### ISSUE TITLE
Estou tentando usar o sikuli com dbehave mas quando clico em um botão ele espera carregar a página e não libera a tela do certificado para ser clicado até dar timeout

### ISSUE THREAD

**Issue by luiscyam** [demoiselle/behave#106]

**Comment by ThiagoNicolielo** [comment]
Nesta parte do código do @luiscyam, ele cita esta classe Screen,
```java
Screen s=new Screen();
            s.click("<path>/OK.png",0);
```
Alguém pode me dizer de qual projeto esta classe Screen pertence? Eu tentei as disponíveis mas nenhuma aceitou ou a instanciação da classe, ou não havia o método click() nelas.

É de alguma outra versão do Sikuli? É via maven ou para utilizar este código dele é necessário instalar manualmente o Sikuli?

Pergunto isto pois eu preciso utilizar outros códigos menos sucintos para fazer a mesma coisa, com o Sikuli que tenho instalado, então, se possível, poderia ser desejável eu utilizar esta classe Screen que contenha este método click(), pois a que eu tenho não o contém.

PS: Estou utilizando o sikuli 1.2.0, por algum motivo foi o que eu consegui fazer funcionar e também aparentemente ele precisa destas versões do javacpp e javacv conforme meu pom.xml abaixo:

```xml
		<!-- Início do bloco de dependências para o Sikuli -->
		<dependency>
			<groupId>org.sikuli</groupId>
			<artifactId>sikuli-api</artifactId>
			<version>1.2.0</version>
		</dependency>

		<dependency>
			<groupId>com.googlecode.javacpp</groupId>
			<artifactId>javacpp</artifactId>
			<version>0.7</version>
		</dependency>

		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacv</artifactId>
			<version>0.8</version>
		</dependency>
		<!-- Final do bloco de dependências para o Sikuli -->
```
