### ISSUE TITLE
Como usar elemento tipo Radio button?

### ISSUE THREAD

**Issue by egrohs** [demoiselle/behave#110]
Alguem já testou/sou clicar em algum radio button? O código abaixo de CommonSteps esta disparando a exceção pois declarei o elemento como Radio... isso é o correto?

@When(value = "clico em \"$elementName\"", priority = 1)
    @Then(value = "clico em \"$elementName\"", priority = 1)
    public void clickButton(String elementName) {
        Element element = runner.getElement(currentPageName, elementName);

```
    if (element instanceof Button) {
        ((Button) element).click();
    } else if (element instanceof Link) {
        ((Link) element).click();
    } else if (element instanceof Menu) {
        ((Menu) element).click();
    } else if (element instanceof MenuItem) {
        ((MenuItem) element).click();
    } else {
        throw new BehaveException("Tipo de elemento [" + element.getClass().getName() + "] inválido");
    }
}
```

**Comment by jorgesartori** [comment]
Fiz uma "manobra" para que o Radio funcione como um Select, visto que com relação ao negócio faz mais sentido. Desta maneira você mapeia apenas um elemento e usa o comando "informo" colocando um valor (dentre os disponiveis) para aquele campo. Acredito que o framework deveria implementar isto internamente de outra forma, mas como solução de contorno vai a dica:
1- Mapear o elemento como Link por XPath, colocando o caminho até o label sem índice para que pegue todos os labels daque radiogroup como no exemplo:
![radio xpath](https://cloud.githubusercontent.com/assets/6615405/9284949/250ec260-42b7-11e5-90fa-83bea0d3a8b5.png)
E acrescentar no final a busca pelo texo "[text()='%param1%']".
O mapeamento fica assim:

@ElementMap(name = "Quantidade de Parcelas", locatorType = ElementLocatorType.XPath, locator = ".//*[@id='form:idQuantidadeParcelas']/tbody/tr/td/label[text()='%param1%']")
	private Link qtdParcelas;

2- Sobrescrever o método inform em seu steps local como no exemplo:
	
      //sobrescrito o método para informar Radio
	@When(value = "informo \"$value\" no campo \"$fieldName\"", priority = 2)
	@Then(value = "informo \"$value\" no campo \"$fieldName\"", priority = 2)
	public void inform(String value, String fieldName) {
		value = DataProviderUtil.replaceValue(value);
		Element element = (Element) runner.getElement(currentPageName, fieldName);
		if (element instanceof Link) {
			clickButtonWithParameters(fieldName, Arrays.asList(value));		
		} else {
			super.inform(value, fieldName);			
		}
	}
