### ISSUE TITLE
 Upload de arquivo para aplicação

### ISSUE THREAD

**Issue by Viveiros** [demoiselle/behave#133]
Pessoal existe alguma frase no DBehave para selecionar arquivo no browser?
Por exemplo uma funcionalidade faz um upload de um arquivo texto para a aplicação.

**Comment by RenatoEller** [comment]
Boa tarde pessoal,
Esta solução já funciona com o Demoiselle 2.5 (HTML5)? 
Ao executar, me deparo com o erro (org.openqa.selenium.WebDriverException: RichFaces is not defined

**Comment by juliancesar** [comment]
Boa tarde @RenatoEller, ainda não tivemos contato com a versão 2.5 do Demoiselle.
Se o problema persistir por favor abra uma nova issue.
