### ISSUE TITLE
DúvidaS na escrita de [hi|e]stórias relacionadas ao trecho de narrativa

### ISSUE THREAD

**Issue by arildojg** [demoiselle/behave#174]
Considerem as palavras-chaves abaixo e o texto (exemplos ficticios) que as procedem:

Narrativa: Efetuar operação tal ...
Como um usuário do tipo tal ...
Desejo realizar operação tal ...

1) Além de servirem como uma informação adicional apenas para leitura, alguém está usando para mais alguma outra finalidade? Qual?
2) O DBehave futuramente vai usá-las para alguma finalidade?
3) Quais problemas podem ocorrer se forem suprimidas das [hi|e]stórias?
4) Tem alguma configuração no plugin do eclipse para o editor não acusar erro nessas palavras quando o idioma é mudado para pt?
5) Corporativamente/formalmente ficou definido usar a palavra "estória" ou "história" para uma "story"?

**Comment by ThiagoNicolielo** [comment]
Só pra atualizar que o link hoje é http://www.aulete.com.br/hist%C3%B3ria
