### ISSUE TITLE
Boas práticas para reuso de passos "semi-genéricos" entre projetos 

### ISSUE THREAD

**Issue by arildojg** [demoiselle/behave#194]
Boa tarde

A medida que estamos utilizando o DBehave nos projetos é comum identificar passos de um projeto que podem ser reaproveitados em outros.

Talvez alguns desses passos sejam genéricos a ponto de serem incorporados ao framework após análise da SUPST, mas nem sempre isso vai ocorrer. Sendo assim,  haverá passos que:
  * não são tão específicos a ponto de servirem apenas a um único projeto, podem ser reaproveitados;
  * não são tão genéricos a ponto de serem incorporados ao framework DBehave.

   Gostaria de receber feedback dos colegas para saber quais práticas estão sendo adotadas para promover o reúso desses passos. Especialmente no que se refere a organização dos mesmos dentro do ALM (área de projeto/stream/componente) e forma de reusá-los nos projeto Maven criados a partir do arquétipo do DBehave para testes com JBehave.

**Comment by ThiagoNicolielo** [comment]
@juliancesar,
Você comentou isso: "NÃO será exibido "$text" - Já foi criado, esta atendendo?"
Não estou encontrando esta frase, utilizo a versão 1.4.1.

Foi retirada?
Grato.

**Comment by arildojg** [comment]
ThiagoNicolielo, este passo é antigo e está dentro de um projeto que criamos internamente apenas para compartilhar passos que poderiam ser reutilizados. Esse projeto segue a idéia comentada nas msgs anteriores dessa issue. Contém passos que são genéricos mas talvez não a ponto de serem incorporados no DBehave.

É um grande candidato a sumir, pois essa abordagem de verificar texto no html todo acaba gerando problemas.
O ideal seria ter uma frase para garantir que o texto não é exibido em um elemento específico, previamente mapeado. Talvez a frase a seguir presente na CommonSteps possa ser usada como base: "ser\u00E1 exibido na \"$elementName\" o valor \"$text\"".

**Comment by arildojg** [comment]
Criamos um projeto onde colocamos classes contendo os steps reutilizáveis. A partir desse projeto criamos um componente e referenciamos ele nos demais projetos via maven/pom.xml. Os classes com steps reutilizaveis que estão nesse projeto extendem a CommonSteps. Nos projetos onde queremos fazer reuso de passos, fazemos as classes de steps específicos do projeto extenderem essas classes de steps reutilizaveis.

**Comment by malaguti** [comment]
Eu faço uma story xxxReuse.story, aonde eu coloco todos os cenários, sem exceção, e faço uma story xxxControl, que vai ser chanada pela classe de teste, e que vai chamar todos os cenários gravados no xxxReuse. Cenários como navegar até chegar em uma tela específica, e cenários aonde eu poso passar as informações de gravação e retorno esperado, eu chamo quantas vezes precisar. Usando parâmetros, eu posso usar o mesmo cenário diversas vezes para executar diversos testes diferentes.

**Comment by malaguti** [comment]
Eu escrevi sobre o assunto postado acima no você.serpro, mas não consegui que o editor respeitasse a identação, e as quebras de linha. Eu estou disponibilizando um DOCX com exemplos dessa prática.
[Abordagem de reuso de cenários.docx](https://github.com/demoiselle/behave/files/316939/Abordagem.de.reuso.de.cenarios.docx)
