### ISSUE TITLE
Método vazio

### ISSUE THREAD

**Issue by egrohs** [demoiselle/behave#252]
O método public void clickRow(String reference) da classe WebGrid, está sem implementação.
Não sei se ele é o ideal quando é necessário clicar em uma linha de tabela referente a um valor, mas parece que sim, ele parece ser a alternativa mais simples e ideal.

**Comment by juliancesar** [comment]
@egrohs, acredito que essa issue não seja mais necessária, pois pelos casos relatados normalmente as questões de grid são tratadas de acordo com o framework de UI utilizado pelo sistema, sendo que para o Primefaces já foi criada um implementação conforme link abaixo.

https://github.com/demoiselle/behave/blob/master/impl/runner/webdriver/src/main/java/br/gov/frameworkdemoiselle/behave/runner/webdriver/ui/primefaces/PrimefacesGrid.java

Caso acredite que seja necessária uma implementação genérica podemos pensar em uma solução e reabrimos a issue.

Obrigado pela contribuição.

**Comment by juliancesar** [comment]
Outra informação importante é que estas situações estão sendo tratadas na issue #61.
