### ISSUE TITLE
Vcs conhecem Node.js?

### ISSUE THREAD

**Issue by egrohs** [demoiselle/behave#254]
Pessoal isso não é um post diretamente sobre DBehave, mas achei importante perguntar ao grupo.
Um colega me falou dessa ferramenta, parece ser bastante usada hoje no mercado não exclusivo para testes, mas para desenvolvimento e automação de uma forma geral.
Alguém conhece, usou, sabe pro e contras?
https://www.youtube.com/watch?v=b7d3P5KGk28

**Comment by fgsl** [comment]
@egrohs, você tem uma sugestão de como usar o Node.js no Dbehave? Qual seria o propósito exatamente? Não entendi qual o problema que precisa ser resolvido.
Eu conheço o npm e acredito que ele é uma ferramenta útil para se incorporar ao Demoiselle Framework o que será natural com a adoção do AngularJS.
Sendo assim, pergunto, posso fechar esta issue?

**Comment by juliancesar** [comment]
Questão fechada por falta de retorno. 
Caso acredite que seja pertinente favor reabrir.
