### ISSUE TITLE
Stacktrace errado...

### ISSUE THREAD

**Issue by egrohs** [demoiselle/behave#255]
Ao fazer reuso de um cenário descrito em outro arquivo, esqueci de citá-lo no "engine.addStories()"
porem o stacktrace acusou uma exceção relacionada a linha SEGUINTE da historia em questão, demorei pra me dar conta...

**Comment by juliancesar** [comment]
@egrohs, você pretende fazer algum Pull Request com relação a este comportamento?

**Comment by egrohs** [comment]
No momento não Julian. Pode fechar e relato.
Em 21/09/2015 11:08, "Julian Cesar" <notifications@github.com> escreveu:
