### ISSUE TITLE
Criação de passos para validação de visibilidade ou não de texto, componentes e componentes parâmetrizados

### ISSUE THREAD

**Issue by rogernobre** [demoiselle/behave#259]
Percebir que na versão 1.4.0-BETA3 existem os seguintes passos:
- ... o elemento "fieldName" está visível e desabilitado
- ... aguardo o elemento "fieldName" estar visível, clicável e habilitado
- ... "elementName" não está visível
- ... será exibido o valor "text" em "elementName" referente a "locatorParameters"
- ... será exibido no "elementName" o valor "text"
- ... será exibido na "elementName" o valor "text"
- ... será exibido "text"

E conversando com várias equipes, percebi que existem variações no mesmo sentido, com relação somente ao texto, com relação ao componente (parametrizado ou nao), com relação ao texto no componente (parametrizado ou nao).
Sugiro a criação dos seguintes passos:
- ... o elemento "fieldName" referente a "locatorParameters" está visível e desabilitado
- ... aguardo o elemento "fieldName" referente a "locatorParameters" estar visível, clicável e habilitado
- ... "elementName" referente a "locatorParameters" não está visível
- ... não será exibido o valor "text" em "elementName" referente a "locatorParameters"
- ... não será exibido no "elementName" o valor "text"
- ... não será exibido na "elementName" o valor "text"
- ... não será exibido "text"

Outra coisa, sugestão de criação de alias nos passos relacionados com o seguinte padrão de escrita:
- ... "elementName" está desabilitado
- ... "elementName" está habilitado
- ... "elementName"  referente a "locatorParameters" está desabilitado
- ... "elementName"  referente a "locatorParameters" está habilitado
- ... "elementName"  referente a "locatorParameters" não está visível
- ... será exibido no "elementName" referente a "locatorParameters" o valor "text" 
- ... será exibido na "elementName" referente a "locatorParameters" o valor "text" 
- ... não será exibido no "elementName" referente a "locatorParameters" o valor "text" 
- ... não será exibido na "elementName" referente a "locatorParameters" o valor "text" 

Queria saber a opinião dos demais, antes de realizar um pull request, neste sentido.

Alguma sugestão, criticas, etc... ???

**Comment by juliancesar** [comment]
Esta issue será fechada por já terem sido implementadas algumas frases relacionadas a estes tratamentos no Pull Request #333. Caso sinta necessidade de reabrir a issue fique a vontade.
