### ISSUE TITLE
Fazer Trim() antes de buscar elementos

### ISSUE THREAD

**Issue by egrohs** [demoiselle/behave#272]
Pessoal alguns métodos da classe CommonSteps, como ex. "clico em ... referente a ..." não estão fazendo trim das strings buscas. Dessa forma ao tentar buscar o valor "1" em uma coluna de uma < table >, não entrou pois estava "           1         " no html. A sugestão seria corrigir os métodos dessa classe.

**Comment by juliancesar** [comment]
@egrohs, você acredita que esta questão ainda seja pertinente?

**Comment by juliancesar** [comment]
Vou fechar esta questão, em caso de ainda ser pertinente favor reabrir.
