### ISSUE TITLE
"Dados as Histórias"/"GivenStories"

### ISSUE THREAD

**Issue by rkazuo** [demoiselle/behave#276]
Bom dia!
Estou com dificuldade em filtrar os cenários de um "GivenStory" conforme explicado no manual do JBehave:
jbehave.org/reference/stable/given-stories.html
Acontece que o filtro não funciona e todos os cenários acabam sendo executados.

E também, ao integrar com ALM, a execução é realizada completamente, mas somente os resultados dos GivenStories são registrados no ALM.

Sei que tem a opção de reuso de cenários (http://demoiselle.sourceforge.net/docs/components/behave/reference/1.3.2/html/behave-story.html#d0e1046). Mas gostaria de saber se é possível utilizar o "GivenStories" com filtros e parâmetros, e também integrar com o ALM, pois acredito que ficaria mais fácil de organizar e manter as histórias.

**Comment by juliancesar** [comment]
@rkazuo, na versão **1.4.2** do dbehave foi necessário voltar a versão do jBehave para a 3.8 devido a um problema com o Windows.
