### ISSUE TITLE
Erro na verificação da presença do loading

### ISSUE THREAD

**Issue by rogernobre** [demoiselle/behave#301]
Estou usando a versão:
Demoiselle Behave 1.4.1-SNAPSHOT em: 12/01/2015 09:48

Estou tendo problemas com relação ao loading, que ora consegue verificar a presença, ora não consegue verificar a presença do componente na tela:

![errocodigo](https://cloud.githubusercontent.com/assets/3092623/5748505/3f0f6e1a-9c1f-11e4-9d62-9f180a29adc6.png)

![erromapeamento](https://cloud.githubusercontent.com/assets/3092623/5748530/64cb0f6a-9c1f-11e4-84e0-4a6859a45627.png)

![errofonte](https://cloud.githubusercontent.com/assets/3092623/5748532/6a3c85fa-9c1f-11e4-91aa-b0709b176ce4.png)

![erroconsole](https://cloud.githubusercontent.com/assets/3092623/5748536/6f347c20-9c1f-11e4-9bc9-d4b8b8ce02db.png)

![okconsole](https://cloud.githubusercontent.com/assets/3092623/5748591/deee92f8-9c1f-11e4-8897-817dc1058b41.png)

Alguém já percebeu isso?

**Comment by juliancesar** [comment]
Não percebi problema até o momento! eu publiquei esta versão SNAPSHOT com estes pontos de log justamente para verificar se existe algum problema. Vamos verificar com calma.

**Comment by rogernobre** [comment]
Percebi que o erro acontece em passos criados no meu projeto.

Exemplo de um passo que faz a validação do conteudo de uma tabela:

	@Then("ser\u00E1 exibido na tabela \"$elementName\" os valores: $table")
	public void textVisibleTable(String elementName, ExamplesTable examplesTable) {
		Element element = runner.getElement(currentPageName, elementName);
		
		if (!(element instanceof Grid)) {
			throw new BehaveException(message.getString("exception-invalid-type", element.getClass().getName()));
		}
		
		WebGrid webGrid = new WebGrid();
		webGrid.setRunner(runner);
		webGrid.setElementMap(element.getElementMap());
		
		webGrid.waitLoading();

Ora funciona ou não, isto é, em modo debug o metodo que faz a verificação do Loading está presente ou não diz que ele está presente e em uma outra execução diz que ele não está presente.

**Comment by rogernobre** [comment]
Desconsidere o que falei. Até em passos comuns deu o erro:

![failed-scenario-bfadf19f-6f5c-4ded-beba-53d9940c8a32](https://cloud.githubusercontent.com/assets/3092623/5767634/d256acaa-9ce8-11e4-9512-6313190c159b.png)

Scenario: Usuário desfavorita todos os critérios
18:56:18,889 DEBUG (pool-2-thread-1) [CommonSteps]: Go to screen Consultar Processo Java
18:56:18,893 DEBUG (pool-2-thread-1) [WebDriverRunner]: Tentar acessar [http://10.32.113.14:8080/eprocesso/consultarProcesso.jsf]
Dado que vou para a tela "Consultar Processo Java"
18:56:22,711 DEBUG (pool-2-thread-1) [CommonSteps]: LOADING - 1/4 - Aguarda o loading estar presente
18:56:22,717 DEBUG (pool-2-thread-1) [CommonSteps]: LOADING - 2/4 - Loading presente
18:56:22,717 DEBUG (pool-2-thread-1) [CommonSteps]: LOADING - 3/4 - Aguarda Loading ficar invisível
18:56:22,737 DEBUG (pool-2-thread-1) [CommonSteps]: LOADING - 4/4 - Loading invisível
Então será exibido na tabela "Filtro de pesquisa" os valores: 

|Palavra-Chave|
|star.png.jsf CPF Responsável Atual|
|star.png.jsf Data do Protocolo|
|star.png.jsf NI Contribuinte|
|star.png.jsf Unidade Atual, Equipe Atual e/ou Atividade Atual|
|star.png.jsf Número de Inscrição|
|star.png.jsf Número Processo|

18:56:24,595 DEBUG (pool-2-thread-1) [WebBase]: LOADING - 1/4 - Aguarda o loading estar presente
18:56:24,602 DEBUG (pool-2-thread-1) [WebBase]: LOADING - 2/4 - Loading NÃO presente
Quando clico em "Remover favoritos de todos"
18:56:24,882 DEBUG (pool-2-thread-1) [CommonSteps]: LOADING - 1/4 - Aguarda o loading estar presente
18:56:24,890 DEBUG (pool-2-thread-1) [CommonSteps]: LOADING - 2/4 - Loading presente
18:56:24,890 DEBUG (pool-2-thread-1) [CommonSteps]: LOADING - 3/4 - Aguarda Loading ficar invisível
18:56:26,978 DEBUG (pool-2-thread-1) [CommonSteps]: LOADING - 4/4 - Loading invisível
Então será exibido na tabela "Filtro de pesquisa" os valores: 

|Palavra-Chave|
|starCinza.png.jsf CPF Responsável Atual|
|starCinza.png.jsf Data do Protocolo|
|starCinza.png.jsf NI Contribuinte|
|starCinza.png.jsf Unidade Atual, Equipe Atual e/ou Atividade Atual|
|starCinza.png.jsf Número de Inscrição|
|starCinza.png.jsf Número Processo|

18:56:29,177 DEBUG (pool-2-thread-1) [CommonSteps]: Go to screen Consultar Processo Java
18:56:29,184 DEBUG (pool-2-thread-1) [WebDriverRunner]: Tentar acessar [http://10.32.113.14:8080/eprocesso/consultarProcesso.jsf]
Quando vou para a tela "Consultar Processo Java"
Então será exibido "Selecione uma palavra-chave na lista abaixo."

Scenario: Usuário altera os critérios favoritos
18:56:30,973 DEBUG (pool-2-thread-1) [CommonSteps]: Go to screen Consultar Processo Java
18:56:30,978 DEBUG (pool-2-thread-1) [WebDriverRunner]: Tentar acessar [http://10.32.113.14:8080/eprocesso/consultarProcesso.jsf]
Dado que vou para a tela "Consultar Processo Java"
Então será exibido "Selecione uma palavra-chave na lista abaixo."
18:56:32,607 DEBUG (pool-2-thread-1) [WebBase]: LOADING - 1/4 - Aguarda o loading estar presente
18:56:32,613 DEBUG (pool-2-thread-1) [WebBase]: LOADING - 2/4 - Loading NÃO presente
18:56:32,927 DEBUG (pool-2-thread-1) [WebBase]: LOADING - 1/4 - Aguarda o loading estar presente
18:56:32,932 DEBUG (pool-2-thread-1) [WebBase]: LOADING - 2/4 - Loading NÃO presente
Quando informo "CPF Responsável Atual" no campo "Selecionar palavra-chave"
18:56:33,241 DEBUG (pool-2-thread-1) [WebBase]: LOADING - 1/4 - Aguarda o loading estar presente
18:56:33,250 DEBUG (pool-2-thread-1) [WebBase]: LOADING - 2/4 - Loading NÃO presente
18:56:33,813 INFO  (pool-2-thread-1) [ScreenShootingMaker]: Screenshot [http://10.32.113.14:8080/eprocesso/consultarProcesso.jsf] salvo em [/home/01069360503/workspace/eprocesso/e-Processo-346689-01069360503/e-Processo-Comum-Testes/01-Sistema/06-Teste/eProcessoIntranetJavaBdd/target/jbehave/view/screenshots/failed-scenario-bfadf19f-6f5c-4ded-beba-53d9940c8a32.png] com [110.477] bytes
Quando informo "Data do Protocolo" no campo "Selecionar palavra-chave" (FAILED)
(java.lang.reflect.UndeclaredThrowableException)
Quando informo "NI Contribuinte" no campo "Selecionar palavra-chave" (NOT PERFORMED)
Quando informo "Unidade/Equipe/Atividade" no campo "Selecionar palavra-chave" (NOT PERFORMED)
Quando informo "Número de Inscrição" no campo "Selecionar palavra-chave" (NOT PERFORMED)

**Comment by rogernobre** [comment]
No primeiro cenário o Loading está presente, no segundo não.

**Comment by rogernobre** [comment]
Rodei os testes hoje de manhã, várias vezes (mais de 20 vezes) e o erro não aconteceu.

**Comment by juliancesar** [comment]
Legal! Eu testei várias vezes e também funcionou.

**Comment by rogernobre** [comment]
Vou fechar a issue. Qualquer coisa eu abro novamente.
