### ISSUE TITLE
Erro com Mapeamento Parametrizável no IE

### ISSUE THREAD

**Issue by rogernobre** [demoiselle/behave#304]
Olá,

Estou tendo problema, com mapeamento parametrizável no IE.

Estou usando elementos com Xpath para esses casos.

Só que o IE não consegue avaliar a expressão, isto é, na verdade ele não encontra o elemento (http://code.google.com/p/selenium/issues/detail?id=2453).

Pelo site acima, fiquei sabendo que seria um bug de um componente do webdriver.

Gostaria saber se alguém já passou por isso, e se teria uma solução alternativa para esta caso mudando o tipo de Xpath para css, class ou tagname...

**Comment by juliancesar** [comment]
@rogernobre, conseguiu avançar no assunto?
Pelo que percebi a issue do link parece parada! Estou tentando simular aqui o problema mas não estou conseguindo, você está usando a versão 1.4.1-SNAPSHOT?

**Comment by rogernobre** [comment]
@juliancesar, sim.

Um exemplo, estou usando o xpath "//tbody[@id='filtroCriterios_data']/tr[td//.='%param1%']/td/a[contains(@id,':favoritar')]" para a seguinte tabela:

<tbody id="filtroCriterios_data" class="ui-datatable-data ui-widget-content"><tr data-ri="0" class="ui-widget-content ui-datatable-even lineOdd,lineEven" role="row"><td role="gridcell"><a id="filtroCriterios:0:desfavoritar" href="#" class="ui-commandlink ui-widget" onclick="PrimeFaces.ab({s:'filtroCriterios:0:desfavoritar',p:'filtroCriterios:0:desfavoritar @(.filtroDinamico)',u:'@(.filtroDinamico)',ps:true});return false;"><img src="/eprocesso/javax.faces.resource/images/star.png.jsf" style="margin-bottom: -3px;"></a>&nbsp;<span id="filtroCriterios:0:nomeCriterio" class="negritoEssencial">CPF Responsável Atual</span></td><td role="gridcell" class="center"><select id="filtroCriterios:0:operador" name="filtroCriterios:0:operador" size="1" style="width:93px;text-align:center;">	<option value="=">=</option>
	<option value="&gt;">&gt;</option>
	<option value="&lt;">&lt;</option>
	<option value="D">Diferente</option>
</select></td><td role="gridcell" class="center">
									
									<!-- Checkbox gen&eacute;rico para os crit&eacute;rios que sejam diferentes dos crit&eacute;rios favoritos iniciais -->
									
									<!-- Textbox gen&eacute;rico para os crit&eacute;rios que sejam diferentes dos crit&eacute;rios favoritos iniciais -->
									
									<!-- Calendar para os crit&eacute;rios do tipo data -->
									
									<!-- Combo gen&eacute;rico para os crit&eacute;rios que sejam diferentes dos crit&eacute;rios favoritos iniciais -->
									
									<!-- Textbox para o n&uacute;mero do Processo -->
									
									<!-- Textbox para o n&uacute;mero de Inscri&ccedil;&atilde;o -->
									
									<!-- Calendar do per&iacute;odo do protocolo -->
									
									<!-- Textbox do NI do Contribuinte -->
									
									<!-- Combo de Unidade/Equipe/Atividade -->
									<!-- Uma vez que s&atilde;o dependentes, for&ccedil;ar a sele&ccedil;&atilde;o dos tr&ecirc;s combos na tela?  -->
									
									<!-- Textbox do CPF do Respons&aacute;vel Atual --><input id="filtroCriterios:0:textboxValorCPFResponsavelAtual" type="text" name="filtroCriterios:0:textboxValorCPFResponsavelAtual" class="textbox-desabilitavel-opaco" maxlength="18" onblur="formata_CNPJ_CPF(this);" onkeypress="javascript:return validarNumero(event);" style="width:100%;"></td><td role="gridcell" class="center"><input id="filtroCriterios:0:checkCriterioEmBranco" type="checkbox" name="filtroCriterios:0:checkCriterioEmBranco" style="vertical-align: middle;" onclick="PrimeFaces.ab({s:this,e:'valueChange',p:'filtroCriterios:0:checkCriterioEmBranco @(.filtroDinamico)',u:'@(.filtroDinamico)',ps:true});"></td><td role="gridcell" class="center"><a id="filtroCriterios:0:excluirCriterio" href="#" class="ui-commandlink ui-widget" onclick="PrimeFaces.ab({s:'filtroCriterios:0:excluirCriterio',p:'filtroCriterios:0:excluirCriterio @(.filtroDinamico)',u:'@(.filtroDinamico)',ps:true});return false;"><img src="/eprocesso/javax.faces.resource/images/fecharLaranjaOff15px.jpg.jsf"></a></td></tr><tr data-ri="1" class="ui-widget-content ui-datatable-odd lineOdd,lineEven" role="row"><td role="gridcell"><a id="filtroCriterios:1:desfavoritar" href="#" class="ui-commandlink ui-widget" onclick="PrimeFaces.ab({s:'filtroCriterios:1:desfavoritar',p:'filtroCriterios:1:desfavoritar @(.filtroDinamico)',u:'@(.filtroDinamico)',ps:true});return false;"><img src="/eprocesso/javax.faces.resource/images/star.png.jsf" style="margin-bottom: -3px;"></a>&nbsp;<span id="filtroCriterios:1:nomeCriterio" class="negritoEssencial">Data do Protocolo</span></td><td role="gridcell" class="center"></td><td role="gridcell" class="center">
									
									<!-- Checkbox gen&eacute;rico para os crit&eacute;rios que sejam diferentes dos crit&eacute;rios favoritos iniciais -->
									
									<!-- Textbox gen&eacute;rico para os crit&eacute;rios que sejam diferentes dos crit&eacute;rios favoritos iniciais -->
									
									<!-- Calendar para os crit&eacute;rios do tipo data -->
									
									<!-- Combo gen&eacute;rico para os crit&eacute;rios que sejam diferentes dos crit&eacute;rios favoritos iniciais -->
									
									<!-- Textbox para o n&uacute;mero do Processo -->
									
									<!-- Textbox para o n&uacute;mero de Inscri&ccedil;&atilde;o -->
									
									<!-- Calendar do per&iacute;odo do protocolo -->Período de <span id="filtroCriterios:1:dataInicialPeriodo"><input id="filtroCriterios:1:dataInicialPeriodo_input" name="filtroCriterios:1:dataInicialPeriodo_input" type="text" class="ui-inputfield ui-widget ui-state-default ui-corner-all hasDatepicker" maxlength="10" size="7" onblur="validarDataCompleta(this);" role="textbox" aria-disabled="false" aria-readonly="false"><button type="button" class="ui-datepicker-trigger ui-button ui-widget ui-state-default ui-corner-all ui-button-icon-only" role="button" aria-disabled="false"><span class="ui-button-icon-left ui-icon ui-icon-calendar"></span><span class="ui-button-text">ui-button</span></button></span> a <span id="filtroCriterios:1:dataFinalPeriodo"><input id="filtroCriterios:1:dataFinalPeriodo_input" name="filtroCriterios:1:dataFinalPeriodo_input" type="text" class="ui-inputfield ui-widget ui-state-default ui-corner-all hasDatepicker" maxlength="10" size="7" onblur="validarDataCompleta(this);" role="textbox" aria-disabled="false" aria-readonly="false"><button type="button" class="ui-datepicker-trigger ui-button ui-widget ui-state-default ui-corner-all ui-button-icon-only" role="button" aria-disabled="false"><span class="ui-button-icon-left ui-icon ui-icon-calendar"></span><span class="ui-button-text">ui-button</span></button></span>
									
									<!-- Textbox do NI do Contribuinte -->
									
									<!-- Combo de Unidade/Equipe/Atividade -->
									<!-- Uma vez que s&atilde;o dependentes, for&ccedil;ar a sele&ccedil;&atilde;o dos tr&ecirc;s combos na tela?  -->
									
									<!-- Textbox do CPF do Respons&aacute;vel Atual --></td><td role="gridcell" class="center"></td><td role="gridcell" class="center"><a id="filtroCriterios:1:excluirCriterio" href="#" class="ui-commandlink ui-widget" onclick="PrimeFaces.ab({s:'filtroCriterios:1:excluirCriterio',p:'filtroCriterios:1:excluirCriterio @(.filtroDinamico)',u:'@(.filtroDinamico)',ps:true});return false;"><img src="/eprocesso/javax.faces.resource/images/fecharLaranjaOff15px.jpg.jsf"></a></td></tr><tr data-ri="2" class="ui-widget-content ui-datatable-even lineOdd,lineEven" role="row"><td role="gridcell"><a id="filtroCriterios:2:desfavoritar" href="#" class="ui-commandlink ui-widget" onclick="PrimeFaces.ab({s:'filtroCriterios:2:desfavoritar',p:'filtroCriterios:2:desfavoritar @(.filtroDinamico)',u:'@(.filtroDinamico)',ps:true});return false;"><img src="/eprocesso/javax.faces.resource/images/star.png.jsf" style="margin-bottom: -3px;"></a>&nbsp;<span id="filtroCriterios:2:nomeCriterio" class="negritoEssencial">NI Contribuinte</span></td><td role="gridcell" class="center"><select id="filtroCriterios:2:operador" name="filtroCriterios:2:operador" size="1" style="width:93px;text-align:center;">	<option value="=">=</option>
	<option value="&gt;">&gt;</option>
	<option value="&lt;">&lt;</option>
	<option value="C">Contém</option>
	<option value="D">Diferente</option>
</select></td><td role="gridcell" class="center">
									
									<!-- Checkbox gen&eacute;rico para os crit&eacute;rios que sejam diferentes dos crit&eacute;rios favoritos iniciais -->
									
									<!-- Textbox gen&eacute;rico para os crit&eacute;rios que sejam diferentes dos crit&eacute;rios favoritos iniciais -->
									
									<!-- Calendar para os crit&eacute;rios do tipo data -->
									
									<!-- Combo gen&eacute;rico para os crit&eacute;rios que sejam diferentes dos crit&eacute;rios favoritos iniciais -->
									
									<!-- Textbox para o n&uacute;mero do Processo -->
									
									<!-- Textbox para o n&uacute;mero de Inscri&ccedil;&atilde;o -->
									
									<!-- Calendar do per&iacute;odo do protocolo -->
									
									<!-- Textbox do NI do Contribuinte --><input id="filtroCriterios:2:textboxValorNIContribuinte" type="text" name="filtroCriterios:2:textboxValorNIContribuinte" class="textbox-desabilitavel-opaco" maxlength="18" onblur="formata_CNPJ_CPF(this);" onkeypress="javascript:return validarNumero(event);" style="width:100%;">
									
									<!-- Combo de Unidade/Equipe/Atividade -->
									<!-- Uma vez que s&atilde;o dependentes, for&ccedil;ar a sele&ccedil;&atilde;o dos tr&ecirc;s combos na tela?  -->
									
									<!-- Textbox do CPF do Respons&aacute;vel Atual --></td><td role="gridcell" class="center"><input id="filtroCriterios:2:checkCriterioEmBranco" type="checkbox" name="filtroCriterios:2:checkCriterioEmBranco" style="vertical-align: middle;" onclick="PrimeFaces.ab({s:this,e:'valueChange',p:'filtroCriterios:2:checkCriterioEmBranco @(.filtroDinamico)',u:'@(.filtroDinamico)',ps:true});"></td><td role="gridcell" class="center"><a id="filtroCriterios:2:excluirCriterio" href="#" class="ui-commandlink ui-widget" onclick="PrimeFaces.ab({s:'filtroCriterios:2:excluirCriterio',p:'filtroCriterios:2:excluirCriterio @(.filtroDinamico)',u:'@(.filtroDinamico)',ps:true});return false;"><img src="/eprocesso/javax.faces.resource/images/fecharLaranjaOff15px.jpg.jsf"></a></td></tr><tr data-ri="3" class="ui-widget-content ui-datatable-odd lineOdd,lineEven" role="row"><td role="gridcell"><a id="filtroCriterios:3:desfavoritar" href="#" class="ui-commandlink ui-widget" onclick="PrimeFaces.ab({s:'filtroCriterios:3:desfavoritar',p:'filtroCriterios:3:desfavoritar @(.filtroDinamico)',u:'@(.filtroDinamico)',ps:true});return false;"><img src="/eprocesso/javax.faces.resource/images/star.png.jsf" style="margin-bottom: -3px;"></a>&nbsp;<span id="filtroCriterios:3:nomeCriterio" class="negritoEssencial">Unidade Atual, Equipe Atual e/ou Atividade Atual</span></td><td role="gridcell" class="center"><select id="filtroCriterios:3:operador" name="filtroCriterios:3:operador" size="1" style="width:93px;text-align:center;" disabled="disabled">	<option value="=">=</option>
</select></td><td role="gridcell" class="center">
									
									<!-- Checkbox gen&eacute;rico para os crit&eacute;rios que sejam diferentes dos crit&eacute;rios favoritos iniciais -->
									
									<!-- Textbox gen&eacute;rico para os crit&eacute;rios que sejam diferentes dos crit&eacute;rios favoritos iniciais -->
									
									<!-- Calendar para os crit&eacute;rios do tipo data -->
									
									<!-- Combo gen&eacute;rico para os crit&eacute;rios que sejam diferentes dos crit&eacute;rios favoritos iniciais -->
									
									<!-- Textbox para o n&uacute;mero do Processo -->
									
									<!-- Textbox para o n&uacute;mero de Inscri&ccedil;&atilde;o -->
									
									<!-- Calendar do per&iacute;odo do protocolo -->
									
									<!-- Textbox do NI do Contribuinte -->
									
									<!-- Combo de Unidade/Equipe/Atividade -->
									<!-- Uma vez que s&atilde;o dependentes, for&ccedil;ar a sele&ccedil;&atilde;o dos tr&ecirc;s combos na tela?  --><select id="filtroCriterios:3:comboUnidade" name="filtroCriterios:3:comboUnidade" size="1" style="width:100%;text-align:left;" onchange="PrimeFaces.ab({s:this,e:'change',p:'filtroCriterios:3:comboUnidade',u:'filtroCriterios:3:comboEquipe filtroCriterios:3:comboAtividade',ps:true});">	<option value="">Selecione a Unidade</option>
	<option value="1|12|1">ALF/AERBLE</option>
	<option value="1|3|1">ALF/AIB</option>
	<option value="24|2|1">ALF/IGI</option>
	<option value="4|10|1">ALF/VIT</option>
	<option value="33|10|1">ARF/FORMIGA</option>
	<option value="1|10|1">ARF/ITE</option>
	<option value="28|10|1">ARF/JUA</option>
	<option value="25|10|1">ARF/SAJ</option>
	<option value="3|6|1">ARQUIVO ÚNICO</option>
	<option value="1|9|1">BA IRF ARATU</option>
	<option value="34|10|1">BA JEQUIE ARF</option>
	<option value="66|3|1">COISA</option>
	<option value="500|3|1">COISA</option>
	<option value="63|3|1">COISA</option>
	<option value="1|5|1">CSRF</option>
	<option value="378|1|1">DRF JUAZNORTE</option>
	<option value="243|1|1">DRF/AJU</option>
	<option value="226|1|1">DRF/BAR</option>
	<option value="305|1|1">DRF/BEL</option>
	<option value="42|8|1">DRF-FLO-ARQVO-PI</option>
	<option value="180|1|1">DRF/FOR</option>
	<option value="84|1|1">DRF/FSA</option>
	<option value="1|1|1">DRF/GAB</option>
	<option value="212|1|1">DRF/NA</option>
	<option value="401|1|1">DRF/RJ1</option>
	<option value="158|1|1">DRF/SPR</option>
	<option value="297|1|1">DRJ/BEL</option>
	<option value="1|2|1">DRJ/GAB</option>
	<option value="10|8|1">EQUIPE PGFN</option>
	<option value="23|3|1">eu teste 2</option>
	<option value="414|1|1">GAB</option>
	<option value="360|1|1">GABIN/FEIRA</option>
	<option value="211|1|1">HIERAR</option>
	<option value="9|9|1">IRF AREIA BRANCA</option>
	<option value="3|9|1">IRF/ALM</option>
	<option value="7|9|1">IRF/ANT</option>
	<option value="40|8|1">PFN SPO</option>
	<option value="32|8|1">PFN/ACRE</option>
	<option value="433|1|1">PI TERESINA DRF</option>
	<option value="407|1|1">RS DRF NOVO HAMBURGO</option>
	<option value="432|1|1">SP CAC TATUAPE</option>
	<option value="41|8|1">SP OSASCO  PGFN</option>
	<option value="53|3|1">Teste</option>
	<option value="56|3|1">Teste</option>
	<option value="51|3|1">Teste</option>
	<option value="58|3|1">Teste</option>
	<option value="57|3|1">Teste</option>
	<option value="54|3|1">Teste</option>
	<option value="55|3|1">Teste</option>
	<option value="61|3|1">Teste</option>
	<option value="52|3|1">Teste</option>
	<option value="59|3|1">Teste</option>
	<option value="34|4|1">TESTE DE CC</option>
	<option value="7|8|1">TESTE INCLUSAO</option>
	<option value="162|1|1">TESTE PARA INCLUIR UNIDADE1</option>
	<option value="448|1|1">TESTE 01100106</option>
	<option value="380|1|1">TESTE'TT</option>
	<option value="10|9|1">TINCUNID</option>
	<option value="37|8|1">UNID/EXC</option>
	<option value="1|4|1">1 CC-MF-DF</option>
	<option value="10|4|1">2 CC/MF/DF (U)</option>
	<option value="31|4|1">20|5</option>
	<option value="17|4|1">3 CC-MF-DF</option>
	<option value="11|8|1">50|88</option>
</select><div style="height: 3px;"></div><select id="filtroCriterios:3:comboEquipe" name="filtroCriterios:3:comboEquipe" size="1" style="width:100%;text-align:left;" disabled="disabled">	<option value="">Selecione acima primeiro</option>
</select><div style="height: 3px;"></div><select id="filtroCriterios:3:comboAtividade" name="filtroCriterios:3:comboAtividade" size="1" style="width:100%;text-align:left;" disabled="disabled">	<option value="">Selecione acima primeiro</option>
</select>
									
									<!-- Textbox do CPF do Respons&aacute;vel Atual --></td><td role="gridcell" class="center"></td><td role="gridcell" class="center"><a id="filtroCriterios:3:excluirCriterio" href="#" class="ui-commandlink ui-widget" onclick="PrimeFaces.ab({s:'filtroCriterios:3:excluirCriterio',p:'filtroCriterios:3:excluirCriterio @(.filtroDinamico)',u:'@(.filtroDinamico)',ps:true});return false;"><img src="/eprocesso/javax.faces.resource/images/fecharLaranjaOff15px.jpg.jsf"></a></td></tr><tr data-ri="4" class="ui-widget-content ui-datatable-even lineOdd,lineEven" role="row"><td role="gridcell"><a id="filtroCriterios:4:desfavoritar" href="#" class="ui-commandlink ui-widget" onclick="PrimeFaces.ab({s:'filtroCriterios:4:desfavoritar',p:'filtroCriterios:4:desfavoritar @(.filtroDinamico)',u:'@(.filtroDinamico)',ps:true});return false;"><img src="/eprocesso/javax.faces.resource/images/star.png.jsf" style="margin-bottom: -3px;"></a>&nbsp;<span id="filtroCriterios:4:nomeCriterio" class="negritoEssencial">Número de Inscrição</span></td><td role="gridcell" class="center"><select id="filtroCriterios:4:operador" name="filtroCriterios:4:operador" size="1" style="width:93px;text-align:center;" disabled="disabled">	<option value="=">=</option>
	<option value="&gt;">&gt;</option>
	<option value="&lt;">&lt;</option>
	<option value="C">Contém</option>
	<option value="D">Diferente</option>
</select></td><td role="gridcell" class="center">
									
									<!-- Checkbox gen&eacute;rico para os crit&eacute;rios que sejam diferentes dos crit&eacute;rios favoritos iniciais -->
									
									<!-- Textbox gen&eacute;rico para os crit&eacute;rios que sejam diferentes dos crit&eacute;rios favoritos iniciais -->
									
									<!-- Calendar para os crit&eacute;rios do tipo data -->
									
									<!-- Combo gen&eacute;rico para os crit&eacute;rios que sejam diferentes dos crit&eacute;rios favoritos iniciais -->
									
									<!-- Textbox para o n&uacute;mero do Processo -->
									
									<!-- Textbox para o n&uacute;mero de Inscri&ccedil;&atilde;o --><input id="filtroCriterios:4:textboxValorNumeroInscricao" type="text" name="filtroCriterios:4:textboxValorNumeroInscricao" class="textbox-desabilitavel-opaco" onkeypress="return validarNumerosProcessoVirgula(event);" style="width:100%;">
									
									<!-- Calendar do per&iacute;odo do protocolo -->
									
									<!-- Textbox do NI do Contribuinte -->
									
									<!-- Combo de Unidade/Equipe/Atividade -->
									<!-- Uma vez que s&atilde;o dependentes, for&ccedil;ar a sele&ccedil;&atilde;o dos tr&ecirc;s combos na tela?  -->
									
									<!-- Textbox do CPF do Respons&aacute;vel Atual --></td><td role="gridcell" class="center"><input id="filtroCriterios:4:checkCriterioEmBranco" type="checkbox" name="filtroCriterios:4:checkCriterioEmBranco" style="vertical-align: middle;" onclick="PrimeFaces.ab({s:this,e:'valueChange',p:'filtroCriterios:4:checkCriterioEmBranco @(.filtroDinamico)',u:'@(.filtroDinamico)',ps:true});"></td><td role="gridcell" class="center"><a id="filtroCriterios:4:excluirCriterio" href="#" class="ui-commandlink ui-widget" onclick="PrimeFaces.ab({s:'filtroCriterios:4:excluirCriterio',p:'filtroCriterios:4:excluirCriterio @(.filtroDinamico)',u:'@(.filtroDinamico)',ps:true});return false;"><img src="/eprocesso/javax.faces.resource/images/fecharLaranjaOff15px.jpg.jsf"></a></td></tr><tr data-ri="5" class="ui-widget-content ui-datatable-odd lineOdd,lineEven" role="row"><td role="gridcell"><a id="filtroCriterios:5:desfavoritar" href="#" class="ui-commandlink ui-widget" onclick="PrimeFaces.ab({s:'filtroCriterios:5:desfavoritar',p:'filtroCriterios:5:desfavoritar @(.filtroDinamico)',u:'@(.filtroDinamico)',ps:true});return false;"><img src="/eprocesso/javax.faces.resource/images/star.png.jsf" style="margin-bottom: -3px;"></a>&nbsp;<span id="filtroCriterios:5:nomeCriterio" class="negritoEssencial">Número Processo</span></td><td role="gridcell" class="center"><select id="filtroCriterios:5:operador" name="filtroCriterios:5:operador" size="1" style="width:93px;text-align:center;" disabled="disabled">	<option value="=">=</option>
	<option value="&gt;">&gt;</option>
	<option value="&lt;">&lt;</option>
	<option value="C">Contém</option>
	<option value="D">Diferente</option>
</select></td><td role="gridcell" class="center">
									
									<!-- Checkbox gen&eacute;rico para os crit&eacute;rios que sejam diferentes dos crit&eacute;rios favoritos iniciais -->
									
									<!-- Textbox gen&eacute;rico para os crit&eacute;rios que sejam diferentes dos crit&eacute;rios favoritos iniciais -->
									
									<!-- Calendar para os crit&eacute;rios do tipo data -->
									
									<!-- Combo gen&eacute;rico para os crit&eacute;rios que sejam diferentes dos crit&eacute;rios favoritos iniciais -->
									
									<!-- Textbox para o n&uacute;mero do Processo --><input id="filtroCriterios:5:textboxValorNumeroProcesso" type="text" name="filtroCriterios:5:textboxValorNumeroProcesso" class="textbox-desabilitavel-opaco" onblur="validarProcessos(removerCaracteresEspeciais(this.value), this);" onkeypress="return validarNumerosProcessoVirgula(event);" style="width:100%;">
									
									<!-- Textbox para o n&uacute;mero de Inscri&ccedil;&atilde;o -->
									
									<!-- Calendar do per&iacute;odo do protocolo -->
									
									<!-- Textbox do NI do Contribuinte -->
									
									<!-- Combo de Unidade/Equipe/Atividade -->
									<!-- Uma vez que s&atilde;o dependentes, for&ccedil;ar a sele&ccedil;&atilde;o dos tr&ecirc;s combos na tela?  -->
									
									<!-- Textbox do CPF do Respons&aacute;vel Atual --></td><td role="gridcell" class="center"></td><td role="gridcell" class="center"><a id="filtroCriterios:5:excluirCriterio" href="#" class="ui-commandlink ui-widget" onclick="PrimeFaces.ab({s:'filtroCriterios:5:excluirCriterio',p:'filtroCriterios:5:excluirCriterio @(.filtroDinamico)',u:'@(.filtroDinamico)',ps:true});return false;"><img src="/eprocesso/javax.faces.resource/images/fecharLaranjaOff15px.jpg.jsf"></a></td></tr></tbody>

No Chrome e Firefox funciona e no IE não.

**Comment by juliancesar** [comment]
@rogernobre, você conseguiu avançar no assunto? Ainda precisa de ajuda?

**Comment by rogernobre** [comment]
A solução foi usar id para cada um dos elementos na tela.

O problema do que eu percebi seria a volta na arvore na busca de elementos utilizando xpath.

No projeto em que estou, preciso usar o IE9.

Não testei em versões mais novas do IE.

**Comment by rogernobre** [comment]
Vou tentar uma solução utilizando ".." para ver o que é que ocorre. Depois, reporto aqui.

**Comment by juliancesar** [comment]
@rogernobre, algum retorno sobre o assunto?
Seria interessante testar com a versão **1.5.1-SNAPSHOT**.

**Comment by juliancesar** [comment]
@rogernobre, algum retorno sobre o assunto?
Realmente seria interessante testar com a versão **1.5.1-SNAPSHOT** com as últimas versões de Drivers.

**Comment by juliancesar** [comment]
Rogério, vou fechar esta issue, caso o problema ainda persista pode reabrir.
