### ISSUE TITLE
Não consigo usar propriedades do pom.xml no behave.properties

### ISSUE THREAD

**Issue by rogernobre** [demoiselle/behave#305]
Não consigo usar propriedades do pom.xml no behave.properties

Estou usando a versão 1.4.1-SNAPSHOT do DBehave e a versão 3.0.5 do maven (demoiselle 2)

Em behave.properties:

behave.runner.screen.driverPath=${behave.runner.screen.driverPath}
behave.runner.screen.type=${behave.runner.screen.type}
behave.runner.screen.remote.name=${behave.runner.screen.remote.name}
behave.runner.screen.remote.url=${behave.runner.screen.remote.url}

No meu pom.xml:
```
<properties>
<behave.runner.screen.driverPath>./src/test/resources/chromedriver</behave.runner.screen.driverPath>
    <behave.runner.screen.remote.name></behave.runner.screen.remote.name>
    <behave.release.version>1.4.1-SNAPSHOT</behave.release.version>
    <behave.runner.screen.remote.url></behave.runner.screen.remote.url>
    <behave.runner.screen.type>GoogleChrome</behave.runner.screen.type>
  </properties>
```
Quando rodo, dar o seguinte erro:

11:07:28,865 DEBUG (main) [PropertiesLoaderUtil]: open: /home/01069360503/workspace/eprocesso/e-Processo-346689-01069360503/e-Processo-Comum-Testes/01-Sistema/06-Teste/eProcessoIntranetJavaBdd/target/test-classes/behave.properties
11:07:28,867 DEBUG (main) [PropertiesLoaderUtil]: open: file:/opt/demoiselle/tool/maven-repo/br/gov/frameworkdemoiselle/component/behave/demoiselle-behave-parser-jbehave/1.4.1-SNAPSHOT/demoiselle-behave-parser-jbehave-1.4.1-SNAPSHOT.jar!/behave.properties
11:07:28,868 DEBUG (main) [PropertiesLoaderUtil]: open: file:/opt/demoiselle/tool/maven-repo/br/gov/frameworkdemoiselle/component/behave/demoiselle-behave-core/1.4.1-SNAPSHOT/demoiselle-behave-core-1.4.1-SNAPSHOT.jar!/behave.properties
11:07:28,868 DEBUG (main) [PropertiesLoaderUtil]: open: file:/opt/demoiselle/tool/maven-repo/br/gov/frameworkdemoiselle/component/behave/demoiselle-behave-runner-webdriver/1.4.1-SNAPSHOT/demoiselle-behave-runner-webdriver-1.4.1-SNAPSHOT.jar!/behave.properties
11:07:28,869 DEBUG (main) [PropertiesLoaderUtil]: open: file:/opt/demoiselle/tool/maven-repo/br/gov/frameworkdemoiselle/component/behave/demoiselle-behave-integration-alm/1.4.1-SNAPSHOT/demoiselle-behave-integration-alm-1.4.1-SNAPSHOT.jar!/behave.properties
11:07:29,094 DEBUG (main) [BehaveContext]: addStoriesReuse:/stories
11:07:29,095 DEBUG (main) [BehaveContext]: addStories:/stories/functional/acessar_consultar_processo_local.story
11:07:29,095 DEBUG (main) [BehaveContext]: addStories:/stories/functional/inicializar_dados.story
11:07:29,095 DEBUG (main) [BehaveContext]: addStories:/stories/functional/selecionar_colunas.story
11:07:29,095 INFO  (main) [BehaveContext]: --------------------------------
11:07:29,095 INFO  (main) [BehaveContext]: Demoiselle Behave Iniciado
11:07:29,095 INFO  (main) [BehaveContext]: Demoiselle Behave 1.4.1-SNAPSHOT em: 05/02/2015 15:55
11:07:29,095 INFO  (main) [BehaveContext]: --------------------------------
11:07:29,095 DEBUG (main) [BehaveConfig]: ------- Propriedades ----------
11:07:29,095 DEBUG (main) [BehaveConfig]: ambiente=local
11:07:29,096 DEBUG (main) [BehaveConfig]: banco.eprocesso=DOC21
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.integration.alm.autoAssociateTestCaseInPlan=true
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.integration.alm.enabled=false
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.integration.alm.projectArea=e-processo+%28Gerenciamento+de+Qualidade%29
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.integration.alm.testPlanId=3164
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.integration.alm.url.security=https://alm.serpro/qm/j_security_check
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.integration.alm.url.services=https://alm.serpro/qm/service/com.ibm.rqm.integration.service.IIntegrationService/
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.integration.authenticator.host=localhost
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.integration.authenticator.port=9991
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.message.locale=pt
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.parser.commonssteps.enabled=true
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.parser.delayBetweenSteps=0
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.parser.identification.scenario.pattern.en=^(\s)*(SCENARIO|Scenario|scenario):(.*)
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.parser.identification.scenario.pattern.pt=^(\s)*(CENÁRIO|Cenário|cenário):(.*)
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.parser.language=pt
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.parser.prefixes.bdd.pattern.en=^(\s)*(GIVEN |WHEN |THEN |AND |BUT |Given |When |Then |And |But |given |when |then |and |but )(.*)
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.parser.prefixes.bdd.pattern.pt=^(\s)*(DADO |QUANDO |ENTÃO |E |MAS |Dado |Quando |Então |Mas |dado |quando |então |e |mas )(.*)
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.parser.story.extension.converted=storyConverted
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.parser.story.extension.original=story
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.parser.story.timeout=21600
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.runner.catchUIException=org.openqa.selenium.StaleElementReferenceException
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.runner.proxy.enabled=false;
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.runner.proxy.url=
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.runner.screen.driverPath=${behave.runner.screen.driverPath}
11:07:29,096 DEBUG (main) [BehaveConfig]: behave.runner.screen.maxWait=20000
11:07:29,097 DEBUG (main) [BehaveConfig]: behave.runner.screen.minWait=100
11:07:29,097 DEBUG (main) [BehaveConfig]: behave.runner.screen.remote.name=${behave.runner.screen.remote.name}
11:07:29,097 DEBUG (main) [BehaveConfig]: behave.runner.screen.remote.url=${behave.runner.screen.remote.url}
11:07:29,097 DEBUG (main) [BehaveConfig]: behave.runner.screen.type=${behave.runner.screen.type}
11:07:29,097 DEBUG (main) [BehaveConfig]: behave.runner.window.maximize.enabled=true
11:07:29,097 DEBUG (main) [BehaveConfig]: behave.version=1.4.1-SNAPSHOT em: 05/02/2015 15:55
11:07:29,097 DEBUG (main) [BehaveConfig]: botao.ok.certificado=ok.png
11:07:29,097 DEBUG (main) [BehaveConfig]: certificado.beraldo=05037383870.png
11:07:29,097 DEBUG (main) [BehaveConfig]: certificado.florisvaldo=05136946504.png
11:07:29,097 DEBUG (main) [BehaveConfig]: certificado.marlene=33702241949.png
11:07:29,097 DEBUG (main) [BehaveConfig]: certificado.padrao=05136946504.png
11:07:29,097 DEBUG (main) [BehaveConfig]: cpf.beraldo=05037383870
11:07:29,097 DEBUG (main) [BehaveConfig]: cpf.florisvaldo=05136946504
11:07:29,097 DEBUG (main) [BehaveConfig]: cpf.marlene=33702241949
11:07:29,097 DEBUG (main) [BehaveConfig]: cpf.padrao=05136946504
11:07:29,097 DEBUG (main) [BehaveConfig]: load.level=2
11:07:29,097 DEBUG (main) [BehaveConfig]: nome.beraldo=BERALDO TADEU VIZIBELLI
11:07:29,097 DEBUG (main) [BehaveConfig]: nome.florisvaldo=FLORISVALDO FELICIO DE CARVALHO
11:07:29,097 DEBUG (main) [BehaveConfig]: nome.marlene=MARLENE AMARAL
11:07:29,097 DEBUG (main) [BehaveConfig]: numero.processo.digital=10010000217041410
11:07:29,098 DEBUG (main) [BehaveConfig]: tipologin.beraldo=certificado
11:07:29,098 DEBUG (main) [BehaveConfig]: tipologin.florisvaldo=certificado
11:07:29,098 DEBUG (main) [BehaveConfig]: tipologin.marlene=certificado
11:07:29,098 DEBUG (main) [BehaveConfig]: tipologin.padrao=certificado
11:07:29,098 DEBUG (main) [BehaveConfig]: url.asp=https://10.32.113.15
11:07:29,098 DEBUG (main) [BehaveConfig]: url.java.retorno=http://10.32.113.14:8080/eprocesso
11:07:29,098 DEBUG (main) [BehaveConfig]: url.java=http://10.32.113.14:8080/eprocesso
11:07:29,098 DEBUG (main) [BehaveConfig]: url.login.eprocesso.java=https://www1.suiterfb.desenv.serpro/camweb/grupo?sis=E-PRO&url=eprocesso.suiterfb.desenv.serpro%2Fjava2%2F
11:07:29,098 DEBUG (main) [BehaveConfig]: url.login.eprocesso=https://www1.suiterfb.desenv.serpro/camweb/grupo?sis=E-PRO&url=eprocesso.suiterfb.desenv.serpro%2F
11:07:29,098 DEBUG (main) [BehaveConfig]: url.suite=https://www.suiterfb.desenv.serpro
11:07:29,098 DEBUG (main) [BehaveConfig]: -------------------------------
11:07:29,325 INFO  (main) [JBehaveParser]: Configurando Parser JBehave...
11:07:29,395 INFO  (main) [JBehaveParser]: Iniciando Parser JBehave...
11:07:29,395 INFO  (main) [JBehaveParser]: Executando história: [[stories/functional/acessar_consultar_processo_local.storyConverted, stories/functional/inicializar_dados.storyConverted, stories/functional/selecionar_colunas.storyConverted]]
Processing system properties {}
Using controls EmbedderControls[batch=false,skip=false,generateViewAfterStories=true,ignoreFailureInStories=true,ignoreFailureInView=true,verboseFailures=true,verboseFiltering=false,storyTimeoutInSecs=1296000,failOnStoryTimeout=false,threads=1]

(BeforeStories)
11:07:29,626 INFO  (main) [BeforeAfterSteps]: 

11:07:29,626 INFO  (main) [BeforeAfterSteps]: >>Iniciando Aplicação<<
br.gov.frameworkdemoiselle.behave.parser.jbehave.BeforeAfterSteps.startStories() (FAILED)
(org.jbehave.core.failures.BeforeOrAfterFailed: Method startStories (annotated with @BeforeStories in class br.gov.frameworkdemoiselle.behave.parser.jbehave.BeforeAfterSteps) failed: java.lang.IllegalArgumentException: No enum const class br.gov.frameworkdemoiselle.behave.runner.webdriver.util.WebBrowser.${behave.runner.screen.type})
11:07:29,698 ERROR (main) [ScreenShootingMaker]: Erro ao salvar screenshot [] caminho [/home/01069360503/workspace/eprocesso/e-Processo-346689-01069360503/e-Processo-Comum-Testes/01-Sistema/06-Teste/eProcessoIntranetJavaBdd/target/jbehave/view/screenshots/failed-scenario-03fcdd43-3f54-4bd7-9cd4-ba4b125d129a.png] causa [null]
11:07:29,698 ERROR (main) [ScreenShootingMaker]: java.lang.NullPointerException

Running story stories/functional/acessar_consultar_processo_local.storyConverted

**Comment by juliancesar** [comment]
@rogernobre, isso que você esta tentando fazer é um recurso do Maven, o erro do dbehave é que a propriedade **behave.runner.screen.type** está com **${behave.runner.screen.type}** o que dá erro na hora de converter a Enum no Java, pois não existe um navegador com esse nome.

Por onde você esta rodando o teste?
Verifique se a goal process resources está funcionando corretamente.

**Comment by rogernobre** [comment]
@juliancesar, via maven.

Desculpe a ignorância (só sei o básico de maven) , mas abri a issue por que quando uso o archetype do demoiselle, eu consigo usar as propriedades nos arquivos de configurações. E no DBehave eu não consigo.

Vou ver aqui o que possa está rodando errado.

**Comment by rogernobre** [comment]
@juliancesar, comparando os dois arquivos (pom.xml de um projeto demoiselle e dbehave), encontrei isso aqui:
```
- Demoiselle
    <testResources>
      <testResource>
        <filtering>true</filtering>
...
      </testResource>
    </testResources>
-Dbehave
    <testResources>
      <testResource>
...
      </testResource>
    </testResources>
```
Isto é, no pom do Dbehave não tem a tag filtering.

Seria esta a causa ou estou enganado?

**Comment by botelhojp** [comment]
É isso ai, o filtering é responsável por parsear os properties. Set para true que deve funcionar.

**Comment by rogernobre** [comment]
Funcionou:
```
	<build>
		<testResources>
			<testResource>
				<filtering>true</filtering>
				<directory>./src/test/resources</directory>
			</testResource>
		</testResources>
	</build>
```
