### ISSUE TITLE
Problema na verificação de campos readonly

### ISSUE THREAD

**Issue by juliancesar** [demoiselle/behave#306]
A lógica de verificação dos campos readonly esta errada, fazendo com que campos com o atributo _readonly_ não sejam identificados como somente leitura na frase **Então o elemento "<CAMPO>" está visível e desabilitado**

**Comment by ThiagoNicolielo** [comment]
@juliancesar 
Não sei se é o que você quis dizer, mas eu fiz um teste e aparentemente o campo estando desabilitado ou mesmo habilitado, passa do mesmo jeito:

Então aguardo o elemento "Valor da participação no capital subscrito" estar visível, clicável e habilitado
!-- Quando seleciono a opção de valor "16-Presidente" no campo "Qualificação"
Então o elemento "Valor da participação no capital subscrito" está visível e desabilitado

Isso passa, sendo que, na aplicação, a frase comentada faz com que o campo continue visível, mas fica desabilitado. Estando comentada, o campo permanece como estava, ou seja, visível, clicável e habilitado, porém a frase que verifica que está visível e desabilitado deveria falhar neste caso.

Como disse, não sei se é o que você quis dizer com "a lógica de verificação está errada", só pra ficar registrado.

**Comment by juliancesar** [comment]
@ThiagoNicolielo, o que ocorre é que no HTML existem algumas maneiras de verificar se o campo esta desabilitado, por exemplo: ele pode somente ter o atributo _disabled_ ou ter o atributo _disable_ mas tem que estar com valor true (**disabled="true"**), a maneira com que isso é interpretado varia entre os navegadores, antes a lógica dentro do dbehave era bem específica, agora fiz uma lógica bem abrangente. Talvez olhando o código fonte você consiga entender o que estou dizendo.

No seu caso o campo provavelmente é um "select" do Primefaces, o que é outra situação completamente diferente do normal, pois o elemento que o usuário manipula é um DIV e não um SELECT como no HTML e a principio esse tratamento também é feito pelo dbehave.

Estas modificações que fiz estão disponíveis a partir da 1.4.2, favor testar novamente com esta versão e nos dar o retorno.

**Comment by ThiagoNicolielo** [comment]
Não funcionou, Julian.

Já estou usando a 1.4.2

O campo que é checado para conferir que está visível e desabilitado, tem o seguinte código html no momento em que o DBehave executa a frase:

<input type="text" class="ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-disabled" name="conteudo:j_id409440119_62a49ac3:tabQSa:valorParticipacaoSocio_input" id="conteudo:j_id409440119_62a49ac3:tabQSa:valorParticipacaoSocio_input" disabled="disabled">

Observe que usa a classe ui-state-disabled e também o atributo disabled="disabled"
Não sei se é algo que possa ser específico deste projeto, esta classe ui-state-disabled, mas imagino que seja do PrimeFaces.

**Comment by juliancesar** [comment]
@ThiagoNicolielo, no caso mencionado, ele passa ou não passa com a frase **Então o elemento "INPUT" está visível e desabilitado**? 
Pelo código o seu caso esta coberto, pois ele possui o atributo **disabled**, se não passar é pq provavelmente ele está visivel.

Favor testar com a versão *1.4.3-SNAPSHOT** para que tenhamos a mesma visão do problema.

**Comment by ThiagoNicolielo** [comment]
Sim, funciona no 1.4.3-SNAPSHOT, ou seja, passa se estiver visível mas desabilitado e não passa se estiver visível e habilitado.

Não estou conseguindo usar versões a partir do 1.4.1 neste momento, por outro problema, que já informei aqui, portanto, esta corrente issue por enquanto parece estar OK.

Obrigado.

**Comment by juliancesar** [comment]
@ThiagoNicolielo, então pelo que entendi podemos fechar essa issue, correto?

**Comment by ThiagoNicolielo** [comment]
Sim!

**Comment by juliancesar** [comment]
OK @ThiagoNicolielo, vou fechar a issue e no caso de ter mais problemas pode reabrir.

Só para eu acompanhar, quais são os outros problemas e suas respectivas issues/PSFs?

**Comment by ThiagoNicolielo** [comment]
Issue #308
