### ISSUE TITLE
Filtro de histórias não funciona para mais de uma história

### ISSUE THREAD

**Issue by ahvsoares** [demoiselle/behave#307]
Tentei usar filtro de histórias (descrito na [issue #248] (https://github.com/demoiselle/behave/issues/248)) no DBehave fazendo:

*eng = BehaveContext.getInstance();
eng.run("/stories", StoryOrScenarioFilter.story("****lista.historias****"));*

quando passo apenas uma história em "**lista.historias**", funciona, mas quando tento passar mais de uma história não executa nada.

Por exemplo, quando faço

*eng.run("/stories", StoryOrScenarioFilter.story("Admitir empregado aba dados pessoais"));*

a aplicação roda, mas quando faço

*eng.run("/stories", StoryOrScenarioFilter.story("Admitir empregado aba dados pessoais;Admitir empregado aba endereço residencial"));*

não roda.

Tentei substituir "***;***" por "***,***" como separador e mesmo assim não rodou.

**Comment by mestihudson** [comment]
Alexandre, o filtro funciona a base de uma expressão regular e não de uma
lista de valores. Tente escrever uma expressão regular que marque as duas
histórias e funcionará.
Em qua, 11 de fev de 2015 às 17:09, Alexandre Henrique Vieira Soares <
notifications@github.com> escreveu:

**Comment by ahvsoares** [comment]
Ok, funcionou.

Seria bom que isso estivesse escrito na documentação e com exemplos, como foi feito para o caso de apenas uma história.

Muito obrigado, @mestihudson !

:-)

**Comment by juliancesar** [comment]
@ahvsoares, realmente exatamente essa funcionalidade ainda não esta documentada, contudo outros filtros já estão. Seria interessante você fazer um Pull Request com uma sugestão de melhoria nesta parte.

http://demoiselle.sourceforge.net/docs/components/behave/reference/lastversion/html/behave-configuracao-testes.html#d0e1794

Obrigado pela contribuição.
