### ISSUE TITLE
Não preenche TextField do Primefaces com máscara (a partir da v1.4.1)

### ISSUE THREAD

**Issue by gugaemc** [demoiselle/behave#308]
Quando usamos a frase &lt;&lt;informo "VALOR" no campo "CAMPO"&gt;&gt; em um campo de texto que usa máscara, o Behave não está preenchendo o valor no campo. Fica piscando mas não preenche.

Criei outra frase para usar o "sendKeys()" em vez do "sendKeysWithTries()", mas ele simplesmente não preenche o campo e passa para o próximo.

Ocorre da versão 1.4.1 do Behave pra a frente. Testamos com a versão 1.3.2 e 1.4.0, e isso não ocorre nelas.

Estamos usando o Primefaces 5.0 na implementação.

**Comment by botelhojp** [comment]
Para entender melhor, informe o valor literalmente que você está informando e o tipo da máscara. Por exemplo:
Máscara de CPF: ###.###.###-##
Valor informado na história: 000.000.000-00 ou  00000000000

**Comment by gugaemc** [comment]
É exatamente um CPF, estou informando o valor: 555.555.555-55

**Comment by rogernobre** [comment]
Solução de contorno:

'''
	@When("informo o texto \"$text\" em \"$elementName\"")
	public WebElement informText(String text, String elementName) {
		WebElement webElement = getWebElement(runner, currentPageName, elementName);
		
		webElement.clear();
		
		webElement.sendKeys(text);
		
		webElement.sendKeys(Keys.TAB);
		
		return webElement;
	}
'''

**Comment by gugaemc** [comment]
Agora está funcionando, mesmo sem fazer alterações.
Coloquei um `clear()` antes do `sendKeys()` e funcionou. Depois removi, e continuou funcionando.
Vou testar em outras máquinas aqui pra ver como se comporta. Depois dou um retorno.

**Comment by botelhojp** [comment]
Então... fiz um exemplo (vide commit https://github.com/demoiselle/behave/commit/dd263909ebb9b5b8e0df1560191ebfd970e6b13d) na página do primefaces http://www.primefaces.org/showcase/ui/input/inputMask.xhtml e tudo funcionou redondo sem sobrescrever nenhum método.

**Comment by rogernobre** [comment]
No meu caso é um javascript que formata o valor do campo após o preenchimento do usuário:
```
<input name="filtroCriterios:0:textboxValorCPFResponsavelAtual" class="textbox-desabilitavel-opaco" id="filtroCriterios:0:textboxValorCPFResponsavelAtual" style="width: 100%;" onkeypress="javascript:return validarNumero(event);" onblur="formata_CNPJ_CPF(this);" type="text" maxLength="18"/>
```
Ai dar erro na verificação com ou sem mascara:
```
Quando informo "123456789" no campo "CPF Responsável Atual"
Então será exibido "O NI deve ter 11 ou 14 dígitos!"
Quando informo "05136946544" no campo "CPF Responsável Atual"
Então será exibido "CPF com Dígito Verificador inválido."
Quando informo "05136946504" no campo "CPF Responsável Atual" (FAILED)
(java.lang.reflect.UndeclaredThrowableException)
11:50:01,746 INFO  (pool-1-thread-1) [ScreenShootingMaker]: Screenshot [http://10.32.113.14:8080/eprocesso/consultarProcesso.jsf] salvo em [/home/01069360503/workspace/eprocesso/e-Processo-346689-01069360503/e-Processo-Comum-Testes/01-Sistema/06-Teste/eProcessoIntranetJavaBdd/target/jbehave/view/screenshots/failed-scenario-f1e5fa2c-c971-471c-99a8-442b0efb6cfe.png] com [103.294] bytes
Então será exibido no "CPF Responsável Atual" o valor "051.369.465-04" (NOT PERFORMED)
Então não será exibido "CPF com Dígito Verificador inválido." (NOT PERFORMED)


Failed to run story stories/consultar processos/preencher_criterios.storyConverted
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy15.sendKeysWithTries(Unknown Source)
	at br.gov.frameworkdemoiselle.behave.parser.jbehave.CommonSteps.inform(CommonSteps.java:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:595)
	at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:535)
	at org.jbehave.core.embedder.StoryRunner.runStepsWhileKeepingState(StoryRunner.java:515)
	at org.jbehave.core.embedder.StoryRunner.runScenarioSteps(StoryRunner.java:479)
	at org.jbehave.core.embedder.StoryRunner.runStepsWithLifecycle(StoryRunner.java:445)
	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:305)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:220)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:181)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:262)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at br.gov.frameworkdemoiselle.behave.internal.ui.UIProxy.invoke(UIProxy.java:35)
	... 21 more
Caused by: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Limpeza de campo não concluída com sucesso
	at br.gov.frameworkdemoiselle.behave.runner.webdriver.ui.WebTextField.sendKeysWithTries(WebTextField.java:88)
	... 26 more
```

**Comment by rogernobre** [comment]
No meu caso, também existe um script na validação de preenchimento do campo. E os caracteres especiais não são preenchidos, por isso não funciona o passo comum. Vou ver aqui se faço um pull request demonstrando a seguinte situação.

**Comment by rogernobre** [comment]
@gugaemc, é esse seu caso também?

Quando você usa os seguintes passos:
```
Quando informo "valor com mascara" no campo "nome do campo"
Quando informo "valor sem mascara" no campo "nome do campo"
```

A sua aplicação formata o valor do campo antes do passo limpar o campo?

**Comment by gugaemc** [comment]
@rogernobre, quando informo sem máscara, ele simplesmente não preenche o valor.
Quando informo com máscara, ele preenche (nas versões anteriores à 1.4.1). O problema está a partir desta versão, em que ele não está mais preenchendo nem com máscara.

Fiz uns testes hoje de manhã com a versão 1.4.1 e percebi que às vezes ele preenche o campo corretamente sim, em uma de cada três tentativas. Não consegui fazer mais testes porque tive problemas com minha máquina no trabalho.

**Comment by juliancesar** [comment]
@rogernobre, será que essa questão de validar depois de perder o foco não poderia ser implementada para todos os casos?

**Comment by rogernobre** [comment]
@juliancesar, não. Tem casos em que o valor do campo será apagado ou formatado, assim, o valor de entrada não permanece igual ao valor do campo após preenchimento. A depender da implementação do componente, esse evento pode ser na medida em que se digita uma sequência de valores (sem perder o focus) ou só quando se perde o focus.

**Comment by rogernobre** [comment]
Para o sendKeysWithTries funcionar, teria de passar três valores: valor de entrada, valor da validação da entrada antes de perde o focus, valor de validação após perde o focus.

**Comment by rogernobre** [comment]
@juliancesar, agora entendi. Pode sim.

**Comment by rogernobre** [comment]
@juliancesar, desnecessário a validação antes da perda de focus.

**Comment by rogernobre** [comment]
@juliancesar, mas tem que existir um passo que não force o campo a perder o focus

**Comment by gugaemc** [comment]
Pessoal, da minha parte, o SO e os navegadores da minha máquina foram atualizados e não notei mais o problema original.

**Comment by juliancesar** [comment]
@gugaemc, qual versão do dbehave vc está utilizando?

**Comment by gugaemc** [comment]
@juliancesar estou usando a 1.4.1.

**Comment by juliancesar** [comment]
@gugaemc, faça o favor de testar com a nossa última versão que é a **1.4.3-SNAPSHOT**, pois assim teremos mais segurança que estamos no caminho certo.

Aguardo o seu retorno.

**Comment by gugaemc** [comment]
@juliancesar testei com o 1.4.3-SNAPSHOT e está funcionando muito bem.
Usei este link pra testar: http://www.primefaces.org/showcase/ui/input/inputMask.xhtml
Aqui no meu sistema também está funcionando ok.

**Comment by botelhojp** [comment]
Então deve funcionar na 1.4.2.

**Comment by ThiagoNicolielo** [comment]
Não sei porque, mas no meu projeto não funciona mais isso em um campo de CPF.
Em um funciona, em outro campo de CPF, em outro trecho da história, não funciona.
Funcionava até a 1.4.1. A partir da 1.4.2-SNAPSHOT, 1.4.2 e também na 1.4.3-SNAPSHOT, parou de funcionar.
Ele preenche o campo e ao perder o foco o valor some do campo, fica vazio.

Aparentemente os campos não têm diferenças significativas (mas pode ter algo mais? não sei porque agora funciona em um e no outro não.

Campo de CPF que funciona ainda:
<input type="text" class="ui-inputfield ui-inputmask ui-widget ui-state-default ui-corner-all" onkeypress="confirmClick(event)" size="18" maxlength="14" value="" name="cpf" id="cpf" role="textbox" aria-disabled="false" aria-readonly="false" aria-multiline="false">

Campo de CPF em que não funciona mais:
<input type="text" class="ui-inputfield ui-inputmask ui-widget ui-state-default ui-corner-all" size="18" name="conteudo:j_id409440119_62a49ac3:tabQSa:cpfCnpjSocio" id="conteudo:j_id409440119_62a49ac3:tabQSa:cpfCnpjSocio" role="textbox" aria-disabled="false" aria-readonly="false" aria-multiline="false">

**Comment by juliancesar** [comment]
@ThiagoNicolielo, esta questão esta encerrada?

**Comment by ThiagoNicolielo** [comment]
Bom, na verdade não consegui resolver, mas o projeto foi suspenso e inclusive passei a trabalhar em outro projeto no dia seguinte, então a orientação é que o que estiver pendente no projeto fique paralizado mesmo e se um dia a empresa decidir retomar o projeto, estará tudo aguardando, inclusive os defeitos encontrados.

Talvez o problema seja específico do projeto. O campo que dava erro varia de CPF para CNPJ dependendo da opção selecionada em um radio (PF/PF?).

Então, acredito que possa ser encerrada a issue.
Obrigado.
