### ISSUE TITLE
Versão 1.4.1, rodando com maven, não reconhece caracter especial

### ISSUE THREAD

**Issue by rogereis** [demoiselle/behave#310]
Ao alterar a versão do DBehave de 1.4.0 para 1.4.1, ao executar os testes através do Maven, os caracteres especiais não são reconhecidos.

Running story stories\Denuncia\FCD\manterDenuncia_P.storyConverted
Funcionalidade: Den?ncia-FCD-ManterDenuncia_P
(stories\Denuncia\FCD\manterDenuncia_P.storyConverted)
Scenario: Funcionalidade: Den?ncia-FCD-ManterDenuncia_P
Narrativa:
Para Criar uma Den?ncia
Como um usu?rio
Desejo criar uma Den?ncia e salv?-la 
Cen?rio: Criar uma Den?ncia
Dado que informo "CPF do T?cnico" com valor "56596081591"

Ent?o estou na tela "Tela de Login" (FAILED)
(br.gov.frameworkdemoiselle.behave.exception.BehaveException: Elemento [Link Acesso"
Ent?o estou na tela "Tela de Login] não encontrado na tela [Tela Inicial])

Ao retornar a versão 1.4.0 volta a funcionar.

Estou usando Windows 7 64bits virtualizado com VMWare.

**Comment by botelhojp** [comment]
Seus arquivos de história estão em qual codificação? UTF-8, ISO, ...
Verifique na pasta source e também no target. O maven durante a fase de process resource irá modificar os aquivos. Se o enconding não informado corretamente os arquivos ficam como você postou.

**Comment by rogereis** [comment]
Como descobrir a codificação de um arquivo? E como saber que codificação o maven espera?

**Comment by mestihudson** [comment]
Linux [http://stackoverflow.com/questions/805418/how-to-find-encoding-of-a-file-in-unix-via-scripts]
Windows [http://stackoverflow.com/questions/3710374/get-encoding-of-a-file-in-windows]

**Comment by rogereis** [comment]
Utilizando a dica para windows, tanto o arquivo do source quanto o arquivo do target estão em UTF-8

**Comment by botelhojp** [comment]
Me diz o que acontece se ajustar seu pom.xml assim:
```xml
<project>
  ...
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <version>2.7</version>
        <configuration>
          ...
          <encoding>UTF-8</encoding>
          ...
        </configuration>
      </plugin>
    </plugins>
    ...
  </build>
  ...
</project>
```

**Comment by rogernobre** [comment]
@rogereis, não seria um problema do Check-out do RTC?

No meu caso aqui, se eu rodo via maven na minha máquina fica ok.

Se eu rodo via um slave do jenkins que está no windows não fica ok.

Olhei os arquivos no notepad++ e ele informa que os arquivos estão com codificação UTF-8 sem BOM.

**Comment by botelhojp** [comment]
Se rodar pelo mavem na máquina windows (sem o jenkins) como fica?

**Comment by rogereis** [comment]
A configuração do POM não resolveu o problema. Sem o jenkins dá o mesmo problema seja pelo eclipse seja por linha de comando, tentei até o "mvn clean compile test". 

@rogernobre, o código que está na sua máquina é utilizando o ALM ou você criou um projeto "desconectado"?

**Comment by rogernobre** [comment]
@rogereis e @botelhojp, 

Minha configuração do POM:
```
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.6</source>
					<target>1.6</target>
					<encoding>${project.build.sourceEncoding}</encoding>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.18.1</version>
				<configuration>
					<argLine>-Dfile.encoding=UTF-8</argLine>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<configuration>
					<encoding>UTF-8</encoding>
				</configuration>
			</plugin>
		</plugins>
	</build>
```
No Ubuntu, tudo blz.

No Windows tanto no eclipse via maven, tanto na slave do jenkins, a codificação se perde:
```
11:51:27,336 DEBUG (main) [BehaveConfig]: -------------------------------
11:51:27,680 INFO  (main) [JBehaveParser]: Configurando Parser JBehave...
11:51:27,743 INFO  (main) [JBehaveParser]: Iniciando Parser JBehave...
11:51:27,743 INFO  (main) [JBehaveParser]: Executando histÃ³ria: [[stories\acessar_consultar_processo_local.storyConverted, stories\consultar processos\palavra_chave.storyConverted]]
Processing system properties {}
Using controls EmbedderControls[batch=false,skip=false,generateViewAfterStories=true,ignoreFailureInStories=true,ignoreFailureInView=true,verboseFailures=true,verboseFiltering=false,storyTimeoutInSecs=1296000,failOnStoryTimeout=false,threads=1]

(BeforeStories)
11:51:27,915 INFO  (main) [BeforeAfterSteps]: 


11:51:27,915 INFO  (main) [BeforeAfterSteps]: >>Iniciando AplicaÃ§Ã£o<<
11:51:32,901 DEBUG (main) [WebDriverRunner]: Driver [Remote Web Driver] iniciado

Running story stories\acessar_consultar_processo_local.storyConverted

(stories\acessar_consultar_processo_local.storyConverted)
Scenario: Realizar login local no e-Processo Java
11:51:33,230 DEBUG (pool-1-thread-1) [CommonSteps]: Inicio do goToWithName Login Local Java
11:51:33,355 DEBUG (pool-1-thread-1) [WebDriverRunner]: Tentar acessar [http://10.32.113.14:8080/eprocesso/index.jsf]
11:51:35,261 DEBUG (pool-1-thread-1) [CommonSteps]: Final do goToWithName Login Local Java
Dado que vou para a tela "Login Local Java"
Quando informo "cpf.padrao" no campo "Username"
Quando clico em "Login"
11:51:41,552 DEBUG (pool-1-thread-1) [CommonSteps]: Inicio do pageWithName Principal Java
11:51:41,897 DEBUG (pool-1-thread-1) [CommonSteps]: Final do pageWithName Principal Java
EntÃ£o estou na tela "Principal Java"


Running story stories\consultar processos\palavra_chave.storyConverted
Funcionalidade: Consultar Processos (palavra-chave)
(stories\consultar processos\palavra_chave.storyConverted)
Meta:
@pastaDatasets consultar processos

Scenario: Incluir palavra chave
Meta:
@cenario 01

11:51:42,288 DEBUG (pool-1-thread-1) [SimpleAssert]: assertNotNullNorEmpty(propertyName=connectionUrl, property=jdbc:oracle:thin:@10.50.240.70:1521:doc21a) - start
11:51:46,694 DEBUG (pool-1-thread-1) [SimpleAssert]: assertNotNullNorEmpty(propertyName=connectionUrl, property=jdbc:oracle:thin:@10.50.240.70:1521:doc21a) - start
Dado que nÃ£o existam critÃ©rios favoritos e Ã© a primeira vez que o usuÃ¡rio acessa a tela
11:51:50,226 DEBUG (pool-1-thread-1) [CommonSteps]: Inicio do goToWithName Consultar Processo Java
11:51:50,243 DEBUG (pool-1-thread-1) [WebDriverRunner]: Tentar acessar [http://10.32.113.14:8080/eprocesso/consultarProcesso.jsf]
11:51:56,512 DEBUG (pool-1-thread-1) [CommonSteps]: Final do goToWithName Consultar Processo Java
```

@rogereis, no Windows agora copiei o projeto do Ubuntu e rodei desconectado, por que minha versão do plugin não é compatível com a nova versão do ALM, mas mesmo assim continua a mesma coisa, isto é, historias com codificação UTF-8 sem BOM, e a formatação se perde.

**Comment by rogernobre** [comment]
@botelhojp, não seria configuração do log4j?

Mudei no Windows a codificação das historias para UTF-8.

As historias convertidas ficaram UTF-8 (antes estava UTF-8 sem BOM), mas o console ainda exibe como ISO.

**Comment by rogereis** [comment]
@rogernobre Mas no seu caso as histórias executam com sucesso? Pois na minha máquina dá erro e não executam? Outro ponto é: o que mudou na versão 1.4.1 para acontecer esse erro que não acontece com o 1.4.0?

**Comment by botelhojp** [comment]
@rogereis, você poderia fazer um teste rodando o projeto mix (https://github.com/demoiselle/behave/tree/master/sample/mix) na sua VM para a versões 1.4.0 e 1.4.1?

**Comment by rogereis** [comment]
@botelhojp, para a versão 1.4.1 ocorreu o mesmo problema, para a versão 1.4.0, tinha problemas de compilação pois usa classes que não estão nesta versão, mas a princípio, pelos erros no log, que o erro não era por causa dos caracteres.

**Comment by botelhojp** [comment]
Blz, vou investigar a questão e retorno com novidades.

**Comment by ahvsoares** [comment]
Também estamos tendo o mesmo problema. Vários projetos pararam de rodar após atualização da versão.

Inclusive na versão 1.4.2-SNAPSHOT que é a que estou usando em um projeto, pois há uma correção que eu preciso que está feita nessa versão.

Alguma novidade?

**Comment by mestihudson** [comment]
Senhores, ontem, ajudando a montar o ambiente de desenvolvimento de uma colega, em uma máquina windows xp passamos por problema similar. Resolvi mudando a versão de 1.4.1 para 1.4.0.

**Comment by botelhojp** [comment]
Vou trabalhar nisso agora a tarde, montei o laboratório com Windows 7 e pretendo reproduzir e analisar o problema, espero retornar ainda hoje alguma novidade, os que puderem voltar para 1.4.0 façam.

**Comment by botelhojp** [comment]
Pessoal, eu rodei o projeto mix, que possui várias frases com acentuação, no Windows 7, chamando o teste pelo maven (mvn clean  test). Na console a acentuação vem quebrada, mas o teste roda sem problema. É isso que acontece com vocês? Se não, não conseguir reproduzir o problema.

**Comment by rogereis** [comment]
Não, ele abre o browser e fecha pois ele ta procurando um comando que não
existe, principalmente quando o cenário tem o comando "Então"

Em sex, 27 de fev de 2015 às 15:57, Vanderson Botelho <
notifications@github.com> escreveu:

**Comment by botelhojp** [comment]
De fato vcs não estão loucos, rs. 
Reproduzi o problema. Quando rodo no eclipse funciona, mas na linha de comando não. Provavelmente é algo relacionado ao maven, se for isso é possível substituir as propriedades do pom.xml enquanto não geramos uma nova versão, mas ainda preciso saber o que aconteceu.

**Comment by botelhojp** [comment]
Seguinte pessoal. Voltei a versão do jbehave para 3.8 e tudo funcionou. Peço que façam o mesmo informando no pom.xml do seu projeto da seguinte forma:
```xml
	<dependency>
		<groupId>org.jbehave</groupId>
		<artifactId>jbehave-core</artifactId>
		<version>3.8</version>
	</dependency>
	<dependency>
		<groupId>org.jbehave.web</groupId>
		<artifactId>jbehave-web-selenium</artifactId>
		<version>3.5.5</version>
	</dependency>
```
Se isso funcionar geraremos uma versão 1.4.3 com a downgrade do jbehave e investigaremos o que pode ter acontecido com a nova versão do jbehave.
Aguardo retorno!

**Comment by ahvsoares** [comment]
@botelhojp , com a versão 1.4.2-SNAPSHOT está funcionando agora.

**Comment by botelhojp** [comment]
Maravilha!
Vi que outros estão passando pelo mesmo problema com o jbehave: http://stackoverflow.com/questions/10429163/maven-jbehave-encoding-stories-utf8

**Comment by rogereis** [comment]
Confirmo a informação passada por @ahvsoares. Só que fica a pergunta, uso essa versão snapshot ou faço downgrade para versão 1.4.0 enquanto a 1.4.2 não é lançada?

**Comment by botelhojp** [comment]
Recomendo que use dbehave 1.4.1 com o downgrade do no jbehave para 3.8, conforme orientação anterior. Pretendo lançar até a manhã a versão 1.4.2, estou fazendo os últimos ajustes.

**Comment by rogereis** [comment]
ok.

**Comment by botelhojp** [comment]
Versão 1.4.2 lançada!
