### ISSUE TITLE
Erro na verificação de textos que originalmente contém aspas, na tela.

### ISSUE THREAD

**Issue by ThiagoNicolielo** [demoiselle/behave#311]
Pessoal,

Gostaria de verificar a exibição de um texto que contém partes com aspas.

Se uso a frase seguinte:
Então será exibido "Caso não seja criada pelo menos uma filial como \"unidade produtiva\""

na execução (Debug), verifiquei que o parâmetro text contém o seguinte valor:
text= "Caso não seja criada pelo menos uma filial como \\"unidade produtiva\\"

Ou seja, está procurando a frase não entendendo a contra-barra como caracter de escape, como se fosse ser exibido a frase abaixo:
Caso não seja criada pelo menos uma filial como \"unidade produtiva\"
Porém, o que quero verificar na tela é a frase: Caso não seja criada pelo menos uma filial como "unidade produtiva"

Desejo não precisar quebrar a frase em vários Então's, como fiz por ora:
Então será exibido "Caso não seja criada pelo menos uma filial como "
Então será exibido "unidade produtiva"
Então será exibido " em até 180 dias, o CNPJ da empresa será "
Então será exibido "Suspenso"
Utilizo tudo isso apenas para verificar a seguinte frase:
Caso não seja criada pelo menos uma filial como "unidade produtiva" em até 180 dias, o CNPJ da empresa será "Suspenso"

Aparentemente, pelo que entendi, a issue #159 não me ajudou neste problema.

**Comment by rogernobre** [comment]
@ThiagoNicolielo, eu uso assim:
```
Cenário: Consultar Processos com critério Opcional em branco
Dado que estou na tela "Consultar Processo Java"
Então será exibido "Selecione uma palavra-chave na lista abaixo."
Quando informo "Assuntos/Objetos" no campo "Selecionar palavra-chave"
Então será exibido na tabela "Filtro de pesquisa" os valores: 
|Palavra-Chave|
|starCinza.png.jsf Assuntos/Objetos|
Quando clico em "Buscar"
Então será exibido "Para realizar a pesquisa, é necessário selecionar e informar pelo menos um critério essencial (em negrito) e com operador "="."
```

**Comment by ThiagoNicolielo** [comment]
@rogernobre 
Não entendi, não vi referência à aspas dentro de algum valor a ser verificado, nesse trecho que postou. É isso mesmo?

**Comment by rogernobre** [comment]
Então será exibido "Para realizar a pesquisa, é necessário selecionar e informar pelo menos um critério essencial (em negrito) e com operador "="."

**Comment by ThiagoNicolielo** [comment]
Ah, ok, não tinha entendido.
Humm, acho que o que ocorreu foi eu achar que usar aspas sendo o delimitador também aspas, iria dar problemas.

Deu certo, ficou assim:
Então será exibido "Caso não seja criada pelo menos uma filial como "unidade produtiva" em até 180 dias, o CNPJ da empresa será "Suspenso""

Obrigado, Roger!
