### ISSUE TITLE
Qual a melhor forma de memorizar valores?

### ISSUE THREAD

**Issue by gugaemc** [demoiselle/behave#313]
Tenho me deparado com situações em que tenho que guardar um valor pra usá-lo posteriormente no mesmo teste, Muitas vezes porque os valores de outro campo dependem do primeiro.

A forma como tenho tratado isso é criar um passo, por exemplo:
`memorizo valor de Município aleatório`
E neste passo, guardo o valor numa variável de instância da classe de passos. Passos que usam os valores memorizados simplesmente lêem essas variáveis.

Um problema que vejo nessa abordagem é quando o valor tem que ser usado em duas telas diferentes (pelo menos aqui no projeto, usamos uma classe de Steps pra cada tela). Um exemplo disso é quando memorizamos os valores de uma pesquisa para conferir os detalhes de um registro em outra tela.

Existe solução melhor? Como vocês lidam com isso?

**Comment by botelhojp** [comment]
O DataProvider seria uma opção:
http://pt.slideshare.net/vandersonsilva9615/02-treinamentodbehaveweb (slide 39)

**Comment by juliancesar** [comment]
@gugaemc, no dbehave existem 3 frases para isso:


Para pegar um valor de um campo:
```gherkin
Dado que obtenho "$var" do campo "$fieldName"
```

Para armazenar um valor:
```gherkin
Dado que informo "$key" com valor \"$value\"
```

E por fim, para usar basta colocar o nome do $var ou $key ao usar uma frase:
```gherkin
Então informo "$var OU $key" no campo "$fieldName"
```

Tendo alguma dúvida ou problema pode reabrir a issue.
