### ISSUE TITLE
Não funciona usar a parametrização do cenário na parametrização do mapeamento

### ISSUE THREAD

**Issue by rogereis** [demoiselle/behave#318]
Não estou conseguindo com as configurações abaixo, o erro acontece pois o locator montado está incluindo as aspas duplas.

Meu cenário parametrizado
```gherkin
Cenário: Abrir o documento "{Pedido}" cujo Nome do Caso é "{NomeCaso}" na situação "{NomeSituacao}" da unidade "{SiglaUnidade}"
....
Então clico em "Documento" referente a ""{Pedido}","{NomeCaso}","{NomeSituacao}""
```

Mapeamento parametrizado

```java
@ElementMap(name = "Documento", locatorType = ElementLocatorType.XPath, locator = "//a[contains(text(),'%param2%')]/../../following-sibling::tr//a[contains(text(),'%param1%']/../../descendant::a[contains(text(),'%param3%']")
```

Como o selenium está procurando

```
//a[contains(text(),'"CriarManterPI-03"')]/../../following-sibling::tr//a[contains(text(),'"OBS"']/../../descendant::a[contains(text(),'"Rascunho"']'
```

Chamado no cenário de testes

Abrir o documento "PB s/n" cujo Nome do Caso é "CriarManterPI-03" na situação "A Avaliar" da unidade "Espei01"

Como o selenium deveria procurar

```
//a[contains(text(),'CriarManterPI-03')]/../../following-sibling::tr//a[contains(text(),'OBS']/../../descendant::a[contains(text(),'Rascunho']'
```

**Comment by juliancesar** [comment]
A frase não pode ser da seguinte maneira? 

```gherkin
Então clico em "Documento" referente a "{Pedido},{NomeCaso},{NomeSituacao}"
```

**Comment by rogereis** [comment]
Tentei fazer este teste mas o que o locator tenta achar é:  
 
//a[contains(text(),'{NomeCaso}')]/../../following-sibling::tr//a[contains(text(),'{Pedido}']/../../descendant::a[contains(text(),'{NomeSituacao}']'

**Comment by juliancesar** [comment]
então tenta coloca assim:

```gherkin
Então clico em "Documento" referente a "\"{Pedido}\",\"{NomeCaso}\",\"{NomeSituacao}\""
```

**Comment by rogereis** [comment]
Resultado do lacator com a sugestão:

//a[contains(text(),translate('"\{NomeCaso}\"','"',''))]/../../following-sibling::tr//a[contains(text(),translate('\"{Pedido}\"','"',''))]/../../descendant::a[contains(text(),translate('\"{NomeSituacao}\"','"',''))]

**Comment by juliancesar** [comment]
Uma issue parecida é a #159, vamos ter que depurar a sua situação para dar uma solução definitiva, peço que entre em contato por telefone comigo amanhã.
Obrigado.

**Comment by rogereis** [comment]
OK, qual o melhor horário?

**Comment by juliancesar** [comment]
No período da manhã, a partir das 9h·

**Comment by rogereis** [comment]
OK

**Comment by juliancesar** [comment]
A solução do colega @rogernobre foi aplicada e publicada na versão **1.4.3-SNAPSHOT** de hoje.
O problema foi resolvido.
