### ISSUE TITLE
Como rolar menu, até exibir item que se encontra oculto?

### ISSUE THREAD

**Issue by emanuelcastro** [demoiselle/behave#323]
Estou tentando rolar um menu lateral até que um determinado link seja exibido.
Alguém já passou por isso?

**Comment by juliancesar** [comment]
Posso estar enganado, mas ao clicar no item essa rolagem ocorre automaticamente, ou não!?

**Comment by emanuelcastro** [comment]
Explicar melhor: eu clico no menu lateral, este é aberto e clico no item "Administração Siconfi".
Todos os itens abaixo dele são mostrados. Só que eu preciso clicar em um item que está abaixo do último mostrado na imagem. Podem notar que o menu ficou com uma barra de rolagem?
Pelo que eu percebi, o behave não está encontrando o meu link na tela. Por isso queria rolar o menu, até encontrar a opção que preciso.

Não sei se deu pra entender.
:-(

![tela](https://cloud.githubusercontent.com/assets/2234171/7047053/78ebe0ac-dde0-11e4-810d-acd2cb7e2ca1.png)

**Comment by juliancesar** [comment]
Acho que entendi. Pelo que entendi vc precisa clicar em um link que não esta sendo mostrado na tela, e vc já tentou clicar nele mas não funciona e quer alguma maneira de rolar o scroll para fazer isso. A resposta rápida é que não temos algo pronto no dbehave para fazer isso, mas acredito que seja possível criar um passo personalizado para fazer essa ação, contudo antes tenha certeza que o mapeamento esta correto.

**Comment by emanuelcastro** [comment]
O mapeamento está correto pois se eu mover essa minha opção para cima até que fique visível ele é acessado.
Estou tentando criar esse passo para acessar esse link.
Até agora nada.
:-(

**Comment by juliancesar** [comment]
Ok, acho que o melhor caminho é tentar usar Javascript como no código abaixo:

```java
WebDriver driver = (WebDriver) runner.getDriver();
JavascriptExecutor js = (JavascriptExecutor)driver;
js.executeScript("chamada javascript que mode o scroll");
```

**Comment by emanuelcastro** [comment]
Com sua dica, consegui resolver dessa forma:

	@When("rolo a barra de rolagem")
	public void whenRoloABarraDeRolagem() {
		WebDriver driver = (WebDriver) runner.getDriver();
		JavascriptExecutor js = (JavascriptExecutor)driver;
		js.executeScript("$('#nav-menu-lateral').scrollTop($('#nav-menu-lateral').height())");
	}

**Comment by juliancesar** [comment]
Ótimo! Se tiver mais alguma dúvida com relação a este assunto pode reabrir a issue.
