### ISSUE TITLE
Arquivos excluídos do diretório resources

### ISSUE THREAD

**Issue by lsalles** [demoiselle/behave#326]
Amigos, bom dia.

Estou somente relatando uma dificuldade que eu tive. 
Ao criar um projeto do Behave um dos 3 archetype do demoiselle para o behave:

jbehave-gest-archetype
jbehave-junit-archetype
jbehave-selenium-archetype

Na pasta src/test/resources na configuração do build path, todas ficaram com um filtro "Excluded ** ", fazendo que o projeto não lesse os arquivos colocados neste diretório, com exceção dos .story.

Somente consegui ler os arquivos, os datasets que criei (ex: src/test/resources/datasets/primeiroDataset.xml), depois de deletar este filtro.

Até descobrir isso, demorou um pouco.

Grato.

**Comment by botelhojp** [comment]
Olá, tentei reproduzir o problema, mas não consegui. Posso não ter entendido.
O filtro "Excluded **" a que ser refere é do maven ou da IDE Eclipse?

**Comment by lsalles** [comment]
O filtro é na IDE  Eclipse. Tirei um printscreen. 
Criei o projeto novamente e o erro apareceu de novo. Só consegui consertar ao adicionar um filtro "datasets/*.xml". Senão ele não recolhece os arquivos na pasta "/home/usuariojava/workspaces/scdp2015_evolutiva/scdp-behave/src/test/resources/datasets/".

Grato 

![captura de tela de 2015-05-06 15 58 08](https://cloud.githubusercontent.com/assets/11540085/7501243/0d47d254-f409-11e4-8c9b-036a5cba3284.png)

**Comment by juliancesar** [comment]
@botelhojp , é possível alterar esta configuração da IDE via maven?

**Comment by botelhojp** [comment]
Pelo que entendi, o problema, se houver, seria no plugin m2 do eclipse, pois o Archetype do dbehave não criar os arquivos .project nem o .classpath, como qualquer archetype do maven.

Fiz um tests criando o um projeto maven vazio e com o dbehave e o eclipse interpreta da mesma forma, o “Included ALL” indicar que todos os arquivos serão aceitos, não entendi a necessidade de criar filtros específicos, por exemplo **/*.java. 

![captura de tela de 2015-05-11 18 06 53](https://cloud.githubusercontent.com/assets/1793654/7575208/75a4c042-f809-11e4-8572-eecfeda41a6f.png)

Até o momento não identifico ajustes necessários ao arquetype.

**Comment by lsalles** [comment]
Ao mesmo tempo que ele bota "Included ALL" ele bota "Excluded **" ou seja, exclui tudo.

Grato.

-- 
Lucas Salles

SUPDE/DESDR

SERPRO - Serviço Federal de Processamento de Dados

Tel.: (71) 2102-7918



Em 11/05/2015 18:15:35, Vanderson Botelho escreveu:
> Pelo que entendi, o problema, se houver, seria no plugin m2 do eclipse, pois o Archetype do dbehave não criar os arquivos .project nem o .classpath, como qualquer archetype do maven.> 

> Fiz um tests criando o um projeto maven vazio e com o dbehave e o eclipse interpreta da mesma forma, o “Included ALL” indicar que todos os arquivos serão aceitos, não entendi a necessidade de criar filtros específicos, por exemplo *> /> .java. > 

> 

> Até o momento não identifico ajustes necessários ao arquetype.> 

> —
> Reply to this email directly or > view it on GitHub> .> 
> 
  > 
    
> > 
  

> > 



-


"Esta mensagem do SERVIÇO FEDERAL DE PROCESSAMENTO DE DADOS (SERPRO), empresa pública federal regida pelo disposto na Lei Federal nº 5.615, é enviada exclusivamente a seu destinatário e pode conter informações confidenciais, protegidas por sigilo profissional. Sua utilização desautorizada é ilegal e sujeita o infrator às penas da lei. Se você a recebeu indevidamente, queira, por gentileza, reenviá-la ao emitente, esclarecendo o equívoco."

"This message from SERVIÇO FEDERAL DE PROCESSAMENTO DE DADOS (SERPRO) -- a government company established under Brazilian law (5.615/70) -- is directed exclusively to its addressee and may contain confidential data, protected under professional secrecy rules. Its unauthorized use is illegal and may subject the transgressor to the law's penalties. If you're not the addressee, please send it back, elucidating the failure."

**Comment by lsalles** [comment]
Ao mesmo tempo que ele bota "Included ALL" ele bota Excluded ** ou seja, exclui tudo.

Grato.

-- 
Lucas Salles

SUPDE/DESDR

SERPRO - Serviço Federal de Processamento de Dados

Tel.: (71) 2102-7918



Em 11/05/2015 18:15:35, Vanderson Botelho escreveu:
> Pelo que entendi, o problema, se houver, seria no plugin m2 do eclipse, pois o Archetype do dbehave não criar os arquivos .project nem o .classpath, como qualquer archetype do maven.> 

> Fiz um tests criando o um projeto maven vazio e com o dbehave e o eclipse interpreta da mesma forma, o “Included ALL” indicar que todos os arquivos serão aceitos, não entendi a necessidade de criar filtros específicos, por exemplo *> /> .java. > 

> 

> Até o momento não identifico ajustes necessários ao arquetype.> 

> —
> Reply to this email directly or > view it on GitHub> .> 
> 
  > 
    
> > 
  

> > 



-


"Esta mensagem do SERVIÇO FEDERAL DE PROCESSAMENTO DE DADOS (SERPRO), empresa pública federal regida pelo disposto na Lei Federal nº 5.615, é enviada exclusivamente a seu destinatário e pode conter informações confidenciais, protegidas por sigilo profissional. Sua utilização desautorizada é ilegal e sujeita o infrator às penas da lei. Se você a recebeu indevidamente, queira, por gentileza, reenviá-la ao emitente, esclarecendo o equívoco."

"This message from SERVIÇO FEDERAL DE PROCESSAMENTO DE DADOS (SERPRO) -- a government company established under Brazilian law (5.615/70) -- is directed exclusively to its addressee and may contain confidential data, protected under professional secrecy rules. Its unauthorized use is illegal and may subject the transgressor to the law's penalties. If you're not the addressee, please send it back, elucidating the failure."

**Comment by lsalles** [comment]
Ao mesmo tempo que ele bota "Included ALL" ele bota "Excluded **" ou seja, exclui tudo.

Grato.


-- 
Lucas Salles

SUPDE/DESDR

SERPRO - Serviço Federal de Processamento de Dados

Tel.: (71) 2102-7918



Em 11/05/2015 18:15:35, Vanderson Botelho escreveu:
> Pelo que entendi, o problema, se houver, seria no plugin m2 do eclipse, pois o Archetype do dbehave não criar os arquivos .project nem o .classpath, como qualquer archetype do maven.> 

> Fiz um tests criando o um projeto maven vazio e com o dbehave e o eclipse interpreta da mesma forma, o “Included ALL” indicar que todos os arquivos serão aceitos, não entendi a necessidade de criar filtros específicos, por exemplo *> /> .java. > 

> 

> Até o momento não identifico ajustes necessários ao arquetype.> 

> —
> Reply to this email directly or > view it on GitHub> .> 
> 
  > 
    
> > 
  

> > 



-


"Esta mensagem do SERVIÇO FEDERAL DE PROCESSAMENTO DE DADOS (SERPRO), empresa pública federal regida pelo disposto na Lei Federal nº 5.615, é enviada exclusivamente a seu destinatário e pode conter informações confidenciais, protegidas por sigilo profissional. Sua utilização desautorizada é ilegal e sujeita o infrator às penas da lei. Se você a recebeu indevidamente, queira, por gentileza, reenviá-la ao emitente, esclarecendo o equívoco."

"This message from SERVIÇO FEDERAL DE PROCESSAMENTO DE DADOS (SERPRO) -- a government company established under Brazilian law (5.615/70) -- is directed exclusively to its addressee and may contain confidential data, protected under professional secrecy rules. Its unauthorized use is illegal and may subject the transgressor to the law's penalties. If you're not the addressee, please send it back, elucidating the failure."

**Comment by juliancesar** [comment]
@lsalles, você ainda tem problemas com esta questão?

**Comment by juliancesar** [comment]
@lsalles, vou fechar esta issue, se a questão ainda existir, favor reabrir.
