### ISSUE TITLE
"Instabilidade" no autocomplete

### ISSUE THREAD

**Issue by emanuelcastro** [demoiselle/behave#327]
Pessoal,
estou testando o componente de autocomplete do primefaces e tenho notado uma certa instabilidade em sua execução. 
Em alguns momentos ele funciona corretamente e em outros não.
Por exemplo, tenho um autocomplete na tela que foi mapeado dessa forma:

```
@ElementMap(name = "Campo Ente", locatorType = ElementLocatorType.XPath, locator = {"//*[@id='formColeta:enteSelect_input']", "//*[@id='formColeta:enteSelect_panel']"})
	private AutoComplete campoEnte;
```
E na pus o passo na story:
```
Quando informo "Caucaia" e seleciono "Caucaia/CE" no campo "Campo Ente"
```
Algumas vezes ele preenche com a string **Caucaia** corretamente e o teste segue.
Outras ele põe todo o texto **Caucaia" e seleciono "Caucaia/CE"**, daí o teste falha.

Alguem já passou por isso?
Alguma dica?

Obrigado.

**Comment by juliancesar** [comment]
@emanuelcastro, acredito que essa questão já foi resolvida no commit https://github.com/demoiselle/behave/commit/27c4cea37af4b563e5ae33591b62bf74c4ed5cd9 e já está disponível na versão **1.4.3-SNAPSHOT**, pretendemos lançar a verão final 1.4.3 até o final da semana que vem.

**Comment by emanuelcastro** [comment]
Opa @juliancesar,

vou testar nessa versão nova.
Obrigado pela ajuda.

**Comment by juliancesar** [comment]
Caso o problema volte a ocorrer favor reabrir a issue.
