### ISSUE TITLE
Demoiselle Mobile - Android

### ISSUE THREAD

**Issue by rogerritter** [demoiselle/behave#328]
Olá Pessoal,

Temos algo Demoiselle para mobile, especificamente validação BDD na plataforma Android?

Abs.

**Comment by juliancesar** [comment]
Olá @rogerritter, ainda não temos este *Runner* (parte do fraemwork que é responsável pela interação com o sistema) no dbehave, contudo o dbehave permite que seja criado um novo. Hoje possuímos 2 *Runners*, uma para sistemas Web (Selenium/WebDriver) e outro para Desktop (FEST). 
Caso tenha interesse em desenvolver um podemos amadurecer a ideia juntos.

**Comment by rogerritter** [comment]
Oi @juliancesar me parece interessante. Por favor entre em contato comigo através do e-mail roger.ritter@ufrgs.br para conversarmos mais sobre isto.

**Comment by juliancesar** [comment]
Acredito que o melhor local para conversarmos sobre este assunto é por aqui mesmo, pois assim todos tem acesso as informações e podem contribuir. Tendo alguma dúvida pode criar uma nova issue.
