### ISSUE TITLE
Testes com Certificado Digital

### ISSUE THREAD

**Issue by albertoivo** [demoiselle/behave#330]
Bom tarde,

Estou fazendo um teste com o Certificado Digital usando a api do sikuli e estou com a seguinte dúvida:
Ao entrar na tela de login, já é necessário a senha do token porém não passa do passo <code>Então vou para a tela "Tela de Login"</code> daí o DBehave não consegue seguir em frente para clicar no botão OK, conforme story abaixo:
<pre>
Cenário: Acesso ao sistema
Então vou para a tela "Tela de Login"
Quando clico no botão ok
</pre>
Na console fica assim:
<pre>
...
Scenario: Acesso ao sistema
</pre>
E não vai nem para o primeiro passo.

**Comment by juliancesar** [comment]
@rogernobre, você poderia nos ajudar nesta questão?

**Comment by rogernobre** [comment]
@juliancesar, como o "vou para a tela" usa o get do webdriver, o selenium trava até a página carregue, mas o modal aparece e deve ser fechado para que a página carregue. Ai está o problema.

**Comment by rogernobre** [comment]
Uma solução de contorno seria criar uma página anterior com um link para a tela e no clique do link não usar o click padrão do selenium e usar o Actions do selenium para simular o clique, ai não vai esperar o page load e ai ele poderá usar os cliques usando sikuli.

**Comment by rogernobre** [comment]
Procurei uma maneira de ignorar o erro do modal no get que selenium faz para carregar uma url, mas não tive sucesso.

**Comment by juliancesar** [comment]
@albertoivo, você conseguiu evoluir na questão?

**Comment by juliancesar** [comment]
Questão fechada por falta de retorno.

**Comment by ThiagoNicolielo** [comment]
Pessoal, também notei este problema, pois a aplicação que estou testando justamente solicita o certificado digital antes mesmo de terminar de carregar a página.

Caso fosse como a aplicação Expresso do Serpro, que só solicita o certificado após o usuário clicar no botão de logar usando este certificado, não haveria problema, mas como já pede antes mesmo de carregar a página, e só solicitar caso seja tentado acessar a página, imagino que a única forma seria alterar o comportamento dos métodos get() ou navigateTo() do selenium para que houvesse um timeout para este processo, ou algo assim.

Vou tentar esta solução de contorno que o @rogernobre propôs. Infelizmente não é tão prático, precisarei ficar mantendo uma página só para isso, mas paciência.

Posto aqui o resultado, se eu conseguir.

**Comment by ThiagoNicolielo** [comment]
Quase consegui, mas dispara um erro org.openqa.selenium.TimeoutException

Não consegui tratar com um try catch, acho que a thread acaba e o programa segue, parece que no momento que a execução passa pelo catch TimeoutException, o erro ainda nem se manifestou, e só depois, mas aí tarde demais.

Acho que precisaria de alguma forma tirar o controle do selenium ou algo assim, ele fica aguardando eventos que não ocorrem e assim o controle não consegue ser passado totalmente ao sikuli. (Pelo menos é o que me pareceu)

Talvez uma solução fosse manter uma Thread executando o sikuli separadamente, sem esta thread ser controlada pelo DBehave, será?
