### ISSUE TITLE
Checkbox e Radio: Verificar se o campo está marcado ou desmarcado no Primefaces

### ISSUE THREAD

**Issue by arildojg** [demoiselle/behave#331]
O primefaces gera uma estrutura de divs que "encapsulam" o input type="check" e o input type="radio" dentro de Divs. Ao mapear o elemento é necessário mapear a Div para que o click funcione e não gere a exceção abaixo:

> Caused by: org.openqa.selenium.WebDriverException: unknown error: Element is not clickable at point (258, 349). Other element would receive the click: 
> `<div class="ui-radiobutton-box ui-widget ui-corner-all ui-radiobutton-relative ui-state-default">...</div>`
>  (Session info: chrome=34.0.1847.137)
>  (Driver info: chromedriver=2.10.267517,platform=Linux 3.2.0-58-generic-pae x86) (WARNING: The server did not provide any stacktrace information)
>   (...)

Na versão 1.4.3, as classes Check e Radio estão recebendo métodos para verificar se o campo  está selecionado. Porém ainda não funcionam no primefaces.
Eles precisariam ser adaptados para tratar essa estrutura de divs que o primefaces gera, pois a principio foram criados para os casos onde o elemento mapeado é realmente o elemento check ou radio.

**Comment by arildojg** [comment]
Exemplo: html de campo radio exibido ao usar o firebug para auxiliar na extração de identificadores (gerado usando primefaces):
![exemplocamporadioprimefaces](https://cloud.githubusercontent.com/assets/4246255/7378087/4fbfc108-edc1-11e4-9d86-a2c73fe2b929.jpg)

**Comment by arildojg** [comment]
Colega @jorgesartori sugeriu usar 2 locator's: um para a div e um para o elemento em questão (check ou radio).

**Comment by rogernobre** [comment]
Seria um componente especifico para o primefaces para cada situação? Ou no próprio componente genérico, teria essa modificação?

**Comment by arildojg** [comment]
Fazer no componente genérico depende de um padrão no HTML.
Não sei se os Check's e Radio's do Primefaces seguem um padrão estrutural no HTML. Nos casos que vi até agora, a estrutura que postei acima, de 1 div contendo outra duas dentro sendo que uma delas abriga o check/radio, **parece** se repetir. Mas não sei se este padrão **sempre** se repete, para que possa ser tomado como base para alterar o componente genérico.

**Comment by rogernobre** [comment]
Falei isso por que se você for olhar o WebSelect (https://github.com/demoiselle/behave/blob/master/impl/runner/webdriver/src/main/java/br/gov/frameworkdemoiselle/behave/runner/webdriver/ui/WebSelect.java) desde a primeira versão já tem um comportamento para o padrão html e padrão "faces".

**Comment by rogernobre** [comment]
Queria até fazer um refatoração para separação de padrão html e "faces", mas quebraria muitos testes já implementados.

**Comment by arildojg** [comment]
A refatoração sugerida pelo @rogernobre seria ótima, pois facilitaria tratar futuras questões similares a esta,  que envolvam tratar diferenças de implementação conforme a tecnologia de interface utilizada. Porém precisa ser feita com cautela. Sugestão: 

   1. Tratar essa issue sem mudar a arquitetura, para resolvê-la e não quebrar outros testes (usando a sugestão dos 2 ids ou outra forma que julguem melhor);
   2. Criar uma outra issue, para planejar e executar essa refatoração assim que possível e não deixar o assunto morrer.

O que acham?

**Comment by arildojg** [comment]
Fiz um commit com uma sugestão inicial para tratar o caso sem grandes refatorações, conforme mencionei no comentário anterior. Procurei reaproveitar código que um colega já havia produzido para tratar a situação em checkbox's de um sistema que usa RichFaces.

**Comment by juliancesar** [comment]
@rogernobre, valide para mim o Pull Request #351 que trata estas questões de Checkbox e Radiobutton. Aguardo os seus comentários.

**Comment by rogernobre** [comment]
@arildojg, faltou o exemplo.

Outra coisa, eu deixaria as tentativas até estourar o tempo máximo do timeout.

Não sei se este caso seria um problema.

**Comment by arildojg** [comment]
Estou numa maratona de reuniões iniciais de um novo projeto esta semana, o que pode dificultar um pouco a interação com vocês. Tentarei resolver o que está pendente para fechar essa issue nos intervalos.

**Comment by rogernobre** [comment]
@arildojg, por que não ficou separado para que o PrimeFacesRadioButton implementasse o Radio?

**Comment by arildojg** [comment]
Hoje, a interface Radio prevê apenas o metodo click(). Porém, no PrimeFacesSteps preciso usar o isSelected(). Por isso usei a interface CheckBox para poder chamar o isSelected().
Posso mudar na PrimeFacesRadioButton para ele implementar o Radio e deixar o isSelected() apenas como um método a mais na classe, mesmo sem a interface Radio exigir.  Mas na PrimeFacesSteps, se usar a Radio o fw não vai saber que na PrimeFacesRadioButton tem o método isSelected() e não vou conseguir chamá-lo.

Se tiverem alguma idéia para usar o isSelected do PrimeFacesRadioButton na PrimeFacesSteps, sem atrelar o codigo do step a implementação concreta da inteface, avisem. As sugestões serão bem vindas.

**Comment by rogernobre** [comment]
Fiz um pull request agora (https://github.com/demoiselle/behave/pull/353), com a mudança na interface do componente de Radio para também possuir o metodo para verificar se esta selecionado ou não.

Não achei exemplo, mas para mim o Radio e o Checkbox são coisas distintas, isto é, o Checkbox poderia ter um terceiro estado (indeterminado) e seria diferente do Radio que só possuiria dois estados.

**Comment by juliancesar** [comment]
Aceitei o PR #353 do @rogernobre, agora vou trabalhar em cima do PR #351, do @arildojg.

**Comment by arildojg** [comment]
Vi o PR #353 do @rogernobre: inserir o isSelect na interface padroniza e facilita a implementação das frases pra Radio e Check. Estou tentando finalizar um page, test e mapemento no projeto mix pra testar as frases propostas no #351

**Comment by rogernobre** [comment]
Valeu @arildojg.

**Comment by juliancesar** [comment]
Foi publicada uma nova versão **1.5.1-SNAPSHOT** com a modificação sugerida e com algumas alterações. Favor validar.

**Comment by juliancesar** [comment]
Está issue será fechada por ter sido implementada na versão **1.5.1-SNAPSHOT**.
Tendo algum problema relacionado a nova implementação, favor abrir utra issue.
