### ISSUE TITLE
Erro no projeto exemplo "treino-desktop" na versão 1.4.3

### ISSUE THREAD

**Issue by rogernobre** [demoiselle/behave#334]
Erro no projeto exemplo "treino-desktop" na versão 1.4.3:

Running story stories/obras/adicionar-alterar-remover-obras.storyConverted
Funcionalidade: Acesso ao Sistema
(stories/obras/adicionar-alterar-remover-obras.storyConverted)
Narrative:
In order to a tela inicial apareceça para mim
As a visitante
I want to acessar o sistema
Scenario: Adicionar Obras
Dado que vou para a tela "Tela de Login"
19:16:49,322 INFO  (pool-1-thread-1) [ScreenShootingMaker]: Screenshot [Autenticação] salvo em [/home/01069360503/workspace/dbehave/behave/sample/treino-desktop/target/jbehave/view/screenshots/failed-scenario-8a7327b8-c130-4e88-9a86-8b2345dd2d09.png] com [6.151] bytes
Então será exibido no "Rótulo Usuário" o valor "Usuário:" (FAILED)
(br.gov.frameworkdemoiselle.behave.exception.BehaveException: Método não implementado.)

**Comment by rogernobre** [comment]
Na versão 1.4.3-SNAPSHOT funciona.

Na versão 1.4.3-SNAPSHOT não funciona.

**Comment by juliancesar** [comment]
@rogernobre, estes métodos anteriormente não faziam nada, e na nova versão estão lançando uma exception!

https://github.com/demoiselle/behave/commit/129c8e07b179929193227bc12a92efb4e85d100c

Você tem algum código pronto para estes casos?

**Comment by juliancesar** [comment]
Corrigido. Mas existem vários métodos para desktop que ainda estão sem implementação.
