### ISSUE TITLE
Erro no projeto exemplo "calculadora" na versão 1.4.3-SNAPSHOT

### ISSUE THREAD

**Issue by rogernobre** [demoiselle/behave#335]
Erro no projeto exemplo "calculadora" na versão 1.4.3-SNAPSHOT. 

O arquivo "pom.xml" apresenta o seguinte erro: 

-Could not find artifact br.gov.frameworkdemoiselle.component.behave:demoiselle-behave-regression-report:pom:1.4.2-SNAPSHOT

**Comment by botelhojp** [comment]
Havia esquecido de habilitar o deploy do behave-regression-report.
Tente novamente usar a versão 1.4.4-SNAPSHOT

**Comment by botelhojp** [comment]
deploy corrigido
