### ISSUE TITLE
Verificar se uma opção está na lista de opções de uma combo select

### ISSUE THREAD

**Issue by arildojg** [demoiselle/behave#336]
Como o step 

> ser\u00E1 exibido {na|no} **\"$elementName\"** o valor **\"$text\"**

Foi pensado para verificar se o valor que está selecionado na combo **$elementName** é igual a **$text**, falta uma instrução para verificar se uma determinada opção, que não necessariamente é a opção selecionada, está na lista de opções da combo, algo como

> {na|no} select **\"$elementName\"** existe uma opção com valor **\"$text\"**

(Texto do step apenas ilustrativo)

**Comment by rogernobre** [comment]
@arildojg, para mim seria:
{na|no} \"$elementName\" existe opção com valor \"$text\"
{na|no} \"$elementName\" existem opções com valores \"$text\"
{na|no} \"$elementName\" somente existem opções com valores \"$text\"

**Comment by arildojg** [comment]
Abri a issue pela necessidade de um step conforme a primeira sugestão @rogernobre. Mas realmente se tivéssemos os três steps seria ótimo, especialmente o terceiro, para garantir que a combo deve ter um número x de opções e identificar quais são essas x opções esperadas. Até cheguei a comentar com o @juliancesar a possibilidade de implementá-lo.
Um colega implementou um step similar a esse terceiro que sugeriu, mas para verificar mensagens esperadas na lista de mensagens da tela. Talvez possa ser aproveitado.

**Comment by rogernobre** [comment]
@arildojg, seria exatamente o valor ou o label no caso do select?

**Comment by juliancesar** [comment]
@rogernobre, valide para mim o Pull Request #351 que trata estas questões de Checkbox e Radiobutton. Aguardo os seus comentários.

**Comment by botelhojp** [comment]
Pessoal durante a avaliação é sempre bom ter um exemplo no mix para testarmos estes novos recursos. Há alguma página do primefaces que tenha exemplos desses Checkbox e Radiobutton ?

**Comment by juliancesar** [comment]
@rogernobre, favor ignorar meu último comentário nesta issue.

**Comment by rogernobre** [comment]
@botelhojp, essa issue não está ligada ao primefaces.

**Comment by rogernobre** [comment]
@arildojg, seria exatamente o valor ou o label no caso do select?

**Comment by botelhojp** [comment]
Verdade! estava falando da #331

**Comment by jorgesartori** [comment]
Para o sistema atual q estamos testando seria melhor o label.
Como o @arildojg comentou, para o terceiro passo sugerido já temos a lógica feita...
Por hora vamos mapear o list separado para esta análise.

**Comment by juliancesar** [comment]
Senhores, algum avanço neste questão?

**Comment by juliancesar** [comment]
Fecharei esta issue e caso ela se torne relevante novamente favor reabrir.
