### ISSUE TITLE
Menu principal da aplicação java swing treino não aparece

### ISSUE THREAD

**Issue by rogernobre** [demoiselle/behave#340]
Menu principal da aplicação java swing treino não aparece.

Estou usando:
- Ubuntu 15.04 64-bit
- Demoiselle Eclipse 4.4.0
- JDK Oracle 1.7.0_79 64-bit

![tela](https://cloud.githubusercontent.com/assets/3092623/7625076/f2d3a964-f9c8-11e4-8ea2-7f5818900383.png)

**Comment by juliancesar** [comment]
@rogernobre, qual versão do **dbehave** você esta usando?
Eu estou usando a **1.4.4-SNAPSHOT** com **Ubuntu 12.04** e esta funcionando.

**Comment by rogernobre** [comment]
@juliancesar, eu estou usando a 1.4.4-SNAPSHOT.
No Serpro, uso com Ubuntu 12.04 e esta funcionando.
Em casa, uso com Ubuntu 15.04 e não esta funcionando.

**Comment by rogernobre** [comment]
@juliancesar, o problema é configuração do SO.
O menu fica oculto, mas aparece quando a barra de menu recebe focus:
![barramenu](https://cloud.githubusercontent.com/assets/3092623/7693302/cc218b52-fda5-11e4-8510-6c28e053094e.png)
Mudei a configuração:
![so](https://cloud.githubusercontent.com/assets/3092623/7693316/18b289e4-fda6-11e4-991a-e719d17d5a93.png)
O menu fica oculto, mas aparece quando a barra de titulos recebe focus:
![menu](https://cloud.githubusercontent.com/assets/3092623/7693325/2cf12e24-fda6-11e4-979c-8d206fb8575d.png)

**Comment by rogernobre** [comment]
@juliancesar, só ferrou os testes por que o menu está oculto.
