### ISSUE TITLE
Sikuli não reconhece imagens

### ISSUE THREAD

**Issue by RenatoEller** [demoiselle/behave#342]
Bom dia pessoal,
estou utilizando o debehave com demoiselle 2.5 e surgiu a necessidade de fazer o upload de arquivos. Me recomendaram o Sikuli, mas me deparei com o seguinte problema:
Ao recortar imagem da tela com cores mais fortes, o Sikuli reconhece a imagem. Se recorto uma parte da tela com cores mais claras, como o nome de um arquivo ou pasta por exemplo, ele não reconhece.
Alguma sugestão?
Obs: segui os passos abaixo para implementar:
http://voce.serpro/demoiselle-behave/blog/adicionar-a-api-sikuli-junto-com-dbehave

**Comment by rogernobre** [comment]
@RenatoEller, qual o score que você está usando? 0,7?

Diminua para ver.

Outra coisa, qual a biblioteca de componente que você está usando?

**Comment by rogernobre** [comment]
Outra coisa, o navegador e o so que você usou quando tirou um screenshot da imagem é o mesmo que seu script de testes usa?

**Comment by RenatoEller** [comment]
@rogernobre , estou usando o score 0.7. Já diminui e aumentei, e nada.
O navegador que estou utilizando é o mesmo (firefox), tanto no screenshot quanto na execução do script.
Em último caso vou manipular via javascript, só acho uma pena, pois vejo o pessoal na net comentando que usa e funciona. Segue abaixo as bibliotecas:
import java.net.URL;
import org.sikuli.api.DesktopScreenRegion;
import org.sikuli.api.ImageTarget;
import org.sikuli.api.Target;
import org.sikuli.api.ScreenRegion;

**Comment by rogernobre** [comment]
@RenatoEller, você é do Serpro? Usa Ubuntu? Está logando na máquina com Ubuntu 2D? Se estiver mude na parte do login do usuário do SO para Ubuntu (não Ubuntu 2d). Na sua máquina tem todas as dependências?

**Comment by rogernobre** [comment]
@RenatoEller, sobre as bibliotecas, queria saber sobre o componente que faz upload de arquivos na aplicação. A maioria já tem uma api completa para manipular o componente via javascript.

**Comment by rogernobre** [comment]
@RenatoEller, não sei qual o método que você está usando, mas deve ser um método que tira um screenshot na hora antes de tentar clicar no elemento da imagem, isto é, se outra aplicação estiver na frente da sua aplicação que contem a imagem que você está procurando ele não vai achar a imagem.

**Comment by rogernobre** [comment]
@RenatoEller, outra coisa, essa issue deveria ser aberta aqui? ou no voce.serpro?

**Comment by RenatoEller** [comment]
@rogernobre, loguei no ubuntu não 2d, como você sugeriu, capturei as imagens novamente pra ter certeza que as anteriores não estavam em baixa resolução, mas continua não reconhecendo. 
O componente que faz upload foi desenvolvido pela própria equipe e utiliza Ajax.
Sobre abrir aqui ou lá, boa pergunta. Qual a diferença? Sempre tiro minhas dúvidas aqui, por isso abri a issue aqui.
Segue o a biblioteca da aplicação utilizada para fazer o upload:


var chaveArquivo = null; //Operações de arquivos podem ser feitas uma por vez, independente do objeto de upload atual.
var tabelaArquivo = null;
var uploadArquivoAtual = null;
var uploadEmOperacao = null;

var uploadList = [];

Upload = function(strUrl) {
	this.url = strUrl;
	this.autenticar = true;
	this.idContainer = null;
	this.tabela = null;
	this.isTabelado = false;
	this.arquivoUpload = null;
		
	this.executeUpload = function() {
		if (uploadEmOperacao) {
			Forms.exibirGrowl('warn', 'Já existe um upload em andamento. Aguarde o término.');
		} else {
			uploadEmOperacao = this;
			realizarUpload();
		}
	}
	
	this.excluirArquivo = function(strUrl) {
		var upload = this;
		return $.ajax({
			type: 'DELETE',
			url: strUrl,
			contentType : "application/json",
			beforeSend : funcaoAutenticacao(upload)
		});
	}
	
	this.downloadArquivo = function(strUrl) {
		if (this.autenticar) App.createAuthCookie();
		$.fileDownload(strUrl).done(function(){
			Forms.exibirGrowl('success', 'Download ocorreu com sucesso!');
		}).fail(function(){
			Forms.exibirGrowl('error', 'Falha ao baixar arquivo.');
		});
	}
	
	this.gerarInterface = function(strContainer) {
		this.idContainer = strContainer;
		renderizaContainer(this);
	}
	
	function realizarUpload() {
		if (uploadEmOperacao) {
			ids = getIds(uploadEmOperacao);
			var inputFile = document.getElementById(ids.inputFile);
			var arquivo = inputFile.files[0];
			
			if (!this.failureFunction) this.failureFunction = null;
				
			//grab all form data  
			var formData = new FormData();
			formData.append("userFile", arquivo);
			enviarFormulario(uploadEmOperacao, formData).done(uploadConcluido).fail(uploadComErro);
		}
	}
	
	function cancelaUpload() {
		if (uploadEmOperacao) {
			habilitaBotaoSubmissao($('#' + ids.btnSelecionar));
			$('#' + ids.progress).css('width', '0%');
			uploadEmOperacao = null;
		}
	}
	
	function getUpload(strContainer) {
		var upload = null;
		$.each(uploadList, function(index, object) {
			if (object.idContainer == strContainer) {
				upload = object;
			}
		});
		return upload;
	}
	
	function getUploadFromTable(strTabela) {
		var nomes = strTabela.split(SEPARADOR_NOMES);
		var nomeTabela = nomes[0];
		var upload = null;
		$.each(uploadList, function(index, object) {
			if (object.isTabelado) {
				if (object.tabela && (object.tabela.idTabela == nomeTabela)) {
					upload = object;
				}
			}
		});
		return upload;
	}
	
	function getTabela(strTabela) {
		var tabela = null;
		var upload = getUploadFromTable(strTabela);
		if (upload) {
			tabela = upload.tabela;
		}
		return tabela;
	}
	
	function getIds(upload) {
		return {
			form: 'frm-' + upload.idContainer,
			inputFile: 'file-' + upload.idContainer,
			fileName: 'fileName-' + upload.idContainer,
			btnSelecionar: 'btnSelecionar-' + upload.idContainer,
			progress: 'progress-' + upload.idContainer,
			containerTabela: 'tabela-' + upload.idContainer,
			tabela: 'tblUpload-' + upload.idContainer
		}
	}
	
	function uploadConcluido(data) {
		var upload = uploadEmOperacao;
		uploadEmOperacao = null; 
		if (upload) {
			ids = getIds(upload);
			habilitaBotaoSubmissao($('#' + ids.btnSelecionar));
			$('#' + ids.progress).css('width', '0%');
			$('#' + ids.fileName).val('O tamanho máximo de arquivo é de 10 MB');
			//
			if (upload.isTabelado) upload.tabela.adicionaLinha(data);
			Forms.exibirGrowl('success', 'Upload do arquivo "' + upload.arquivoUpload + '" concluído com sucesso.');
		}
	}

	function uploadComErro(response) {
		cancelaUpload();
		processaMensagensRetorno(response);		
	}
	
	function enviarArquivo(e) {
		if (uploadEmOperacao) {
			Forms.exibirGrowl('warn', 'Já existe um upload em andamento. Aguarde o término.');
		} else {
			var file = $(this).val();
			var uploadObjectId = $(this).attr('upload-object');
			var upload = getUpload(uploadObjectId);
			
			if (upload) {
				uploadEmOperacao = upload;
				ids = getIds(upload);
				if (file) {
					//Se existe o arquivo, transferir.
					upload.arquivoUpload = file.replace(/^.*[\\\/]/, '');
					$('#' + ids.fileName).val(upload.arquivoUpload);
					desabilitaBotaoSubmissao($('#' + ids.btnSelecionar));
					Forms.retornoConfirmacao = function(ok) {
						if (ok) {
							$('#' + ids.progress).css('width', '100%');
							realizarUpload();
						} else {
							cancelaUpload();
						}
					}
					mensagemConfirmacao('Confirmação', 'Ok', 'Cancelar', 'Deseja transferir o arquivo "' + upload.arquivoUpload + '"?');
				} else {
					$('#' + ids.fileName).val('O tamanho máximo de arquivo é de 10 MB');
				}
			}
		}
	}	

	function baixarClick() {
		var chave = $(this).val();
		var tabela = getTabela($(this).attr('id'));
		var linha = tabela.getLinha(chave);
		
		Forms.baixarArquivo(chave); //Somente usuários autenticados podem baixar arquivos
		Forms.exibirGrowl('info', 'Baixando arquivo "' + linha.nome + '".');
	}

	function excluirClick() {
		function excluirArquivoOk() {
			if (uploadArquivoAtual) {
				var tabela = uploadArquivoAtual.tabela; 
				var nome = 'desconhecido';
				var linha = tabela.getLinha(chaveArquivo);
				if (linha) nome = linha.nome;
				tabela.removeLinha(chaveArquivo);
				chaveArquivo = null;
				Forms.exibirGrowl('success', 'O arquivo "' + nome + '" foi removido com sucesso.');	
			}
		}

		function acaoArquivoErro(response) {
			chaveArquivo = null;
			processaMensagensRetorno(response);
		}
		
		if (chaveArquivo) {//Evita ações simultâneas
			Forms.exibirGrowl('warn', 'Aguarde o término da operação com outro arquivo.');
		} else {
			chaveArquivo = $(this).val();
			uploadArquivoAtual = getUploadFromTable($(this).attr('id'));
			if (uploadArquivoAtual) {
				var linha = uploadArquivoAtual.tabela.getLinha(chaveArquivo);
				Forms.retornoConfirmacao = function(ok) {
					if (ok) {
						uploadEstatuto.excluirArquivo(chaveArquivo).done(excluirArquivoOk).fail(acaoArquivoErro);
					} else 
						chaveArquivo = null;
				}
				mensagemConfirmacao('Confirmação', 'Ok', 'Cancelar', 'Deseja excluir o arquivo "' + linha.nome + '"?');
			} else
				chaveArquivo = null;
		}
	}
	
	function renderizaContainer(upload) {
		var ids = getIds(upload); 
		html = '<form id="' + ids.idForm +  '">' +
			'	<input id="' + ids.inputFile + '" type="file" style="visibility:hidden;" upload-object="' + upload.idContainer + '">' +
			'</form>' +
			'<div class="form-inline">' +
			'	<div class="form-group">' +
			'		<label for="filtro">Selecione o arquivo:</label><span class="help-block">(Os formatos permitidos são: PDF, JPG, GIF, PNG, MPG, MPEG, AVI, TXT, ZIP)</span>' +
			'		<input type="text" class="form-control" id="' + ids.fileName + '" name="fileName" style="width: 400px" readonly="readonly" value="O tamanho máximo de arquivo é de 10 MB">' +
			'		<button id="' + ids.btnSelecionar + '" type="button" class="btn btn-primary">Selecionar</button>' +
			'		<div class="progress" style="max-width: 400px">' +
			'			<div id="' + ids.progress + '" class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">' +
			'				<span class="sr-only">Transferindo arquivo. Aguarde...</span>' +
			'			</div>' +
			'		</div>' +									  
			'	</div>' +
			'</div>' +
			'<div id="' + ids.containerTabela + '"></div>';
		
		$('#' + upload.idContainer).html(html);
		
		if (upload.isTabelado) {
			tabela = new Table();
			tabela.colunas = [
                  new TableColumn('dataUpload', 'Data do Upload'),
                  new TableColumn('nome', 'Arquivo'),
           		  new TableColumn('baixar', 'Baixar'),
   				  new TableColumn('excluir', 'Excluir')
            ];
			tabela.textoEmpty = 'Nenhum arquivo foi transferido.';
			var acaoBaixar = new TableAction('baixar', new IconButton('glyphicon-save', 'Baixar Arquivo'), baixarClick);
			var acaoExcluir = new TableAction('excluir', new IconButton('glyphicon-remove', 'Excluir Arquivo'), excluirClick);
			tabela.acoes = [acaoBaixar, acaoExcluir];
			tabela.chave = 'url';
			tabela.gerarTabela(ids.containerTabela, ids.tabela);
			upload.tabela = tabela;
		}
		
		$('#' + ids.inputFile).on('change', enviarArquivo);
		$('#' + ids.btnSelecionar).click(function() {
			$('#' + ids.inputFile).click();
		});
		
	}

	function enviarFormulario(upload, formData) {
		return $.ajax({
			type: 'POST',
			url: 'api/' + upload.url,
			data: formData,
			async: false,
			cache: false,
			contentType: false,
			processData: false,
			beforeSend : funcaoAutenticacao(upload)				
		});
	}
	
	function funcaoAutenticacao(upload) {
		if (upload.autenticar) 
			return function(request) {
				App.setHeader(request);
			}			
			else return null;
	}
	
	//Adiciona objeto na lista 
	uploadList[uploadList.length] = this;
		
	App.loadJS('js/lib/jquery.fileDownload.js');
}

**Comment by rogernobre** [comment]
@RenatoEller, como sikuli não faz parte do framework, acho melhor lá.

Tente qualquer imagem na tela, por exemplo, a caixa de seleção dos arquivos para ver se ele acha.

Lembrando que a api do sikuli tem dependências, e que o navegador deve se a aplicação ativa e a vista na area de trabalho, na hora da chamada ao método. 

Estranho que mesmo você disse que mudando o score não acontece nada.

**Comment by rogernobre** [comment]
@RenatoEller, na sua página já tem todas as funções para realizar o upload.

Veja com o pessoal que construiu os parâmetros e chame através do webdrive.

**Comment by rogernobre** [comment]
@RenatoEller, dicas: ids.inputFile; realizarUpload()

**Comment by rogernobre** [comment]
@RenatoEller, por favor cole aqui a imagem que o sikuli não achou e a um screenshot da area de trabalho no momento que deveria ocorrer o clique. para analisar o score minimo.

**Comment by RenatoEller** [comment]
@rogernobre , seguem 2 imagens e a tela:

![botao abrir](https://cloud.githubusercontent.com/assets/11670038/7758299/19936d84-ffdf-11e4-9f31-6943df87c041.png)
![sistema de arquivos](https://cloud.githubusercontent.com/assets/11670038/7758300/1993aa10-ffdf-11e4-9494-4b5af39d4444.png)
![tela](https://cloud.githubusercontent.com/assets/11670038/7758301/19940f3c-ffdf-11e4-8f2f-5d35a89c7c4c.png)

**Comment by RenatoEller** [comment]
Esta imagem o sikuli encontra:
![serpro](https://cloud.githubusercontent.com/assets/11670038/7758360/7635ee54-ffdf-11e4-8b8f-d0af1f2e2549.png)

**Comment by rogernobre** [comment]
Olhe como aparece para mim a imagem da tela:

![telaembranco](https://cloud.githubusercontent.com/assets/3092623/7758431/0c2885c0-ffe0-11e4-868c-4655a54a8f76.png)

**Comment by RenatoEller** [comment]
Sim, esta é a imagem do ícone "Sistema de Arq..." a ser clicado na tela.

**Comment by rogernobre** [comment]
E o dialogo "Enviar arquivo".

Tem como enviar a tela inteira no momento em que o script chama o metodo do clique que usa sikuli?

**Comment by RenatoEller** [comment]
Tinha enviado também, mas acho que não foi. Segue o diálogo:

![tela](https://cloud.githubusercontent.com/assets/11670038/7758598/2b4425e4-ffe1-11e4-9a19-ead3c51fbed2.png)

**Comment by rogernobre** [comment]
Repetindo:

Tem como enviar a tela inteira no momento em que o script chama o metodo do clique que usa sikuli?

**Comment by RenatoEller** [comment]
Essa ou a exatamente anterior a esta:?
![tela inteira](https://cloud.githubusercontent.com/assets/11670038/7758750/62d25066-ffe2-11e4-803f-364aa58c5aab.png)

**Comment by rogernobre** [comment]
Essa, vlw.

**Comment by juliancesar** [comment]
@rogernobre, algum retorno sobre o assunto?

**Comment by RenatoEller** [comment]
Uma informação que talvez ajude na identificação do problema: Ao explorar mais, verifiquei que o sikuli só reconhece as imagens da barra ferramentas do linux (aquela que vem como padrão o botão do Serpro, Writer, Calc, etc.)

**Comment by juliancesar** [comment]
Senhores, houve algum avanço nesta questão?

**Comment by RenatoEller** [comment]
Não, sem avanços até o momento.

**Comment by rogernobre** [comment]
@RenatoEller, então o sikuli não está funcionando na sua máquina. Isso acontecia quando o pessoal logava como Ubuntu 2D nas máquinas do SERPRO.

**Comment by rogernobre** [comment]
@RenatoEller, tente instalar o Sikuli Script (http://www.sikuli.org/download.html) e depois coloque uma referência no classpath do seu projeto para o "sikuli-java.jar".

**Comment by rogernobre** [comment]
@RenatoEller, antes disso só reveja a versão do sikuli api:

![dep](https://cloud.githubusercontent.com/assets/3092623/8816235/86656c28-2ffa-11e5-8c46-9e0f9d18f7bb.png)

**Comment by rogernobre** [comment]
Recorte essas imagens para criar um exemplo de teste:
![busca_chrome](https://cloud.githubusercontent.com/assets/3092623/8816735/26dbad6a-3001-11e5-9b7e-bb0c8b5b1907.png)
![busca_firefox](https://cloud.githubusercontent.com/assets/3092623/8816737/26e489c6-3001-11e5-8028-9b283bb3060f.png)
![chrome](https://cloud.githubusercontent.com/assets/3092623/8816738/26e61e80-3001-11e5-8daa-c006bf307cd4.png)
![firefox](https://cloud.githubusercontent.com/assets/3092623/8816736/26e2b948-3001-11e5-985c-5213bb4623a9.png)

**Comment by rogernobre** [comment]
Teste usando o seguinte exemplo:

package teste2;

import java.net.MalformedURLException;
import java.net.URL;

import org.sikuli.api.DesktopScreenRegion;
import org.sikuli.api.ImageTarget;
import org.sikuli.api.ScreenRegion;
import org.sikuli.api.Target;
import org.sikuli.api.robot.Keyboard;
import org.sikuli.api.robot.Mouse;
import org.sikuli.api.robot.desktop.DesktopKeyboard;
import org.sikuli.api.robot.desktop.DesktopMouse;

public class Teste {

	public static void main(String[] args) throws MalformedURLException {
		String navegador = "Chrome";
		
		ScreenRegion tela = new DesktopScreenRegion();
		Mouse mouse = new DesktopMouse();
		Keyboard teclado = new DesktopKeyboard();

		URL imagemNavegador = ClassLoader.getSystemResource(navegador + ".png");
		Target targetNavegador = new ImageTarget(imagemNavegador);
		ScreenRegion screenRegionNavegador = tela.wait(targetNavegador, 5000);

		mouse.click(screenRegionNavegador.getCenter());

		try {
			Thread.sleep(5000l);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}

		URL imagemCampoBusca = ClassLoader.getSystemResource("Busca_" + navegador + ".png");
		Target targetCampoBusca = new ImageTarget(imagemCampoBusca);
		ScreenRegion screenRegionCampoBusca = tela.wait(targetCampoBusca, 5000);

		if (screenRegionCampoBusca != null) {
			teclado.type("Sikuli");
		}
	}

}

**Comment by rogernobre** [comment]
@RenatoEller, relate em que linha do exemplo deu erro...

**Comment by RenatoEller** [comment]
@rogernobre 
Alterei a classe main incluindo o local onde salvei as imagens (/Testes):

public static void main(String[] args) throws RuntimeException, IOException {
		String navegador = "Firefox";
		clicarNaImagem(navegador + ".png", "/Testes/",
				"Onde esta o icone");
		clicarNaImagem("Busca_" + navegador + ".png", "/Testes/",
				"Onde esta o campo de busca");
		teclado.type("Sikuli");
}

Ocorreu o seguinte erro:

Exception in thread "main" java.lang.IllegalArgumentException: input == null!
	at javax.imageio.ImageIO.read(ImageIO.java:1388)
	at org.sikuli.api.ImageTarget.<init>(ImageTarget.java:39)
	at br.gov.serpro.novosiconv.sikuli.Test.buscarNaTela(Test.java:33)
	at br.gov.serpro.novosiconv.sikuli.Test.clicarNaImagem(Test.java:40)
	at br.gov.serpro.novosiconv.sikuli.Test.main(Test.java:50)

A linha 33 é a seguinte:
	Target target = new ImageTarget(imagem);

**Comment by RenatoEller** [comment]
Obs.: a biblioteca sikuli-core-1.1.3.jar não estava presente no meu projeto. Acrescentei, mas não surtiu efeito nos meus testes.

**Comment by juliancesar** [comment]
@RenatoEller, você conseguiu evoluir neste assunto?

**Comment by RenatoEller** [comment]
@juliancesar , negativo. Surgiram outras demandas mais importantes e acabei deixando esta de lado. Recomenda fechar a issue?

**Comment by juliancesar** [comment]
@RenatoEller, sim, vou fechar ela e quando voltar no assunto podemos reabrir ela.
Obrigado.

**Comment by MrXPanze** [comment]
Alguém conhece um comando que faça o sikuli apagar o texto já existente em um campo ??
