### ISSUE TITLE
cannot get automation extension

### ISSUE THREAD

**Issue by estivalet** [demoiselle/behave#349]
Acho que esse erro não tem relação com o framework, mas está acontecendo ao rodar meus testes usando o google chrome no windows 7.

Alguém já passou por isso? Alguma solução?

O que eu pesquisei é que tem relação com a maximização da tela antes de rodar os testes. Por sinal, coloquei behave.runner.window.maximize.enabled=true e o chrome não iniciou maximizado.

Failed to run batch 
org.jbehave.core.embedder.StoryRunner$SomethingHappened@18488ef: org.jbehave.core.failures.BeforeOrAfterFailed: Method startStories (annotated with @BeforeStories in class br.gov.frameworkdemoiselle.behave.parser.jbehave.BeforeAfterSteps) failed: org.openqa.selenium.WebDriverException: unknown error: cannot get automation extension

**Comment by arildojg** [comment]
Quando executo os testes localmente, em linux, no chrome, com usuário sem permissões de administrador, sempre é exibida esta msg qdo o selenium abre o navegador: "Could not load extension from "/tmp/PASTA_CRIADA_DINAMICAMENTE". Loading of unpacked extensions is disabled by the administrator."

Quando ocorre falha em um teste, a criação do screenshot da tela no momento da falha também não está ocorrendo. No console obtenho um erro com msg bem similar a sua: 

```
12:14:36,612 ERROR (pool-1-thread-1) [ScreenShootingMaker]: Erro ao salvar screenshot [PATH DA PAGINA] caminho [PATH DO ARQUIVO QUE SERIA CRIADO] causa [unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
  (Session info: chrome=34.0.1847.137)
  (Driver info: chromedriver=2.10.267517,platform=Linux 3.2.0-58-generic-pae x86) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10.01 seconds
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'serpro-1546430', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'i386', os.version: '3.2.0-58-generic-pae', java.version: '1.7.0_67'
Session ID: b8a93ceeba0436bd954ad9df5edcdb97
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.EknBuf}, rotatable=false, locationContextEnabled=true, version=34.0.1847.137, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]]
12:14:36,612 ERROR (pool-1-thread-1) [ScreenShootingMaker]: org.openqa.selenium.WebDriverException: unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
  (Session info: chrome=34.0.1847.137)
  (Driver info: chromedriver=2.10.267517,platform=Linux 3.2.0-58-generic-pae x86) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10.01 seconds
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'serpro-1546430', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'i386', os.version: '3.2.0-58-generic-pae', java.version: '1.7.0_67'
Session ID: b8a93ceeba0436bd954ad9df5edcdb97
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.EknBuf}, rotatable=false, locationContextEnabled=true, version=34.0.1847.137, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
Então será exibido no "CAMPO" o valor "VALOR" (FAILED)
```

**Comment by arildojg** [comment]
![erroextensoeschrome](https://cloud.githubusercontent.com/assets/4246255/8235194/fd36c8e6-15b6-11e5-9899-9c78bf79255e.jpg)

**Comment by estivalet** [comment]
É praticamente a mesma mensagem que tenho aqui no Win7, o detalhe é que sou administrador local da máquina.

**Comment by arildojg** [comment]
Funciona o screenshot qdo um passo falha?

**Comment by estivalet** [comment]
não funciona também

**Comment by juliancesar** [comment]
@estivalet, este problema relatado acontece em quais versões do dbehave?

**Comment by juliancesar** [comment]
Uma nova versão **1.5.1-SNAPSHOT** foi gerada com a correção.
Caso o problema persista, favor reabrir a issue.

**Comment by estivalet** [comment]
Infelizmente continuo com o mesmo problema na nova versão. Antes de iniciar o navegador aparece um popup "Could not load extension" e quando um passo da história falha tem o seguinte erro:

Quando informo "Fazenda Federal" no campo "tipo da prova de regularidade" (FAILED)
(java.lang.reflect.UndeclaredThrowableException)
13:55:24,968 ERROR (pool-1-thread-1) [ScreenShootingMaker]: Erro ao salvar screenshot [http://localhost:4200/fornecedor/2/prova-regularidade/nova] caminho [C:\Users\lestivalet\workspace\SACTest\target\jbehave\view\screenshots\failed-scenario-b0e31c0e-4905-40e2-9e2f-ff58177b2e4d.png] causa [unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
  (Session info: chrome=43.0.2357.124)
  (Driver info: chromedriver=2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3),platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10.09 seconds
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'SETIC-15311', ip: '10.4.3.110', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.6.0_45'
Session ID: 034696e6c201b613824746f0cfb24ea5
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=XP, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=C:\Users\LESTIV~1\AppData\Local\Temp\scoped_dir2344_3842}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=43.0.2357.124, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]]
13:55:24,968 ERROR (pool-1-thread-1) [ScreenShootingMaker]: org.openqa.selenium.WebDriverException: unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
  (Session info: chrome=43.0.2357.124)
  (Driver info: chromedriver=2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3),platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10.09 seconds

Aliás, pelo que percebi está dando sempre o erro "cannot get automation extension" quando algum passo não pode ser executado corretamente. No exemplo acima deu o erro no passo "Quando informo "Fazenda Federal" no campo "tipo da prova de regularidade" (FAILED)". O campo é textfield e existe na tela.
