### ISSUE TITLE
Por que a cada execução de método são mantidos em memória todos os .story de cenários anteriores?

### ISSUE THREAD

**Issue by ttperes** [demoiselle/behave#352]
Notei aqui em um projeto bem grande, em torno de 900 cenários, que quando executamos o projeto inteiro é mantido no vetor de histórias todas os arquivos .story já armazenados. Gostaria de saber o motivo, pois já que cada cenário é feito para ser uma unidade, por que são mantidos em memória?

Imagina que executo o projeto inteiro com os 900 cenários, a cada adição de cenário é necessário verificar duplicidade e outras questões em todo o vetor de histórias, o que não faz sentido, pois aquele cenário não vai mais ser executado pois já não estou mais no seu método. 

Os Steps eu até entendo, pois podemos ter o mesmo para uma classe inteira. Mas os .story são montados por métodos...

Sugestão: na classe behaveContext adicionar allOriginalStoriesPath.clear(); na linha 135.

**Comment by juliancesar** [comment]
Teríamos que pegar o histórico das *issues* e *commits* para verificar o motivo pelo qual chegamos a este comportamento ou poderíamos alterar o fonte e rodar todos os testes dos samples e verificar se continuará funcionando e depois propor esta alteração e testar em alguns projetos reais, pois ela é **muito impactante** e pode prejudicar o andamento de dezenas de projetos.

Se você tiver disponibilidade para fazer isso seria muito interessante.

Por curiosidade, na prática, este comportamento está causando algum problema nos seus projetos?

**Comment by ttperes** [comment]
oi @juliancesar, então descobrimos esse comportamento pois neste projeto com muitos casos de teste, as vezes temos variações nas histórias em .story diferentes que tem o mesmo nome de cenário. Na prática o nome do cenário para entendimento deveria se manter o mesmo já que as .story são chamadas por métodos java diferentes de diferentes classes. O que acontece é quando executamos o projeto como um todo, ele vai armazenando todas as histórias executadas por todoas as classes e acontece o erro de história repetida. 
Para evitar o erro sem comprometer o entendimento do nome do cenário temos que ficar adicionando índices nos nomes para evitar o erro de repetição. Sendo que essas repetições nunca acontecem pois são realizadas por métodos diferentes que não trabalham com os mesmos cenários, a repetição só acontece pelo fato do behave ficar armazenando tudo que é executado sem eliminar nada.

Acredito que não teria impacto, nunca vi ninguem usando o behave sem colocar todos os .story que precisam no método que é executado. A alteração só impactaria se alguém que tivesse por exemplo 2 cenários, usasse no 2o método referência de um .story adicionado pelo 1o método. Conforme as práticas de testes, sabemos que cada método deve ser independente entre si, logo ao permitir esse comportamento o behave está também infringindo de certa forma a independência dos testes. Até por que como eles podem ser executados fora de ordem, ao executar 1o o método 2, ainda não teríamos em memória o .story que ele faria referência do método 1.

**Comment by juliancesar** [comment]
@ttperes, favor testar em nossos samples também, faça o Pull Request com a modificação e eu vou correr atrás de outros projetos reais para testar.

Samples: https://github.com/demoiselle/behave/tree/master/sample

**Comment by juliancesar** [comment]
Encontramos uma solução de contorno com um novo método chamado *clearAllOriginalStories*. Uma versão **1.5.1-SNAPSHOT** será gerada ainda hoje para testes.

Contudo é importante que façamos uma revisão do método **run(List<String> storiesFiles)** da classe **BehaveContext** para corrigir alguns problemas conceituais de reuso de histórias. Sugiro que a futura versão **1.6.0** contenha essas alterações, pois será uma mudança que irá gerar um impacto nos projetos em andamento.

**Comment by ttperes** [comment]
Oi @juliancesar a princípio eu acredito que precisamos de dividir o reuso em 3 categorias que atenderiam a maioria dos casos.

adicionar histórias ao projeto (teoricamente seriam histórias de reuso, podemos ter apenas uma opção dessas para o projeto)
adicionar histórias de reuso ao projeto
adicionar passos ao projeto

adicionar histórias para a classe
adicionar histórias de reuso para a classe
adicionar passos para a classe

adicionar histórias para o método
adicionar histórias de reuso para o método
adicionar passos para o método

Acho que com esses 3 subgrupos conseguiremos contemplar os diferentes escopos e não ficaremos presos a uma interpretação, deixando assim que as equipes definam a melhor forma que pretendem trabalhar. Podendo inclusive fazer mesclas das mesmas.

Acho que podem ser criados diferentes eng.add() para cada tipo, e já que hoje o padrão é de adicionar tudo, deixar talvez uma properties de behavecontext.legacy.compatibility=true/false para que os projetos antigos não sofram impacto.

Com esta opção de legado ligada, o comportamento seria o da versão antiga para que projetos feitos anteriormente não sofram impactos.

Aí talvez num marco maior de versão do projeto remover de vez a opção de legado. Não sei como seria a política de vocês.

**Comment by juliancesar** [comment]
@ttperes, você pretende fazer algum Pull Request com relação a este comportamento?

**Comment by ttperes** [comment]
Oi @juliancesar, acabei de implementar uma versão alpha desse comportamento. Porém ainda deixei os métodos originais por conta de manter a retrocompatibilidade. Teria como fazer um pull request para você dar uma olhada se a ideia ficou legal?

**Comment by fgsl** [comment]
@ttperes, você fará o pull request citado em #issuecomment-178119026?

**Comment by ttperes** [comment]
Oi @fgsl , se for relacionado ao comentário do dia 23 de junho, esse comportamento já foi comitado no dbehave tem um bom tempo no snapshot atual. Tenho usado aqui bastante e ainda não detectei problemas.
