### ISSUE TITLE
Some relatório no plano de teste filho após integração.

### ISSUE THREAD

**Issue by Viveiros** [demoiselle/behave#355]
Estamos com um problema ao integrar o Dbehave com o RQM, verificamos que o Relatório de testes está sumindo do Plano de testes filho. O fato ocorreu após execução no eclipse dos testes automatizados integrados com o ALM. Esse problema não existia porém após a atualização do RQM passou a acontecer, mas sei dizer com certeza se existe ligação entre o problema e essa atualização.

**Comment by juliancesar** [comment]
Esta questão será tratada internamente.
