### ISSUE TITLE
Analisar proposta alternativa para manipulação de Grid

### ISSUE THREAD

**Issue by arildojg** [demoiselle/behave#356]
Analisar proposta enviada por outro colega para verificar se é possível mesclar com a iniciativa do colega @ttperes, ou manter como uma segunda implementação, complementar a já existente

**Comment by arildojg** [comment]
A implementação está descrita em comentário da issue #61
https://github.com/demoiselle/behave/issues/61#issuecomment-114509278

**Comment by ttperes** [comment]
@arildojg , @juliancesar Seria legal pôr mais exemplos.
Por exemplo, daria pra comparar múltiplos campos de uma só vez?
Nas tabelas que a linha final é a linha de incluir dados, eu conseguiria pegar a última linha para trabalhar?
Consigo guardar informações da tabela no dataprovider?
Jogar informações nela?
Você tem que mapear cada tipo de elemento (button, label, text)? A implementação que usei detecta por conta o elemento, assim o usuário não precisa mapear tudo da tabale ganhando tempo.
Basicamente o que entendi é um substituto do xpath com params.

**Comment by arildojg** [comment]
Usei a outra implementação que mencionei por que em certas ocasiões não sei em qual das linhas as informações e campos que vou utilizar estarão. Quando uma grid não tem ordenação fixa e não possui filtros as instruções que mencionei no comentário https://github.com/demoiselle/behave/issues/61#issuecomment-114509278 ajudaram a resolver o problema.

**Comment by rogernobre** [comment]
@ttperes, poderia mostrar um exemplo de mapeamento usado nos passos do GridSteps. Como ele difere da solução proposta pelo colega de BH?

**Comment by juliancesar** [comment]
@ttperes, algum retorno sobre o assunto?

**Comment by ttperes** [comment]
Foi respondido aqui https://github.com/demoiselle/behave/issues/61, último post.

**Comment by juliancesar** [comment]
@ttperes, então vou fechar a issue.
