### ISSUE TITLE
Problema com ListBox

### ISSUE THREAD

**Issue by RenatoEller** [demoiselle/behave#358]
Boa tarde, estou utilizando o dBehave com Demoiselle 2.5 e não estou conseguindo fazer funcionar um list box do tipo "UF" e selecionar estados. Na documentação não encontrei nada. Poderiam me indicar algum exemplo?

**Comment by juliancesar** [comment]
O exemplo mix tem essa situação no seguinte arquivo de história:

https://github.com/demoiselle/behave/blob/master/sample/mix/src/test/resources/stories/primefaces/input.story#L15

E neste mapeamento:

https://github.com/demoiselle/behave/blob/master/sample/mix/src/test/java/demoisellebehave/mix/pages/PrimefacesSelectCheckboxMenu.java#L13

**Comment by juliancesar** [comment]
@RenatoEller, vou fechar a issue, contudo se a questão ainda não tiver sido resolvida pode reabrir.
