### ISSUE TITLE
Espera fechar lista de valores de picklist

### ISSUE THREAD

**Issue by ednaldolira** [demoiselle/behave#359]
O sistema apresenta o seguinte erro:
>>Timed out after 10 seconds waiting for element to no longer be visible: By.xpath: id('painelCamposEntidade:pickListParticipantes')/div[1]/ul

quando usamos o elemento de PickList, ele dá timeout esperando que a lista feche, mas ela nunca vai fechar devido à natureza do componente.

Vejam abaixo o tipo de componente usado (ele está mapeado como Select):
![captura de tela de 2015-07-07 09 51 18](https://cloud.githubusercontent.com/assets/13219841/8546476/7f7777f2-248e-11e5-942a-80633f2c1a01.png)

Estamos fazendo algo errado ou o behave não está preparado para este tipo de componente, ou talvez seja um bug?

**Comment by ednaldolira** [comment]
fechei por engano

**Comment by gugaemc** [comment]
Estou interessado neste problema também.

**Comment by juliancesar** [comment]
@ednaldolira, o ideal seria a criação de um novo tipo elemento para esta situação, você pode entender como funciona seguindo este tutorial: https://github.com/demoiselle/behave/wiki/Como-criar-novos-tipos-de-elementos.

Ou, uma solução mais simples seria utilizar as suas opções como  se fosse botões e utilizar o mapeamento parametrizável para clicar na opção, utilize o seguinte Capítulo da documentação para isso: http://demoiselle.sourceforge.net/docs/components/behave/reference/lastversion/html/behave-screenmapping.html#d0e1241.

Tente uma das 2 sugestões e me retorne.

**Comment by juliancesar** [comment]
Esta questão será fechada por falta de retorno, caso o problema persista, favor reabrir.
