### ISSUE TITLE
Algumas frases pré-definidas não estão funcionando

### ISSUE THREAD

**Issue by RenatoEller** [demoiselle/behave#365]
Boa tarde pessoal,
estou utilizando o dbehave 1.5.0 no demoiselle 2.5. 
Algumas frases que utilizo nos meus testes pararam de funcionar nesta semana:
[Dado que | Quando | Então] confirmo a caixa de diálogo
[Dado que | Quando | Então] cancelo a caixa de diálogo
[Quando] limpo o valor do campo "<nome do campo>"
[Quando] não informo valor para o campo "<nome do campo>"
Alguma sugestão?

**Comment by juliancesar** [comment]
Renato, realmente não testamos o **dbehave** na nova versão **2.5**, você sabe qual biblioteca de interface que ele utiliza? Será que ainda é **Primefaces**?

**Comment by RenatoEller** [comment]
@juliancesar, não é o Primefaces. Os desenvolvedores do projeto aqui estão utilizando o Bootstrap.

**Comment by juliancesar** [comment]
O **dbehave** não da suporte aos componentes do **Bootstrap**, você terá que criá-los.
Segue um tutorial feito por outro colega para a criação de novos elementos.

https://github.com/demoiselle/behave/wiki/Como-criar-novos-tipos-de-elementos

**Comment by RenatoEller** [comment]
ok. Obrigado.
