### ISSUE TITLE
Adição da mesma .story 2x apresenta erro de webdriver quit()

### ISSUE THREAD

**Issue by ttperes** [demoiselle/behave#367]
Ao adicionar uma mesma .story repetidamente, não é apresentado nenhum erro, porém na execução recebemos (nem mesmo a screenshot é salva):

09:51:15,612 ERROR (pool-1-thread-1) [ScreenShootingMaker]: org.openqa.selenium.remote.SessionNotFoundException: The FirefoxDriver cannot be used after quit() was called.

exemplo de uso:

lista.add(a.story)
lista.add(b.story)
lista.add(a.story)
lista.add(c.story)

eng.run(lista);

O erro acontece na execução da 2a a.story.

**Comment by juliancesar** [comment]
Foi feita uma alteração no dbehave para que não permita adicionar 2 vezes a mesma história.
Com relação ao seu problema recomendo que os arquivos sejam reestruturados da seguinte forma:

lista.add(cenarios_de_reuso.story)
lista.add(a.story)
lista.add(b.story)
lista.add(c.story)

Caso tenha alguma outra dúvida, favor reabrir a issue.
