### ISSUE TITLE
Dúvida sobre o passo "movo o mouse sobre"

### ISSUE THREAD

**Issue by joaopaulosc** [demoiselle/behave#368]
Pessoal,

Percebi que o passo "@When("movo o mouse sobre \"$element\"")" foi retirado da classe CommonSteps a partir da versão 1.4.3. Se eu usar o Behave a partir desse versão e precisar de um passo como esse, eu terei que implementar um passo customizado ou existe outra maneira já implementada ?

**Comment by juliancesar** [comment]
Olá. As classes de passos comuns foi reestruturada, agora o passo em questão está na seguinte classe:
https://github.com/demoiselle/behave/blob/master/impl/parser/jbehave/src/main/java/br/gov/frameworkdemoiselle/behave/parser/jbehave/MouseControlSteps.java

**Comment by joaopaulosc** [comment]
Hum, ótimo! Deu certo. Obrigado
