### ISSUE TITLE
Dúvida configuração timeout

### ISSUE THREAD

**Issue by estivalet** [demoiselle/behave#369]
Pessoal, de onde vem esses 300 segundos??

Meu teste está parando no meio com essa mensagem:

6:07:23,600 DEBUG (pool-1-thread-1) [DefaultStoryReport]: Espera entre passos habilitada, aguardando [1s] antes de prosseguir
Quando clico em "menu fornecedores"
16:07:24,959 DEBUG (pool-1-thread-1) [DefaultStoryReport]: Espera entre passos habilitada, aguardando [1s] antes de prosseguir
Story stories\fornecedor.storyConverted duration of 301 seconds has exceeded timeout of 300 seconds

(AfterStories)
16:07:27,213 INFO  (main) [BeforeAfterSteps]: >>Finalizando Aplicação<<

Minha configuração está assim:

behave.runner.screen.type=GoogleChrome
behave.runner.screen.driverPath=c:/users/lestivalet/chromedriver.exe
behave.runner.window.maximize.enabled=false
behave.runner.screen.maxWait=100000 
behave.runner.screen.minWait=1000

**Comment by juliancesar** [comment]
@estivalet qual a versão que vc esta usando?

**Comment by estivalet** [comment]
1.5.1-SNAPSHOT

**Comment by juliancesar** [comment]
Tente utilizar a versão **1.5.1** e não a 1.5.1-SNAPSHOT com a propriedade **behave.parser.story.timeout**.

**Comment by estivalet** [comment]
Essa issue vou fechar pois resolveu o problema conforme a sua sugestão, mas a 370 segue com problema.
