### ISSUE TITLE
Erro ao atualizar para 1.5.1

### ISSUE THREAD

**Issue by estivalet** [demoiselle/behave#370]
Ao atualizar meu pom de:

	<parent>
		<groupId>br.gov.frameworkdemoiselle.component.behave</groupId>
		<artifactId>demoiselle-behave-parent</artifactId>
		<version>1.5.1-SNAPSHOT</version>
	</parent>

para:

         <parent>
		<groupId>br.gov.frameworkdemoiselle.component.behave</groupId>
		<artifactId>demoiselle-behave-parent</artifactId>
		<version>1.5.1</version>
	</parent>

o seguinte erro aparece:

16:14:06,193 INFO  (main) [BeforeAfterSteps]: >>Iniciando Aplicação<<
br.gov.frameworkdemoiselle.behave.parser.jbehave.BeforeAfterSteps.startStories() (FAILED)
(org.jbehave.core.failures.BeforeOrAfterFailed: Method startStories (annotated with @BeforeStories in class br.gov.frameworkdemoiselle.behave.parser.jbehave.BeforeAfterSteps) failed: java.lang.NoClassDefFoundError: org/openqa/selenium/remote/service/DriverService$Builder)

Essa classe não baixou aqui no meu repositório.

**Comment by juliancesar** [comment]
Tente criar um projeto na versão **1.5.1** a partir de um arquétipo selenium e veja se ele roda, se não rodar deve ter alguma dependência que não esta conseguindo ser baixada.

**Comment by estivalet** [comment]
Continuo com o problema. Estava dando uma pesquisada sobre essa classe e parece ser alguma coisa com o PhantomDriver que alias nem estou usando.

**Comment by juliancesar** [comment]
Estivalet, o novo projeto a partir do arquétipo não funcionou?

**Comment by estivalet** [comment]
Sim:

10:19:27,416 INFO  (main) [BehaveContext]: --------------------------------
10:19:27,416 INFO  (main) [BehaveContext]: Demoiselle Behave Iniciado
10:19:27,416 INFO  (main) [BehaveContext]: Demoiselle Behave 1.5.1 em: 12/08/2015 10:15
10:19:27,416 INFO  (main) [BehaveContext]: --------------------------------
10:19:27,436 INFO  (main) [JBehaveParser]: Configurando Parser JBehave...
10:19:27,465 INFO  (main) [JBehaveParser]: Iniciando Parser JBehave...
10:19:27,470 INFO  (main) [JBehaveParser]: Executando história: [[stories\dbehave.storyConverted]]
Processing system properties {}
Using controls EmbedderControls[batch=false,skip=false,generateViewAfterStories=true,ignoreFailureInStories=true,ignoreFailureInView=true,verboseFailures=true,verboseFiltering=false,storyTimeouts=1121600,threads=1,failOnStoryTimeout=false]

(BeforeStories)
10:19:28,055 INFO  (main) [BeforeAfterSteps]: 


10:19:28,055 INFO  (main) [BeforeAfterSteps]: >>Iniciando Aplicação<<
10:19:28,075 ERROR (main) [ScreenShootingMaker]: Erro ao salvar screenshot [] caminho [C:\Temp\proj3\proj3\target\jbehave\view\screenshots\failed-scenario-c5373847-6e34-478a-af17-bce2610c861f.png] causa [null]
10:19:28,075 ERROR (main) [ScreenShootingMaker]: java.lang.NullPointerException
br.gov.frameworkdemoiselle.behave.parser.jbehave.BeforeAfterSteps.startStories() (FAILED)
(org.jbehave.core.failures.BeforeOrAfterFailed: Method startStories (annotated with @BeforeStories in class br.gov.frameworkdemoiselle.behave.parser.jbehave.BeforeAfterSteps) failed: java.lang.NoClassDefFoundError: org/openqa/selenium/remote/service/DriverService$Builder)

Running story stories\dbehave.storyConverted
Funcionalidade: Acesso ao Projeto Demoiselle Behave
(stories\dbehave.storyConverted)
Narrative:
In order to informações sobre o projeto Demoiselle Behave
As a visistante
I want to ter acesso a documentação, fórum e demais informações sobre o projeto
Scenario: Site do DBehave
Using timeout for story dbehave.storyConverted of 1121600 secs.
10:19:29,238 ERROR (pool-1-thread-1) [ScreenShootingMaker]: Erro ao salvar screenshot [] caminho [C:\Temp\proj3\proj3\target\jbehave\view\screenshots\failed-scenario-1daacbdc-0f38-46ab-a35f-7fcd138b44d9.png] causa [null]
10:19:29,238 ERROR (pool-1-thread-1) [ScreenShootingMaker]: java.lang.NullPointerException
Dado que vou para a tela "dbehave" (FAILED)
(java.lang.NullPointerException)
Então será exibido "dbehave - projeto mantido pelo SERPRO" (NOT PERFORMED)

Scenario: Lendo dúvidas
10:19:30,286 ERROR (pool-1-thread-1) [ScreenShootingMaker]: Erro ao salvar screenshot [] caminho [C:\Temp\proj3\proj3\target\jbehave\view\screenshots\failed-scenario-f4773c24-9b50-4e63-a09c-189ff428ba8c.png] causa [null]
10:19:30,287 ERROR (pool-1-thread-1) [ScreenShootingMaker]: java.lang.NullPointerException
Dado que vou para a tela "Github" (FAILED)
(java.lang.NullPointerException)
Então será exibido "Demoiselle Behave" (NOT PERFORMED)
Então será exibido "http://dbehave.com" (NOT PERFORMED)
Quando clico em "Dúvidas e Questões" (NOT PERFORMED)
Então será exibido "New issue" (NOT PERFORMED)

Scenario: Procurando documentação
10:19:31,331 ERROR (pool-1-thread-1) [ScreenShootingMaker]: Erro ao salvar screenshot [] caminho [C:\Temp\proj3\proj3\target\jbehave\view\screenshots\failed-scenario-29be153c-e3d9-4da2-b605-3d870f05a64a.png] causa [null]
10:19:31,331 ERROR (pool-1-thread-1) [ScreenShootingMaker]: java.lang.NullPointerException
Dado que vou para a tela "Documentação" (FAILED)
(java.lang.NullPointerException)
Quando clico em "Roteiro Rápido" (NOT PERFORMED)
Então será exibido "um roteiro rápido para criação e configuração de um projeto com uso do framework Demoiselle Behave" (NOT PERFORMED)
Quando clico em "Link Principal" (NOT PERFORMED)
E clico em "Testes de Regressão" (NOT PERFORMED)
Então será exibido "a funcionalidade que permite a comparação de layout entre navegadores diferentes" (NOT PERFORMED)



(AfterStories)
10:19:31,490 ERROR (main) [ScreenShootingMaker]: Erro ao salvar screenshot [] caminho [C:\Temp\proj3\proj3\target\jbehave\view\screenshots\failed-scenario-b2037102-b150-4051-bea0-924ebf9b3ee3.png] causa [null]
10:19:31,490 ERROR (main) [ScreenShootingMaker]: java.lang.NullPointerException
br.gov.frameworkdemoiselle.behave.parser.jbehave.BeforeAfterSteps.stopStories() (FAILED)
(org.jbehave.core.failures.BeforeOrAfterFailed: Method stopStories (annotated with @AfterStories in class br.gov.frameworkdemoiselle.behave.parser.jbehave.BeforeAfterSteps) failed: java.lang.NullPointerException)

Failed to run batch 
org.jbehave.core.embedder.PerformableTree$SomethingHappened@6f9b8e: java.lang.NullPointerException
	at br.gov.frameworkdemoiselle.behave.runner.webdriver.WebDriverRunner.setDefaultWindow(WebDriverRunner.java:263)
	at br.gov.frameworkdemoiselle.behave.runner.webdriver.WebDriverRunner.navigateTo(WebDriverRunner.java:109)
	at br.gov.frameworkdemoiselle.behave.parser.jbehave.CommonSteps.goToWithName(CommonSteps.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:598)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:317)
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1012)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:902)
	at org.jbehave.core.embedder.PerformableTree$NormalPerformableScenario.perform(PerformableTree.java:930)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:853)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:781)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:758)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:390)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:364)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:291)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:265)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)

Generating reports view to 'C:\Temp\proj3\proj3\target\jbehave' using formats '[defaultstoryreport, console, html, stats]' and view properties '{navigator=ftl/jbehave-navigator.ftl, views=ftl/jbehave-views.ftl, reports=ftl/jbehave-reports.ftl, nonDecorated=ftl/jbehave-report-non-decorated.ftl, decorated=ftl/jbehave-report-decorated.ftl, maps=ftl/jbehave-maps.ftl}'
log4j:WARN No appenders could be found for logger (freemarker.cache).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Reports view generated with 2 stories (of which 0 pending) containing 3 scenarios (of which 0 pending)
Failures in reports view: 3 scenarios failed
10:19:31,794 INFO  (main) [JBehaveParser]: Finalizando Parser JBehave...
10:19:31,794 INFO  (main) [BehaveContext]: --------------------------------
10:19:31,794 INFO  (main) [BehaveContext]: Demoiselle Behave Finalizado
10:19:31,794 INFO  (main) [BehaveContext]: --------------------------------

**Comment by estivalet** [comment]
Só um detalhe para reforçar... o novo projeto funciona no Firefox a partir no arquétipo, mas quando tento usar o Chrome, não.

behave.runner.screen.type=GoogleChrome
behave.runner.screen.driverPath=c:/users/lestivalet/chromedriver.exe
behave.runner.window.maximize.enabled=false
behave.runner.screen.maxWait=100000 
behave.runner.screen.minWait=1000

behave.parser.beforeaftersteps.enabled=true
behave.parser.delayBetweenSteps=1
behave.parser.story.timeout=1121600

**Comment by juliancesar** [comment]
Com relação ao primeiro problema da atualização acredito que seja alguma questão de configuração, ou agora a sua máquina já deve ter conseguido baixar as dependências necessárias, tente rodar novamente o seu projeto e nos de um retorno.

Sobre o problema no Chrome provavelmente a versão do Driver que você está usando não é compatível com a nova versão que colocamos do WebDriver (2.46) ou até mesmo a versão do Chrome da sua maquina, veja no release notes do driver: http://chromedriver.storage.googleapis.com/2.16/notes.txt

**Comment by estivalet** [comment]
Deu o mesmo erro na maquina de um colega. Só que ele usa Ubuntu 15.04 com ultimo chrome driver e ultima versao do chrome. Deu o mesmo classnotfound. Vou atualizar o meu ambiente que é Windows para ver se o problema continua.

**Comment by juliancesar** [comment]
Não estou conseguindo identificar o problema, o ideal é depurar e ver em que ponto exatamente o erro ocorre.

**Comment by estivalet** [comment]
Forcei no meu pom.xml:

<dependencies>
	<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>2.44.0</version>
</dependency>

E daí o chrome abre e o erro não ocorre. Fiz conforme sugestão desse link: http://code.google.com/p/chromedriver/issues/detail?id=1045

**Comment by juliancesar** [comment]
Conseguiu identificar o ponto do problema que levanta a exception **NoClassDefFoundError**?

**Comment by estivalet** [comment]
Não consegui, estou numa correria aqui para automatizar uns testes até 6a feira e não vou ter tempo até lá para investigar. A solução de colocar a versão 2.44.0 do selenium direto no projeto, e não usar a 2.46.0 que vem com o framework resolve por enquanto. Como estou com pressa vai ficar assim, mas pelo que testamos aqui o erro ocorre tanto no ambiente windows 7 e Ubuntu 15 com as versões mais recentes do google chrome (45.0.2454.85) e do driver (2.18). O browser nem chega a abrir

**Comment by juliancesar** [comment]
Vou fechar esta issue, e quando precisar pode reabrir.

**Comment by RenatoEller** [comment]
Estou com o mesmo problema. Adicionei a dependência que o estivalet adicionou, mas no meu caso o erro persistiu. Estou usando a última versão do Chromedriver.

**Comment by juliancesar** [comment]
Para rodar o Google Chrome homologado pelo Serpro (Versão 34.0) as configurações devem ser as seguintes:

**1 - o arquivo do Google Driver deve ser a versão 2.10 que é o que da suporte a versão 34 do Chrome**

http://chromedriver.storage.googleapis.com/index.html?path=2.10/ - Endereço de download
http://chromedriver.storage.googleapis.com/2.10/notes.txt - Endereço do release notes que explicita as versões que o driver suporta

**2 - a dependência do WebDriver no seu projeto deve ser a segue:**

```xml
<dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-java</artifactId>
        <version>2.43.0</version>
</dependency>
```

ela deve ser adicionada, se não existir, no seu pom.xml.

**3 - o seu behave.properties deve ser configurado da seguinte maneira**

```
behave.runner.screen.type=GoogleChrome
behave.runner.screen.driverPath=//CAMINHO_DO_DRIVER//chromedriver
```

Realize os procedimentos e retorne o resultado.

**Comment by RenatoEller** [comment]
Fiz conforme acima e ocorre o seguinte erro:

09:21:53,995 INFO  (main) [BeforeAfterSteps]: >>Iniciando Aplicação<<
br.gov.frameworkdemoiselle.behave.parser.jbehave.BeforeAfterSteps.startStories() (FAILED)
(org.jbehave.core.failures.BeforeOrAfterFailed: Method startStories (annotated with @BeforeStories in class br.gov.frameworkdemoiselle.behave.parser.jbehave.BeforeAfterSteps) failed: java.lang.IllegalStateException: The driver executable does not exist: /home/03548349676/workspace/novo/TRANSFERE/01-Sistema/06-Teste/01-Dbehave/testes)
09:21:54,045 ERROR (main) [ScreenShootingMaker]: Erro ao salvar screenshot [] caminho [/home/03548349676/workspace/novo/TRANSFERE/01-Sistema/06-Teste/01-Dbehave/testes/target/jbehave/view/screenshots/failed-scenario-ca266030-27c5-4fad-b3bd-9d239947d6f4.png] causa [null]
09:21:54,045 ERROR (main) [ScreenShootingMaker]: java.lang.NullPointerException

**Comment by juliancesar** [comment]
Renato, como conversado agora pouco a propriedade deve ser informada da seguinte maneira:
```
 PropertiesLoaderUtil.getInstance().getProperties().put("NOME_DA_PROPRIEDADE", "VALOR_DA_PROP");
```

**Comment by RenatoEller** [comment]
Julian, agora funcionou.
Obrigado!
