### ISSUE TITLE
Especificação de cenários em inglês

### ISSUE THREAD

**Issue by trsilva** [demoiselle/behave#376]
Bom dia!

Tenho uma questão relativa às opções de idioma. Preciso utilizar os cenários descritos em inglês. Há alguma previsão no framework para alterar esse tipo de configuração? É possível trabalhar com os Common Steps em inglês?

**Comment by juliancesar** [comment]
Bom dia, a principio não existe impedimento para escrever os textos em outros idiomas, pois o **JBehave** que é a ferramenta que trata as histórias juntamente com algumas funcionalidades do framework dão suporte a este comportamento alterando os parâmetros descritos na documentação: 

http://demoiselle.sourceforge.net/docs/components/behave/reference/lastversion/html/behave-configuracao.html#d0e1703

Caso não consiga fazer funcionar corretamente pode reabrir a issue.

**Comment by trsilva** [comment]
OK, Julian!

Com relação aos Common Steps, há uma tradução deles em inglês ao modificar esses parâmetros de configuração? Se sim, há alguma espécie de catálogo onde possamos consultá-los?

**Comment by juliancesar** [comment]
Os passos comuns existem somente em português.

**Comment by trsilva** [comment]
Certo.

Nesse caso então preciso reescrever a classe do Common Steps para poder trabalhar com eles?

**Comment by juliancesar** [comment]
Não precisa reescrever, basta criar uma classe de steps que chamem diretamente os métodos já escritos.

**Comment by trsilva** [comment]
Julian,

alterei apenas o parâmetro idioma no behave.properties, porém ele gera corretamente o arquivo .storyConverted, mas não consegue lê-lo durante a execução.

É preciso alterar também a expressão regular que identificará um início de cenário e passo no arquivo de história?

P.S.: não consigo reabrir essa issue!

**Comment by trsilva** [comment]
Estou tentando executar, inclusive alterando a expressão regular, porém ele continua não conseguindo ler o arquivo de cenários.

Acredito que o behave.properties não esteja sendo lido, já que mesmo alterando a propriedade behave.parser.language para en, as mensagens no console de início e fim da aplicação, por exemplo, continuam em português!

**Comment by trsilva** [comment]
Alguma sugestão para esse problema, Julian?! Será que você poderia reabrir essa issue?

**Comment by juliancesar** [comment]
Mande para mim somente as linhas não comentadas do seu **behave.properties**.

**Comment by trsilva** [comment]
Descomentei somente a linha "behave.parser.language". Alterei o parâmetro para "en":

behave.parser.language=en

Em seguida, tentei descomentar também as linhas "behave.parser.identification.scenario.pattern" e "behave.parser.prefixes.bdd.pattern", traduzindo os termos da expressão regular, mas também não funcionou.

**Comment by juliancesar** [comment]
somente descomente a linha **behave.parser.language** e altere para en, não é necessário as outras e se fosse seria algo do tipo:

```
behave.parser.prefixes.bdd.pattern.en=^(\s)*(GIVEN |WHEN |THEN |AND |BUT |Given |When |Then |And |But |given |when |then |and |but )(.*)
behave.parser.identification.scenario.pattern.en=^(\s)*(SCENARIO|Scenario|scenario):(.*)
```

Favor mandar o arquivo behave.properties para verificação.

**Comment by trsilva** [comment]
# ------------------ ConfiguraÃ§Ãµes do Parser ------------------ 

# Default: pt
behave.parser.language=en

# Default: null - JBehave Default: ^(\\s)*(CEN\u00C1RIO|Cen\u00E1rio|cen\u00E1rio)\:(.*)
# behave.parser.identification.scenario.pattern=^(\\s)*(CEN\u00C1RIO|Cen\u00E1rio|cen\u00E1rio)\:(.*)

# Default: null - JBehave Default: ^(\\s)*(DADO |QUANDO |ENT\u00C3O |E |MAS |Dado |Quando |Ent\u00E3o |Mas |dado |quando |ent\u00E3o |e |mas )(.*)
# behave.parser.prefixes.bdd.pattern=^(\\s)*(DADO |QUANDO |ENT\u00C3O |E |MAS |Dado |Quando |Ent\u00E3o |Mas |dado |quando |ent\u00E3o |e |mas )(.*)

# Default: bdd - JBehave Default: bdd
# behave.parser.story.extension.original=bdd

# Default: story - JBehave Default: story
# behave.parser.story.extension.converted=story

# Default: 360 (6 horas) - Define o tempo maximo em minutos para execucao das historias
# behave.parser.story.timeout=360
	
# Default: true - JBehave Default: true | Habilita os passos comuns utilizados com o WebDriver
# behave.parser.commonssteps.enabled=true

# Default: true - JBehave Default: true | Habilita a criaÃ§Ã£o e finalizaÃ§Ã£o do Runner (BeforeStories e AfterStories)
# behave.parser.beforeaftersteps.enabled=true

# ------------------ ConfiguraÃ§Ãµes da IntegraÃ§Ã£o ALM ------------------

# Default: false
# behave.integration.alm.enabled=false
	
# Default: null | Campo obrigatÃ³rio para integraÃ§Ã£o com a ALM. EndereÃ§o completo do caminho para autenticaÃ§Ã£o na ALM
# behave.integration.alm.url.security
	
# Default: null | Campo obrigatÃ³rio para integraÃ§Ã£o com a ALM. EndereÃ§o completo do caminho para os serviÃ§os REST
# behave.integration.alm.url.services

# Default: null | Campo obrigatÃ³rio para integraÃ§Ã£o com a ALM. Alias da Ã¡rea de projeto, tomar cuidado com Ã¡reas renomeadas, pois o Alias nÃ£o Ã© alterado
# behave.integration.alm.projectArea
	
# Default: null | Campo obrigatÃ³rio para integraÃ§Ã£o com a ALM. Id do plano de testes que pertence a Ã¡rea de projeto
# behave.integration.alm.testPlanId

# Default: localhost | EndereÃ§o (IP) do Autenticator
# behave.integration.authenticator.host=localhost
	
# Default: 9990 | Porta utilizada para comunicaÃ§Ã£o com o Autenticator
# behave.integration.authenticator.port=9990

# ------------------ ConfiguraÃ§Ãµes do Runner ------------------ 

# Default: 10000 | Tempo mÃ¡ximo de espera em uma aÃ§Ã£o na tela
# behave.runner.screen.maxWait=10000

# Default: 100 | Tempo mÃ­nimo de espera em uma aÃ§Ã£o na tela
# behave.runner.screen.minWait=100

# Default: false | Ativa ou desativa o uso de proxy no navegador
# behave.runner.proxy.enabled=false
 
# Default: null | URL do proxy
# behave.runner.proxy.url

# Default: false | Ativa ou desativa o uso de profile no navegador
# behave.runner.profile.enabled=false
 
# Default: null | LocalizaÃ§Ã£o do profile
# behave.runner.screen.profilePath

# Default: null	| LocalizaÃ§Ã£o do driver que faz	ligaÃ§Ã£o	entre o navegador e o webdriver
# behave.runner.screen.driverPath
	
# Default: null - WebDriver Default: MozillaFirefox | OpÃ§Ãµes do WebDriver: MozillaFirefox, InternetExplorer, GoogleChrome, RemoteWeb. No caso do IE, RemoteWeb e Chrome sÃ£o necessÃ¡rias configuraÃ§Ãµes adicionais.
# behave.runner.screen.type=MozillaFirefox

# ConfiguraÃ§Ãµes especÃ­fica para o RemoteWeb
#Default: null | Nome do driver do selenium server | OpÃ§Ãµes: firefox, chrome, internetExplorer, safari, htmlUnit
#behave.runner.screen.remote.name=firefox

#Default: null | Url na qual encontra-se o selenium server
#behave.runner.screen.remote.url=http://127.0.0.1:4444/wd/hub

**Comment by trsilva** [comment]
# ------------------ ConfiguraÃ§Ãµes do Parser ------------------ 

# Default: pt
behave.parser.language=en

# Default: null - JBehave Default: ^(\\s)*(CEN\u00C1RIO|Cen\u00E1rio|cen\u00E1rio)\:(.*)
# behave.parser.identification.scenario.pattern=^(\\s)*(CEN\u00C1RIO|Cen\u00E1rio|cen\u00E1rio)\:(.*)

# Default: null - JBehave Default: ^(\\s)*(DADO |QUANDO |ENT\u00C3O |E |MAS |Dado |Quando |Ent\u00E3o |Mas |dado |quando |ent\u00E3o |e |mas )(.*)
# behave.parser.prefixes.bdd.pattern=^(\\s)*(DADO |QUANDO |ENT\u00C3O |E |MAS |Dado |Quando |Ent\u00E3o |Mas |dado |quando |ent\u00E3o |e |mas )(.*)

# Default: bdd - JBehave Default: bdd
# behave.parser.story.extension.original=bdd

# Default: story - JBehave Default: story
# behave.parser.story.extension.converted=story

# Default: 360 (6 horas) - Define o tempo maximo em minutos para execucao das historias
# behave.parser.story.timeout=360
	
# Default: true - JBehave Default: true | Habilita os passos comuns utilizados com o WebDriver
# behave.parser.commonssteps.enabled=true

# Default: true - JBehave Default: true | Habilita a criaÃ§Ã£o e finalizaÃ§Ã£o do Runner (BeforeStories e AfterStories)
# behave.parser.beforeaftersteps.enabled=true

# ------------------ ConfiguraÃ§Ãµes da IntegraÃ§Ã£o ALM ------------------

# Default: false
# behave.integration.alm.enabled=false
	
# Default: null | Campo obrigatÃ³rio para integraÃ§Ã£o com a ALM. EndereÃ§o completo do caminho para autenticaÃ§Ã£o na ALM
# behave.integration.alm.url.security
	
# Default: null | Campo obrigatÃ³rio para integraÃ§Ã£o com a ALM. EndereÃ§o completo do caminho para os serviÃ§os REST
# behave.integration.alm.url.services

# Default: null | Campo obrigatÃ³rio para integraÃ§Ã£o com a ALM. Alias da Ã¡rea de projeto, tomar cuidado com Ã¡reas renomeadas, pois o Alias nÃ£o Ã© alterado
# behave.integration.alm.projectArea
	
# Default: null | Campo obrigatÃ³rio para integraÃ§Ã£o com a ALM. Id do plano de testes que pertence a Ã¡rea de projeto
# behave.integration.alm.testPlanId

# Default: localhost | EndereÃ§o (IP) do Autenticator
# behave.integration.authenticator.host=localhost
	
# Default: 9990 | Porta utilizada para comunicaÃ§Ã£o com o Autenticator
# behave.integration.authenticator.port=9990

# ------------------ ConfiguraÃ§Ãµes do Runner ------------------ 

# Default: 10000 | Tempo mÃ¡ximo de espera em uma aÃ§Ã£o na tela
# behave.runner.screen.maxWait=10000

# Default: 100 | Tempo mÃ­nimo de espera em uma aÃ§Ã£o na tela
# behave.runner.screen.minWait=100

# Default: false | Ativa ou desativa o uso de proxy no navegador
# behave.runner.proxy.enabled=false
 
# Default: null | URL do proxy
# behave.runner.proxy.url

# Default: false | Ativa ou desativa o uso de profile no navegador
# behave.runner.profile.enabled=false
 
# Default: null | LocalizaÃ§Ã£o do profile
# behave.runner.screen.profilePath

# Default: null	| LocalizaÃ§Ã£o do driver que faz	ligaÃ§Ã£o	entre o navegador e o webdriver
# behave.runner.screen.driverPath
	
# Default: null - WebDriver Default: MozillaFirefox | OpÃ§Ãµes do WebDriver: MozillaFirefox, InternetExplorer, GoogleChrome, RemoteWeb. No caso do IE, RemoteWeb e Chrome sÃ£o necessÃ¡rias configuraÃ§Ãµes adicionais.
# behave.runner.screen.type=MozillaFirefox

# ConfiguraÃ§Ãµes especÃ­fica para o RemoteWeb
#Default: null | Nome do driver do selenium server | OpÃ§Ãµes: firefox, chrome, internetExplorer, safari, htmlUnit
#behave.runner.screen.remote.name=firefox

#Default: null | Url na qual encontra-se o selenium server
#behave.runner.screen.remote.url=http://127.0.0.1:4444/wd/hub

**Comment by juliancesar** [comment]
@trsilva, fiz o seguinte processo:

1 - Criei um projeto do zero com o arquétipo jbehave-selenium do behave
2 - Alterei o arquivo dbeaveh.story com o seguinte conteúdo

```bdd
Scenario: Site do DBehave

Given teste julian
When teste maria
Then teste joão
```

3 - Alterei o behave.properties para **behave.parser.language=en**
4 - Alterei a versão do dbeaveh do **pom.xml** de 1.5.1 para 1.5.2-SNAPSHOT
5 - Rodei o teste

A saída do console continha o seguinte trecho:

```Java
Running story stories/dbehave.storyConverted

(stories/dbehave.storyConverted)
Scenario: Site do DBehave
Given teste julian (PENDING)
When teste maria (PENDING)
Then teste joão (PENDING)
@Given("teste julian")
@Pending
public void givenTesteJulian() {
  // PENDING
}

@When("teste maria")
@Pending
public void whenTesteMaria() {
  // PENDING
}

@Then("teste jo\u00E3o")
@Pending
public void thenTesteJoão() {
  // PENDING
}
```

Ou seja, ele identificou a linguagem.

Você poderia fazer o mesmo procedimento e retornar o resultado?

**Comment by juliancesar** [comment]
Peço que faça o teste agora, mas estou publicando uma nova versão SNAPSHOT que pode afetar esta questão, acredito que até o final da tarde esteja publicada (1.5.2-SNAPSHOT).

**Comment by trsilva** [comment]
Acabei de rodar o teu exemplo, Julian. Tanto com a versão 1.5.1 quanto com a versão 1.5.2-SNAPSHOT, o resultado é o mesmo:

Running story stories/dbehave.storyConverted

(stories/dbehave.storyConverted)
Scenario: 


Que é exatamente o mesmo resultado que eu obtive rodando o projeto de testes da minha aplicação. Ele não consegue identificar a linguagem.

**Comment by trsilva** [comment]
Devo aguardar e tentar novamente mais tarde com a versão 1.5.2-SNAPSHOT?

**Comment by juliancesar** [comment]
Assim que a nova publicação da **1.5.2-SNAPSHOT** estiver pronta eu aviso.

**Comment by trsilva** [comment]
OK, vou aguardar. Obrigado!

**Comment by juliancesar** [comment]
Favor testar.

**Comment by trsilva** [comment]
OK, Julian. Obrigado, agora funcionou! De fato, é um bug na versão 1.5.1 então?

**Comment by trsilva** [comment]
Julian,

uma questão: ao modificar o parâmetro para inglês, o framework não deveria pegar as mensagens de "demoiselle-parser-jbehave-bundle_en.properties" ao invés de "demoiselle-parser-jbehave-bundle_pt.properties"? As mensagens de execução no console continuam sendo exibidas em português.

**Comment by juliancesar** [comment]
Para as mensagens do framework é necessário alterar a propriedade **behave.message.locale=en**.
