### ISSUE TITLE
problemas com o google chrome portable

### ISSUE THREAD

**Issue by estivalet** [demoiselle/behave#377]
alguém já rodou testes com o chrome portable?

Configurei o properties para rodar o portable, e não está funcionando, o teste continua pegando o chrome padrão instalado na minha máquina e não o especificado pela propriedade binaryPath.

behave.runner.screen.type=GoogleChrome
behave.runner.screen.binaryPath=C:\\Users\\lestivalet\\Downloads\\GoogleChromePortable\\GoogleChromePortable.exe

Estou tentando contornar o problema relatado na issue #374

**Comment by juliancesar** [comment]
Esta issue ainda é pertinente?

**Comment by estivalet** [comment]
O único detalhe que ficou é que ao rodar os testes com Chrome portable o framework não fecha o browser ao final da execução. Agora que a issue #374 foi resolvida eu não preciso usar mais o chrome portable, portanto vou fechar.
