### ISSUE TITLE
Execução de estórias não listadas para executar

### ISSUE THREAD

**Issue by estivalet** [demoiselle/behave#381]
Quero somente que as estórias contidas nos arquivos abaixo sejam executadas, mas aparentemente o framework está tentando rodar todos os *.story que tenho pois ele rodou cenários do arquivo usuario.story  que nem foram listados para rodar. 

Esse comportamento eu percebi pois rodei apenas o teste abaixo e o relatório ficou inconsistente (ver telas)

```
public class ComprasDiretasTest {

    private BehaveContext eng = BehaveContext.getInstance();

    Logger log = Logger.getLogger(ComprasDiretasTest.class);

    public ComprasDiretasTest() {
        eng.addSteps(new MySteps());
    }

    @Test
    public void testRequisicoes() throws Throwable {
        eng.addStories("/stories/common.story");
        eng.addStories("/stories/login.story");
        eng.addStories("/stories/compras_diretas.story");
        eng.run();
    }

}
```
![rel1](https://cloud.githubusercontent.com/assets/4981831/11278690/80a15ac6-8ed3-11e5-8fc3-3b15c677ce50.png)

![rel2](https://cloud.githubusercontent.com/assets/4981831/11278689/809faf28-8ed3-11e5-889e-4b21385cbc22.png)

![rel3](https://cloud.githubusercontent.com/assets/4981831/11278688/809e0678-8ed3-11e5-94de-cc08cd71a740.png)

**Comment by estivalet** [comment]
Olhando o relatório acima, veja que "Usuarios" (6 falharam), "Requisicoes" (3 com sucesso) e "Contratos"  (1 com sucesso) nem foram chamados por mim. Note também que a duração deles foi 00:00:00.000.

Eu só chamei um cenário que faz o login na aplicação que estou testando e um cenário do módulo de "Compras Diretas". Ambos os cenários passaram e estão refletindo corretamente no relatório (inclusive o tempo de execução dos mesmos).

O que não consigo entender é como que cenários de Usuário, Requisições e Contratos foram chamados. Eles estão em arquivos .story separados.

**Comment by juliancesar** [comment]
Estivalet, este comportamento é normal, pois o relatório gerado pelo JBehave é incremental, ou seja, ele não gera um novo a cada vez que você rodar, portanto quando aparecem histórias antigas não quer dizer necessariamente que ele executou na última vez que você rodou, o que provavelmente aconteceu no seu caso é que em algum momento você já rodou todos os cenários e eles deram erro.

Tendo mais alguma dúvida pode reabrir a issue.

**Comment by estivalet** [comment]
@juliancesar Apaguei o diretório target/jbehave e agora o relatório está de acordo com os testes que eu rodei.

Será que o framework poderia ter uma opção para limpar esses logs antigos de execução? Não sei se faz muito sentido ficar acumulando os resultados dos testes antigos. Pelo menos para o meu caso não.
