### ISSUE TITLE
Execução da instrução "então será exibido ''" é muito lenta

### ISSUE THREAD

**Issue by camilalbmaia** [demoiselle/behave#382]
Usamos o Demoiselle Behave em vários projetos, mas em dois deles achamos muito estranho o fato de a instrução "então será exibido ''" demorar absurdamente para ser executada. Na maioria dos projetos, esta instrução demora no máximo 3 segundos, enquanto nesses dois projetos específicos a instrução demora de 30 a 40 segundos para ser executada. 

Quando há cenários com várias dessas instruções, o Demoiselle Behave simplesmente "se perde", e diz que a janela do browser foi fechada (tela não mais acessível), mas a mesma continua aberta. 

Um colega investigou esses casos e descobriu que essa demora estava ocorrendo devido a campos combobox que possuíam muitos valores (código fonte da página muito grande). Um exemplo de tela tem dois combos, e cada um deles tem como valores todos os países. Quando ele diminuiu a quantidade de valores dos campos combobox, a instrução passou a ser executada na velocidade considerada normal.

Sugiro investigar e verificar como é possível melhorar o código de modo a atender projetos que possuam essa característica, até porque nem sempre temos controle sobre a base de dados, por isso não podemos diminuir os valores para que o teste seja executado. Desses dois projetos citados, apenas um pôde ter os valores diminuídos.

**Comment by ttperes** [comment]
Você teria um exemplo deste HTML pra usar como base para verificar o desempenho?

**Comment by ttperes** [comment]
@camilalbmaia , @juliancesar Acho que encontrei uma solução para otimizar muito esse método. Você tem este exemplo que causa lentidão para eu fazer um teste?

**Comment by joaquimpedrooliveira** [comment]
@juliancesar , alguma novidade em relação a este problema? A correção do @ttperes foi liberada em algum snapshot?

**Comment by juliancesar** [comment]
Olá @joaquimpedrooliveira, não temos previsão a correção sair em uma SNAPSHOT pois ainda é necessário testar em alguns projetos reais com o objetivo de verificar a retrocompatibilidade.

**Comment by juliancesar** [comment]
@camilalbmaia e @joaquimpedrooliveira, você poderiam confirmar para mim que se a lentidão ainda esta ocorrendo e se é em um sistema que tenha FRAME/IFRAME?

Obrigado e aguardo.

**Comment by camilalbmaia** [comment]
Vou testar na versão 1.5.2 beta1 e retorno.

**Comment by camilalbmaia** [comment]
@juliancesar, o problema foi resolvido na versão 1.5.2-BETA1.

**Comment by juliancesar** [comment]
Que bom! Ainda vou manter a issue aberta pois a BETA2 ainda conterá modificações nesta questão e pode ser que outros problemas surjam.

**Comment by juliancesar** [comment]
Favor testar com a BETA2.

**Comment by juliancesar** [comment]
Favor testar o comportamento na **1.5.2-BETA3**.

Se for possível teste ainda esta semana, pois na segunda, dia 12/11, lançaremos a versão final e caso exista algum problema podemos resolver antes do lançamento.

Obrigado pela colaboração.

**Comment by camilalbmaia** [comment]
@juliancesar O problema voltou a acontecer na versão 1.5.2-BETA3. A instrução "então será exibido" demora cerca de 40 segundos para executar.

**Comment by juliancesar** [comment]
@camilalbmaia, a aplicação possuir frames ou iframes?

**Comment by juliancesar** [comment]
Ao rodas os testes é importante ter certeza que este usando a versão correta, é possível verificar isso verificando o log no início do teste, tem que ter algo como o trecho abaixo:

```
12:24:55,409 INFO  (main) [BehaveContext]: --------------------------------
12:24:55,409 INFO  (main) [BehaveContext]: Demoiselle Behave Iniciado
12:24:55,409 INFO  (main) [BehaveContext]: Demoiselle Behave 1.5.2-BETA3 em: 06/12/2016 13:48
12:24:55,409 INFO  (main) [BehaveContext]: --------------------------------

```

Fiz vários testes aqui em modo debug nos nossos exemplos com/sem frames e tudo foi bem rápido como mostra o log abaixo (com frames que é o caso mais demorado):

```
Dado que vou para a tela "Teste de Frame"
Então não será exibido "Texto que não existe"
12:25:03,782 DEBUG (pool-1-thread-1) [WebBase]: O tamanho do texto analizado é de [0]
12:25:03,815 DEBUG (pool-1-thread-1) [WebBase]: O tamanho do texto analizado é de [4]
Então será exibido "Topo"
12:25:04,059 DEBUG (pool-1-thread-1) [WebBase]: O tamanho do texto analizado é de [0]
12:25:04,085 DEBUG (pool-1-thread-1) [WebBase]: O tamanho do texto analizado é de [4]
12:25:04,113 DEBUG (pool-1-thread-1) [WebBase]: O tamanho do texto analizado é de [0]
12:25:04,156 DEBUG (pool-1-thread-1) [WebBase]: O tamanho do texto analizado é de [33]
Então será exibido "Menu"
12:25:04,447 DEBUG (pool-1-thread-1) [WebBase]: O tamanho do texto analizado é de [0]
12:25:04,522 DEBUG (pool-1-thread-1) [WebBase]: O tamanho do texto analizado é de [4]
12:25:04,554 DEBUG (pool-1-thread-1) [WebBase]: O tamanho do texto analizado é de [0]
12:25:04,628 DEBUG (pool-1-thread-1) [WebBase]: O tamanho do texto analizado é de [33]
12:25:04,666 DEBUG (pool-1-thread-1) [WebBase]: O tamanho do texto analizado é de [18]
12:25:04,697 DEBUG (pool-1-thread-1) [WebBase]: O tamanho do texto analizado é de [6]
Então será exibido "Rodape"
12:25:04,972 DEBUG (pool-1-thread-1) [WebBase]: O tamanho do texto analizado é de [0]
12:25:05,007 DEBUG (pool-1-thread-1) [WebBase]: O tamanho do texto analizado é de [4]
12:25:05,038 DEBUG (pool-1-thread-1) [WebBase]: O tamanho do texto analizado é de [0]
12:25:05,078 DEBUG (pool-1-thread-1) [WebBase]: O tamanho do texto analizado é de [33]
12:25:05,108 DEBUG (pool-1-thread-1) [WebBase]: O tamanho do texto analizado é de [18]
Então será exibido "Sitema de Produtos"
Quando clico em "Carros"
12:25:12,446 DEBUG (pool-1-thread-1) [WebBase]: O tamanho do texto analizado é de [0]
12:25:12,497 DEBUG (pool-1-thread-1) [WebBase]: O tamanho do texto analizado é de [4]
12:25:12,526 DEBUG (pool-1-thread-1) [WebBase]: O tamanho do texto analizado é de [0]
12:25:12,569 DEBUG (pool-1-thread-1) [WebBase]: O tamanho do texto analizado é de [33]
12:25:12,606 DEBUG (pool-1-thread-1) [WebBase]: O tamanho do texto analizado é de [39]
Então será exibido "Carro 1"
```

**Comment by camilalbmaia** [comment]
@juliancesar Não tem frames, mas tem dois combobox que possuem todos os aeroportos do mundo (muitos dados). Me certifiquei a versão utilizada, e é a correta.

**Comment by juliancesar** [comment]
@camilalbmaia, realmente este caso de páginas muito grandes o processo é mais demorado do que na versão BETA1 pois na beta 1 ele tentava pegar de um elemento específico, sugiro que você "force" fazer a verificação somente no elemento utilizando a frase [Então] será exibido na "<nome do elemento>" o valor "<valor>" que provavelmente será bem rápido.

Se quiser coloque o projeto em modo debug e verifique os tempos que são mostrados no log.

**Comment by camilalbmaia** [comment]
@juliancesar Eu já tinha testado forçando a verificação em elementos específicos, e deu certo (tempo médio de 3 segundos). Os testes do projeto estão funcionando desta maneira atualmente. O problema é que perde-se muito tempo mapeando cada elemento da tela, diminuindo a produtividade.

**Comment by juliancesar** [comment]
@camilalbmaia, vc tem razão! realmente este é um ponto de melhoria no dbehave, contudo as soluções propostas até o momento não atenderam a todos os casos, como por exemplo a BETA1 que falhou um muitos outros testes.

Vou gerar a versão final 1.5.2 da maneira que está a 1.5.2-BETA3, mas vou deixar esta issue aberta para que possamos voltar neste assunto na 1.5.3, pois acredito que ainda podemos parar para pensar em algo melhor.

Obrigado pela sua colaboração.

**Comment by juliancesar** [comment]
Criei uma página na Wiki para irmos acompanhando o assunto, já que ele é uma questão importante que deve ser analisada com calma.

https://github.com/demoiselle/behave/wiki/Verifica%C3%A7%C3%A3o-de-Texto-em-P%C3%A1ginas

**Comment by juliancesar** [comment]
Prezados, alguma evolução no assunto? Alguém chegou a colocar em modo _debug_ e analisou os logs para verificar alguma possível melhoria?

**Comment by juliancesar** [comment]
A versão **1.5.3** foi lançada agora pouco contendo as melhorias desta issue.

O release notes esta disponível em:
http://demoiselle.sourceforge.net/docs/components/behave/reference/lastversion/html/release.html

Favor testar e caso o problema persista, favor reabrir.
