### ISSUE TITLE
Instalação do Eclipse DBehave + ALM no Windows

### ISSUE THREAD

**Issue by ThiagoNicolielo** [demoiselle/behave#386]
Pessoal,

Como vocês testam no IE?
Acredito que o ideal seria eu instalar o Eclipse com os plugins de DBehave (JBehave apenas?) e integração com ALM, baixar o projeto que desenvolvemos no Eclipse do Linux, e rodar os testes.

Seria isso?
Não encontro na Central de pacotes Serpro o eclipse, e acionei a css e me informaram que não instalam no Windows.

Como vocês fazem? Instalam manualmente? Se sim, o que é preciso, apenas o Eclipse + integrador ALM?

Ou vocês rodam manualmente, via prompt de comando?

Ou ainda, algo diferente?

Procurei no guia e aqui e não vi discussão sobre isto.
Esta issue pode acabar servindo para outros desenvolvedores que venham a se deparar com esta necessidade.

Grato.

**Comment by juliancesar** [comment]
@ThiagoNicolielo, não entendi a sua dúvida. Vamos por partes.

**Como vocês testam no IE?**

Normalmente para testar com IE é necessário ter uma máquina rodando Windows, podendo ela ser a máquina "local" ou até mesmo uma máquina remota. Em ambos os casos é necessário rodar o DBehave utilizando uma configuração específica para isso juntamente com um driver (https://code.google.com/p/selenium/wiki/InternetExplorerDriver). 

No caso de ser remoto é necessário utilizar os passos deste artigo: https://github.com/demoiselle/behave/wiki/Cria%C3%A7%C3%A3o-Ambiente-RemoteWeb

O processo de criação e execução dos testes é o mesmo de Linux.

**Não encontro na Central de pacotes Serpro o eclipse, e acionei a css e me informaram que não instalam no Windows.**

O eclipse que usamos é o mesmo do Serpro da central de pacotes, não sei como funciona no Windows, mas bastaria baixar o eclipse (com Maven) e rodar os testes.

**Como vocês fazem? Instalam manualmente? Se sim, o que é preciso, apenas o Eclipse + integrador ALM?**

Normalmente baixamos o eclipse com maven e java e rodamos o teste. Com relação ao integrador com a ALM ele só precisa do java instalado para rodar o jar do integrador.

**Ou vocês rodam manualmente, via prompt de comando?**

Dificilmente os projetos são rodados na linha de comando, na verdade eles rodam "na linha de comando" quando são executados com RemoteWeb.

**Procurei no guia e aqui e não vi discussão sobre isto.
Esta issue pode acabar servindo para outros desenvolvedores que venham a se deparar com esta necessidade.**

Realmente não consegui entender a sua necessidade, talvez uma conversa possa resolver.

**Comment by ThiagoNicolielo** [comment]
Olá Julian,
Não deixei claro no início do texto, mas a dúvida era sobre instalação do Eclipse DBehave + tudo o que for necessário no S.O. Windows, sim.

O que eu esperava era achar na central de pacotes, no Windows, o eclipse preparado para isto, como ocorre hoje no Linux.
Como não tem, perguntei para saber como fazem, pois vejo que costumam testar no IE.

Obrigado pela resposta, não era o que eu pretendia inicialmente, mas acho que vou tentar rodar remotamente, assim não preciso ficar baixando projeto dentro do eclipse lá no Windows, dentre outras coisas. Pode acabar sendo uma boa opção.

Obrigado!

**Comment by malaguti** [comment]
Eu também tenho essa necessidade. Não sei como instalar o dBehave no eclipse do Windows. Eu estou inferindo, pelo que Julian falou, que esta "instalação" não é necessária. Basta baixar o eclipse com Maven.Também estou inferindo que é só baixar o Driver do IE, instalar os plugins do ALM, e baixar o projeto a ser testado. Estou correto, ou esta faltando alguma coisa no meu checklist? Quanto ao Driver, tentei achar no link supracitado, mas "deu ruim"... Alguem tem esse driver, ou um link de download para me fornecer? Desde já grato.

**Comment by rogernobre** [comment]
O site que eu baixava era: http://www.seleniumhq.org/download/

A ultima versão que usei foi a "IEDriverServer_Win32_2.41.0" para o "IE9" no "Windows 7"

**Comment by rogernobre** [comment]
Outra coisa teve projetos que para funcionar o driver do IE tinha que está em alguma pasta do PATH do windows
