### ISSUE TITLE
Alteração do executor para testes Java desktop (atualmente é o Fest)

### ISSUE THREAD

**Issue by ahvsoares** [demoiselle/behave#396]
Haja vista que o projeto Fest foi descontinuado em 2012 ( https://groups.google.com/forum/#!msg/easytesting/bAt1nWx55FM/e3DF0bxGUf8J ) e que as alterações no código pararam em 2013, sugiro alterar o executor Fest por outro.

Felizmente há um fork ativo do Fest ( https://groups.google.com/forum/#!topic/easytesting/eV3MGDxoinM ), chamado AssertJ ( http://joel-costigliola.github.io/assertj/assertj-swing.html ).

Acho que esse é um bom candidato.

**Comment by juliancesar** [comment]
Realmente o FEST foi descontinuado, mas acreditamos que até o momento da escolha da tecnologia de manipulação de telas Swing ele era a melhor opção (2013) e é possível com certa facilidade o desenvolvimento de um novo **Runner** com esta nova ferramenta, principalmente se ela utilizou a mesma base do FEST. Caso tenha interesse em desenvolver podemos dar o suporte.

**Comment by juliancesar** [comment]
@ahvsoares, vou fechar a issue, mas caso tenha avançado no desenvolvimento pode reabrir.

**Comment by ahvsoares** [comment]
@juliancesar , você poderia reabrir essa issue?

Conseguimos fazer as alterações necessárias para trocar o Fest para o AssertJ.

Testamos em dois projetos reais e no de teste do DBehave e, aparentemente está ok.

Obrigado.
