### ISSUE TITLE
Ao atualizar para Demoiselle-behave 1.5.1 deixa de funcionar no Google Chrome 34

### ISSUE THREAD

**Issue by lucianojs** [demoiselle/behave#399]
Após atualização de um projeto para a ultima versão estável do Demoiselle-Behave, a 1.5.1, o mesmo não funciona mais no google Chrome 34.

O Chromedriver utilizado é a versão 2.9.

**Comment by lucianojs** [comment]
Verifiquei que a falha começou a ocorrer devido a adição da seguinte dependência:

<dependency>
    <groupId>com.github.detro</groupId>
    <artifactId>phantomjsdriver</artifactId>
    <version>1.2.0</version>
</dependency>

Isto fez com que a versão do componente selenium-remote-driver baixado seja a versão 2.41, sendo que os demais componentes estão utilizando a versão 2.46.

Como medida paliativa consegui sanar o problema, forçando a versão 2.46 da dependência no meu projeto:

<dependency>
	<groupId>org.seleniumhq.selenium</groupId>
	<artifactId>selenium-remote-driver</artifactId>
	<version>2.46.0</version>
</dependency>

**Comment by juliancesar** [comment]
Correção aceita. Obrigado pela contribuição.

Estará na versão **1.5.2 SNAPSHOT** ainda hoje ou na versão 1.5.2 release gerada no final do mês.

**Comment by lucianojs** [comment]
Percebi que após meu pull request o GhostDriver (PhantomJS) parou de funcionar.

Estou encaminhando uma alteração complementar para corrigir este novo bug.
