### ISSUE TITLE
Toda vez que rodo os testes, o LOG permanece mostrando "Failures in reports view: 7 scenarios failed" mesmo não existindo nenhuma falha.

### ISSUE THREAD

**Issue by mmsps** [demoiselle/behave#401]
O Log de execução dos testes automatizados está sempre mostrando "Failures in reports view: 7 scenarios failed" mesmo não existindo nenhuma falha na execução. 

[LOG_JUNIT_20160301-01.txt](https://github.com/demoiselle/behave/files/158720/LOG_JUNIT_20160301-01.txt)

**Comment by ttperes** [comment]
@mmsps 
Existe essa mensagem sim, porém ela não impacta no resultado do seu teste. Observe que o resultado do Junit ficará "verde" tudo ocorrendo corretamente.

**Comment by juliancesar** [comment]
@mmsps, este é um comportamento do JBehave (Ferramenta de BDD utilizada pelo DBehave).

Ela guarda o resultado dos testes anteriores, e enquanto não rodar novamente os testes que deram problema continuará com erro, a não ser que delete a pasta aonde são gerados os relatórios do teste.
