### ISSUE TITLE
Como configurar o Browser no "behave.properties" para não ficar exibindo mensagens de confirmação do tipo "Deseja sair ou continuar na página?"

### ISSUE THREAD

**Issue by mmsps** [demoiselle/behave#402]
Como configuro o Browser no "behave.properties" para não ficar exibindo modais do tipo "Deseja sair ou continuar na página?". Estou tendo problemas ao executar os mesmos testes no firefox e depois quando vou executar no Chrome, os scenarios emperram nestas mensagens do próprio Browser.

**Comment by ttperes** [comment]
@mmsps ,
Acontece em que browser? Firefox, chrome ou ambos? Qual é o fim da sua história de teste?

Normalmente essa frase é padrão do browser, você criando um profile próprio pra ele e salvando a opção e usando o mesmo profile na automação resolve o problema.

**Comment by mmsps** [comment]
Acontece no Chrome! No firefox o passo "E clico em "Confirmar caixa de diálogo""  funciona e confirma a caixa de diálogo mas no chrome não funciona, o behave fica parado nas telas que possuem essa caixa de confirmação.
![tela de mensagem](https://cloud.githubusercontent.com/assets/5444722/13581034/ad574caa-e483-11e5-8964-3560baeb2976.png)

**Comment by mmsps** [comment]
Vi que logo no inicio da execução o chrome exibe essa mensagem "Could not load extension from '/tmp/.com.google.Chrome.Mz7uz4/internal'. Loading of unpacked extensions is disabled by the administrator." Será essa a causa dele não estar Confirmando as telas? ví que tenho que adicionar: 

ChromeOptions options = new ChromeOptions();
options.addArguments("--disable-extensions");
driver = new ChromeDriver(options);

Porém, Onde, exatamente devo adicionar esse pedaço de código?

**Comment by juliancesar** [comment]
@mmsps, qual versão do DBehave você esta utilizando?

**Comment by juliancesar** [comment]
Pergunto isso, pois a partir do dia 17/11/2015 (https://github.com/demoiselle/behave/commit/a237125946646122d39f82a2c68951c1d3b73652) foi adicionado por padrão o **--disable-extensions** na inicilização do Chrome.

Tente rodar com a versão **1.5.2-SNAPSHOT**.

**Comment by mmsps** [comment]
Tou na versão 1.5.1, a versão 1.5.2 tá rodando sem bronca? Se eu alterar a versão você acha que ainda terei esse problema?

**Comment by juliancesar** [comment]
A principio deve funcionar. Teste e nos retorne.

**Comment by juliancesar** [comment]
Vou fechar esta issue, caso julguem necessário podem reabri-la.
