### ISSUE TITLE
É possível usar o plugin Thucydides com o dBehave?

### ISSUE THREAD

**Issue by cynarar** [demoiselle/behave#405]
Conheci o plugin [Thucydides](https://github.com/thucydides-webtests/thucydides-jbehave) que apresenta relatórios interessantes sobre os testes automatizados. Gostaria de usar, mas não sei se é possível sua integração com o dBehave, já que ele é totalmente modificado. Vocês conhecem alguma equipe que use?

**Comment by juliancesar** [comment]
@cynarar, você conseguiu avançar no assunto?

**Comment by juliancesar** [comment]
Issue fechada por falta de retorno, caso necessário favor reabrir.
