### ISSUE TITLE
Alternativas para automação desktop

### ISSUE THREAD

**Issue by estivalet** [demoiselle/behave#406]
Pessoal, quem tem experiência em automação desktop? Vamos substituir o FEST por outro framework? Atualmente tenho uma demanda para automatizar um sistema em Delphi e nem o FEST e nem o AssertJ serviriam. Por esse motivo estou procurando alternativas. Atualmente estou testando o AutoHotKey, o código está seguindo o modelo abaixo.

Será que existe a possibilidade de integrar isso ao dbehave.

```
ppp := new PaginaPrincipalPage(false)
ppp.acionarMenuConfiguracao()

class PaginaPrincipalPage {
	__New(configurar) {
	   ; QUANDO executo o AUD
	   Run, C:\Software\PJE\AUD3\aud3.exe
	   
	   if(configurar) {
			WinWaitActive, ^Confirma
			ControlClick, TButton2
	   } else {
		  ; ENTÃO aguardo a tela "Principal do AUD"
   		  WinWaitActive, ^AUD - Vers
	   }
	}
	
    selecionarMenuAudiencia() {
		; QUANDO clico no menu "Audiência"
		MouseClick, left, 46, 36
    }
}
```

**Comment by juliancesar** [comment]
@estivalet, retomando esta assunto...

Me parece que a integração com o AutoHotKey será muito complexa, pois ele não é escrito em Java e não possui alguma API ou algo que possamos chamar ele. Talvez o caminho seja gerar scripts compatíveis com a ferramenta e depois chamar ela.

Você conseguiu enxergar ma maneira de integrar a ferramenta ao DBehave?

**Comment by estivalet** [comment]
@juliancesar Não, estou fazendo a automação sem DBehave.
