### ISSUE TITLE
Geração de relatórios no formato XML também

### ISSUE THREAD

**Issue by psgrigoletti** [demoiselle/behave#407]
Pessoal,
Existe alguma forma de configurar o DBEHAVE para gerar relatórios no formato XML, além do HTML e o STAT? Ou é preciso ajustar o br.gov.frameworkdemoiselle.behave.parser.jbehave?
Obrigado

**Comment by juliancesar** [comment]
Olá @psgrigoletti , hoje o dbehave por padrão não faz a exportação em XML, mas é possível criar um novo parser com base no atual e alterar a seguinte linha adicionando o XML.

https://github.com/demoiselle/behave/blob/master/impl/parser/jbehave/src/main/java/br/gov/frameworkdemoiselle/behave/parser/jbehave/JBehaveParser.java#L224

**Comment by psgrigoletti** [comment]
Olá @juliancesar, blz?

Nossa necessidade de gerar XML veio do interesse em integrar o DBehave com um plugin do Jenkins que faz a leitura do XML. Para testar, acabei compilando a versão 1.5.1 e alterando apenas a linha 

https://github.com/demoiselle/behave/blob/master/impl/parser/jbehave/src/main/java/br/gov/frameworkdemoiselle/behave/parser/jbehave/JBehaveParser.java#L112

para gerar os formatos STAT, XML e HTML. Instalamos essa versão compilda no repositório local do maven.

**Comment by psgrigoletti** [comment]
O interessante seria configurar o tipo de saída no arquivo de propriedades.
Além disso, pelo que pude ver no código, atualmente não é possível gerar o relatório JBehave e ALM juntos... é um ou outro... seria legal poder gerar as duas saídas na mesma bateria de testes.

**Comment by juliancesar** [comment]
Acabo de gerar uma SNAPSHOT (versão 1.5.2-SNAPSHOT) que contém a modificação solicitada.

*Demoiselle Behave 1.5.2-SNAPSHOT em: 22/08/2016 11:00*

Vou fechar a issue, caso exista algum outro problema relacionado favor reabri-la.
