### ISSUE TITLE
Falhar cenário quando um passo não for encontrado(PENDETE)

### ISSUE THREAD

**Issue by marcosbrolini** [demoiselle/behave#409]
O Demoiselle behave quando não encontra um passo, lança no console:
@Given("seleciono dados Responsavel pela Solicitacao")
@Pending
public void givenSelecionoDadosResponsavelPelaSolicitacao() {
  // PENDENTE
}

Porém não falha o cenário.
Seria importante que ele gerasse uma exceção.
No Junit o cenário ficou verde, porém no log estava como pendente.

**Comment by juliancesar** [comment]
Acredito que esta issue tenha sido resolvida com o Pull Request do @delmarfilho que foi incorporada ao código principal do DBehave.

Vou fechar a issue e caso o problema persista favor reabri-la.

@delmarfilho, obrigado pela colaboração.
