### ISSUE TITLE
Permitir desabilitar screenshot

### ISSUE THREAD

**Issue by marcosbrolini** [demoiselle/behave#410]
Estou usando o Demoiselle Behave para a execução de testes rest.
E estou usando a propriedade "behave.runner.screen.type=HtmlUnit" para que não seja aberto o browser, porém quando um teste falha o demoisselle behave tenta realizar o screenshot, e acaba gerando um erro do demoiselle behave, pois não tem browser rodando.

Sugestão: adicionar propertie que permita desabilitar a geração de screenshot.

**Comment by juliancesar** [comment]
@delmarfilho, esta issue será fechada pois o Pull Request esta feito e as alterações já estão disponíveis na versão **1.5.2-SNAPSHOT**.

Se existir algum problema nos avise e reabrimos a issue.

Muito obrigado pela sua colaboração.
