### ISSUE TITLE
Maven - Atualização de Framework Demoiselle

### ISSUE THREAD

**Issue by demismeneghetti** [demoiselle/behave#414]
Senhores, 

Atualmente o repositório do Maven está com as dependências do Selenium desatualizadas e apresentando erro ao executar o Firefox. 

A versão 2.53 do Selenium já corrige o erro, é possível realizar essa atualização?

Framework Demoiselle
http://demoiselle.sourceforge.net/repository/archetype-catalog.xml

Obrigado.

**Comment by juliancesar** [comment]
@demismeneghetti, você pode fazer a atualização das dependências Maven direto no seu projeto, a principio deixamos a versão do Selenium compatível com os navegadores utilizados/homologados dentro do SERPRO (Empresa patrocinadora), mas podemos planejar a atualização para uma versão futura sim.

**Comment by demismeneghetti** [comment]
@juliancesar, obrigado pelo retorno, mas sou novato em Java e não soube fazer essa atualização no pom.xlm devido não haver as dependências descritas no arquivo. De qualquer forma, agradeço a atenção! Abraço!

**Comment by juliancesar** [comment]
@demismeneghetti, precisa de mais algum auxilio ou eu posso fechar a issue?

**Comment by demismeneghetti** [comment]
Não Julian, obrigado!

*Demis Meneghetti*
*LinkedIn:* br.linkedin.com/in/demismeneghetti
*GitHub:* github.com/demismeneghetti
*E-mail:* demismeneghetti@gmail.com
*Skype:* demismeneghetti
+55 11 98201-6004



2016-08-15 9:33 GMT-03:00 Julian Cesar <notifications@github.com>:
