### ISSUE TITLE
É possível paralelisar a execução de cenários de teste ?

### ISSUE THREAD

**Issue by joaopaulosc** [demoiselle/behave#416]
Olá, alguém sabe se é possível paralelisar a execução dos cenários de teste? Por exemplo, pra um total de 100 cenários, executar duas threads em paralelo contendo cada uma 50 cenários.

**Comment by juliancesar** [comment]
Olá @joaopaulosc, segue a documentação sobre o assunto:

http://demoiselle.sourceforge.net/docs/components/behave/reference/lastversion/html/behave-execucao.html#d0e2158

Caso exista alguma outra dúvida, favor reabrir a issue.
