### ISSUE TITLE
Comandos de story que não foram incorporados no dBehave.

### ISSUE THREAD

**Issue by malaguti** [demoiselle/behave#421]
Caros colegas. Precisamos urgentemente colocar em produção novas versões do dBehave. Caso contrário as implementações casuais, e localizadas, vão transformar o dBehave em várias ferramentas diferentes, cada uma em um polo de desenvolvimento. Estou me deparando com várias instruções de story que não tem documentação alguma no github, e que estão apenas parcialmente implementadas, exclusivamente para suprir um deficiência pontual. Tenho uma instrução que deixou de funcionar, apenas porque o mapeamento da tela que ela suportava mudou. O grupo precisa pegar todas estas instruções que estão perifericamente, e precariamente implementadas, terminar a sua implementação, e introduzir em uma nova versão, sob o risco de inviabilizar o uso de tão boa ferramenta.

**Comment by juliancesar** [comment]
@malaguti, entendo as suas colocações e são pertinentes.

Neste momento estamos passando por uma reestruturação em nossa área e estamos realinhando vários aspectos. Pretendo colocar a suas colocações nas reuniões para que possamos melhorar a ferramenta.

Um ponto interessante é que ainda não encontramos a maneira ideal para trabalhar com relação as frases/implementações que são utilizadas pelos projetos, pois hoje entendemos que as frases que "sobem" para o *core* do framework são apenas as que são genéricas o suficiente para serem utilizadas por qualquer projeto de testes, e as que são muito específicas devem ficar no projeto de testes do sistema, e por isso hoje essas implementações estão no local correto ou a equipe teria que ter um esforço para submeter a contribuição para a comunidade, podemos pensar em alguma melhoria neste sentido. 

É importante levar em consideração que o framework foi pensado de uma maneira que permitisse essas situações de especificidades, pois caso não fosse desta maneira os projetos de testes ficariam impedidos de avançar em cada problema pontual que encontrasse, existindo a necessidade de uma intervenção da equipe que mantem.

Sobre a falta de documentação e das implementações específicas acredito que a comunidade possa nos ajudar nisso com contribuições nestes sentidos, e caso acredite que possa ajudar podemos fazer um treinamento rápido para isso, que consiste basicamente em fazer o Pull Request no Github.

**Comment by malaguti** [comment]
@juliancesar. O meu entender é que toda, e qualquer implementação de frases, que não sejam redundantes,  são contribuições que vão facilitar a vida de quem, mesmo que eventualmente, vá precisar dela. O que não é legal é que elas sejam precariamente implementadas, e que tenham uma abordagem localizada.

No meu entender, um set único de instruções/frases (muito bem documentadas, é claro) dentro da empresa, é fundamental para que seja possível que outros colegas não tenham que aprender um "segundo dBehave", quando um sistema migrar de uma regional para outra. E você sabe que isso cansa de acontecer. Razão pela qual eu acredito que toda e qualquer implementação tenha que passar pelo processo do github, antes de ser posta em produção.

De todas as "novas" instruções com as quais eu me deparei, a frase "Então obtenho" é a frase que mais me faz falta, seguida de perto da instrução "caso aconteça".

Sim. São instruções com as quais eu lido aqui na regional RJ. "Então obtenho" é uma frase fantástica, mas ainda não pode ser usada com TextField. Eu acredito que a sua implementação mais breve possível se faz necessária. A frase "caso aconteça" é uma idéia genial do Leandro. O primeiro IF do dBehave, que veio, inicialmente, para fechar box de avisos, caso ele ocorra, mas que deveria ter sua implementação voltada para as demais possibilidades de se resolver problemas com um IF.

Enfim: Estou lidando com o dBehave agora, e estou gostando muito da ferramenta. Espero que essas necessidades que eu identifiquei, e que não devem ser só minhas, e as soluções citadas, sejam avaliadas pelo grupo, para uma evolução do dBehave.

Desde já agradeço pela consideração.

**Comment by juliancesar** [comment]
@malaguti, acredito que todas as suas considerações são válidas, e o GitHub permite que sejam feitas Requisições de Alteração (Pull Request), e sempre peço que os colegas que entenderem que as suas frases sejam de utilidade para todos façam a requisição para incorporar no framework. 

Uma estratégia que a regional de Florianópolias estava adotando é criar um projeto pai para os projetos de teste de um mesmo sistema, talvez possamos difundir mais esta técnica.

Infelizmente não tenho condições de analisar todas as situações a serem incorporadas.

Vou fechar esta issue, mas pretendo retomar este assunto o quanto antes em outra oportunidade.

Obrigado pela contribuição.
