### ISSUE TITLE
Erro de sessão nula ao usar perfil do firefox

### ISSUE THREAD

**Issue by wagnerwrc** [demoiselle/behave#422]
Pessoal,

Meus testes estavam quebrando por conta de um diálogo intermitente do browser ao cancelar uma operação ou lançar uma nova url ("Deseja mesmo sair da página? Informações não salvas podem ser perdidas."). Descobri que isso é controlado através da diretiva "dom.disable_beforeunload" do browser Firefox e para garantir que essa diretiva seria carregada no perfil do browser invocado pela execução automática do Behave através do Jenkins:

- Copiei toda a pasta do profile do firefox para dentro do projeto de testes
- Adicionei a diretiva "dom.disable_beforeunload" com valor "true" ao arquivo prefs.js do firefox (o equivalente a digitar o comando about:config no browser e setar essa diretiva para true.
- Setei o valor true para a propriedade behave.runner.profile.enabled do behave.properties
- Atualizei o caminho do profile Firefox na propriedade behave.runner.screen.profilePath no behave.properties

Isso funcionou. O diálogo não foi mais exibido e os testes não foram mais impactados.
Contudo, um efeito colateral passou a se apresentar. Algumas baterias rodam com 100% de aprovação e outras apresentam o seguinte erro intermitente: "Session ID is null. Using WebDriver after calling quit()?". Aparentemente, é como se ao tentar rodar determinado teste, ele perca a sessão do browser e após algum tempo, a sessão é novamente recuperada e outros testes da suite são executados normalmente.

Perguntas: 

1. Existe alguma forma de contornar esse efeito colateral?
2. Existe uma forma mais elegante de resolver o problema original (adicionar preferências ao browser que será invocado pelo Behave)?
3. Como executar os testes em browser distintos do Firefox? A solução seria apenas apontar para o binário do browser na propriedade behave.runner.screen.binaryPath? Pergunto isso, pois dessa maneira, não seria possível rodar ao mesmo tempo em múltiplos browsers. Apenas um poderia ser escolhido por vez.

Segue abaixo o stacktrace do erro da sessão nula:

(AfterStories)
04:30:26,736 ERROR (pool-6-thread-1) [ScreenShootingMaker]: Erro ao salvar screenshot [] caminho [/opt/programas/jenkins/workspace/DERCE/DE414/PEN/QualiEmpresa/pen-quali-executa-teste-automatizado/PEN/01-Sistema/06-Teste/Automatizados/automated-tests/target/jbehave/view/screenshots/failed-scenario-e964aba2-2987-4cbf-a68a-50780dc2c92e.png] causa [Session ID is null. Using WebDriver after calling quit()?
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'N/A', ip: 'N/A', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-431.17.1.el6.x86_64', java.version: '1.7.0_76'
Driver info: driver.version: RemoteWebDriver]
04:30:26,740 ERROR (pool-6-thread-1) [ScreenShootingMaker]: org.openqa.selenium.remote.SessionNotFoundException: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'N/A', ip: 'N/A', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-431.17.1.el6.x86_64', java.version: '1.7.0_76'
Driver info: driver.version: RemoteWebDriver
Dado que vou para a tela "Manter Solicitação de Produtos Financeiros" (FAILED)
(br.gov.frameworkdemoiselle.behave.exception.BehaveException: Erro ao tentar navegar para [http://penta-tes07377.apps.dev.serpro/pen-web/manterSolicitacaoProdutosFinanceiros.jsf])

Grato antecipadamente,

**Comment by juliancesar** [comment]
@wagnerwrc, ainda não consegui simular o problema do Session ID, mas encontrei algumas pistas de solução nos seguinte links:

- http://stackoverflow.com/questions/27497875/selenium-grid-running-tests-in-parallel
- http://stackoverflow.com/questions/11674254/selenium-webdriver-sessionid-or-check-if-all-browser-windows-are-closed

Sobre as perguntas:

1. Como comentei acima, provavelmente existe alguma solução, mas precisamos analisar com mais detalhes o problema, e pelo que entendi o seu teste esta sendo executado pelo jenkins e provavelmente na máquina separada da que executa o teste com navegador e neste caso existem outros problemas que podem ocorrer, principalmente relacionados a rede (alta latência, perda de pacotes, perda temporária de conexão)
2. a principio a melhor maneira de contornar o problema é como você esta fazendo, que consiste na criação de um profile do navegador
3. o dbehave foi projetado inicialmente para a execução de uma navegador por vez (podendo ser executadas várias threads simultâneas http://demoiselle.sourceforge.net/docs/components/behave/reference/lastversion/html/behave-execucao.html#d0e2158), no caso de vários navegadores o ideal é criar um projeto jenkins para cada navegador, utilizando variáveis do maven para selecionar o navegador dentro do behave.properties. Outra solução que poderia ajudar é a utilização da funcionalidade de **Testes de Regressão de Layout** ou até mesmo algumas das ideias implementadas nela, que a principio atendem a sua necessidade.

http://demoiselle.sourceforge.net/docs/components/behave/reference/lastversion/html/behave-regression.html

**Comment by juliancesar** [comment]
@wagnerwrc, conseguiu avançar?

**Comment by juliancesar** [comment]
@wagnerwrc, acredito que a última versão SNAPSHOT (Demoiselle Behave 1.5.2-SNAPSHOT em: 22/08/2016 11:00) contenha uma alteração (https://github.com/demoiselle/behave/pull/415) que possa ajudar você neste sentido, sendo que agora é possível informar o profile do navegador Firefox para execuções remotas.

Vou fechar a issue e caso o problema persista favor reabri-la.
