### ISSUE TITLE
Implementando testes em projeto desktop já existente.

### ISSUE THREAD

**Issue by lucasseveriano** [demoiselle/behave#423]
Olá a todos! 
Tenho um projeto java desenvolvido para desktop, gostaria de implementar os tetes utilizando o Demoiselle Behave. Consegui criar um projeto novo utilizando FEST, porém não sei como iniciar os testes de um projeto desktop já existente. 
Alguém poderia indicar alguma referência para que eu possa seguir um passo a passo? 

Desde já agradeço!

**Comment by juliancesar** [comment]
Olá @lucasseveriano, os 3 principais locais para encontrar essas informações são:

1. Documentação do projeto: http://demoiselle.sourceforge.net/docs/components/behave/reference/lastversion/html/desktop.html
2. Slides de treinamento do DBehave (www.dbehave.com), o ideal é fazer desde o módulo 1, mas a parte que trata de Desktop é a 3: http://pt.slideshare.net/vandersonsilva9615/demoiselle-behave-parte-3
3. Exemplo de utilização em um projeto de exemplo: https://github.com/demoiselle/behave/tree/master/sample/treino-desktop

A partir destes materiais se ainda restarem dúvidas favor reabrir a issue.
