### ISSUE TITLE
Permitir passagem de argumentos de linha de comando para o binário

### ISSUE THREAD

**Issue by otmarjr** [demoiselle/behave#428]
Pessoal,
Estou tentando executar o chrome com a opção de --no-sandbox ( no meu computador, só funciona com este argumento), mas não encontrei opção para permitir que este argumento seja passado. Pelo que vi da classe WebBrowser.java, parece que é construído um novo objeto ChromeOptions que apenas inicializa o chrome sem extensões. Como eu poderia passar mais argumentos de linha de comando? Mesmo criando um executável para envelopar o argumento (criei um executável chrome-44 que chama o google-chrome --no-sandbox), continuou sem funcionar.

**Comment by juliancesar** [comment]
@otmarjr, você conseguiu avançar na questão ou ainda precisa de suporte?

**Comment by otmarjr** [comment]
Não consegui avançar não, ainda gostaria de uma solução.

**Comment by juliancesar** [comment]
Será lançada na **BETA2** a seguinte propriedade a ser inserida no **behave.properties**:
**behave.runner.screen.commandLineOptions**: permite passar os parâmetros de inicialização do navegador, substituindo todos os fornecidos pelo framework. Por enquanto somente existe implementação para o Google Chrome. o valor padrão é vazio.

**Comment by juliancesar** [comment]
Hoje foi gerada uma versão **1.5.2-SNAPSHOT** (com diversas outras modificações) que contém a seguinte propriedade:

_behave.runner.screen.commandLineOptions_ : permite passar os parâmetros de inicialização do navegador, substituindo todos os fornecidos pelo framework. Por enquanto somente existe implementação para o Google Chrome. O valor padrão é vazio.

Favor testar.
