### ISSUE TITLE
Problema ao usar o Internet Explorer

### ISSUE THREAD

**Issue by Ildeberto** [demoiselle/behave#431]
Não estou conseguindo executar testes com o DBehave utilizando o InternetExplorer 9, com o driver 2.53.1.0.

Segue abaixo a configuração do behave.properties:
# Default: null - WebDriver Default: MozillaFirefox | OpÃ§Ãµes do WebDriver: MozillaFirefox, InternetExplorer, GoogleChrome, RemoteWeb. No caso do IE, RemoteWeb e Chrome sÃ£o necessÃ¡rias configuraÃ§Ãµes adicionais.

behave.runner.screen.type=InternetExplorer
# ConfiguraÃ§Ãµes especÃ­fica para o RemoteWeb
# Default: null | Nome do driver do selenium server | OpÃ§Ãµes: firefox, chrome, internetExplorer, safari, htmlUnit

behave.runner.screen.remote.name=internetExplorer
# Default: null | Url na qual encontra-se o selenium server

behave.runner.screen.remote.url=http://127.0.0.1:4444/wd/hub
# Default: null | LocalizaÃ§Ã£o do driver que faz   ligaÃ§Ã£o   entre o navegador e o webdriver - Máquina Local

behave.runner.screen.driverPath=C:\TestesAutomatizados\IEDriverServer.exe
# BinaryPath Máquina Local

behave.runner.screen.binaryPath=C:\Program Files\Internet Explorer\iexplore.exe

Segue abaixo o erro do log.

Started InternetExplorerDriver server (64-bit)
2.53.1.0
Listening on port 47043
Only local connections are allowed
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
17:04:18,787 ERROR (main) [ScreenShootingMaker]: Erro ao salvar screenshot [] caminho [C:\TestesAutomatizados\testeautomatizado\target\jbehave\view\screenshots\
failed-scenario-b68e153c-6dc1-4f6a-bcf2-15c84e5a39fb.png] causa [null]
17:04:18,788 ERROR (main) [ScreenShootingMaker]: java.lang.NullPointerException
br.gov.frameworkdemoiselle.behave.parser.jbehave.BeforeAfterSteps.startStories() (FAILED)
(org.jbehave.core.failures.BeforeOrAfterFailed: Method startStories (annotated with @BeforeStories in class br.gov.frameworkdemoiselle.behave.parser.jbehave.Bef
oreAfterSteps) failed: org.openqa.selenium.remote.SessionNotFoundException: Unexpected error launching Internet Explorer. Protected Mode settings are not the sa
me for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones. (WARNING: The server did not provide any stacktrace i
nformation)
Command duration or timeout: 741 milliseconds
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'SERPROS-1OSPVAG', ip: '10.3.3.7', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver)

Running story stories\internet\aderirModalidade\aderirModalidadeLogandoViaCodigoAcesso.storyConverted
Funcionalidade: Aderir Modalidade - Listar modalidades para o contribuinte
(stories\internet\aderirModalidade\aderirModalidadeLogandoViaCodigoAcesso.storyConverted)
Scenario: Listar modalidades para o contribuinte logando com codigo de acesso
Using timeout for story aderirModalidadeLogandoViaCodigoAcesso.storyConverted of 21600 secs.
17:04:19,194 ERROR (pool-1-thread-1) [ScreenShootingMaker]: Erro ao salvar screenshot [] caminho [C:\TestesAutomatizados\testeautomatizado\target\jbehave\view\s
creenshots\failed-scenario-339ee6ed-8ef4-4051-981d-d028c5ed732c.png] causa [null]

**Comment by juliancesar** [comment]
@Ildeberto, existe uma página na Wiki com relação a esta compatibilidade e realmente ainda não temos dados sobre o IE 9.

Caso algum outro colega tenha experiência com o assunto ou se você conseguir avançar, por favor, nos repasse a informação.

https://github.com/demoiselle/behave/wiki/Compatibilidade-de-Navegadores

Obrigado pela colaboração.

**Comment by juliancesar** [comment]
Corrigindo: existem sim dados para o IE9 no Windows 7 (64-bits).

**Comment by ThiagoNicolielo** [comment]
@Ildeberto, tente também ver se esse Wiki te ajuda:
[Configurações para rodar os testes no Internet Explorer (IE), a partir do Eclipse do Ubuntu (rodar remotamente)](https://github.com/demoiselle/behave/wiki/Configura%C3%A7%C3%B5es-para-rodar-os-testes-no-Internet-Explorer-%28IE%29,-a-partir-do-Eclipse-do-Ubuntu-%28rodar-remotamente%29)

**Comment by juliancesar** [comment]
@Ildeberto, conseguiu avançar no assunto?

**Comment by juliancesar** [comment]
Vou fechar esta issue, caso o problema tenha persistido favor comentar.
