### ISSUE TITLE
Comentários e anotações no Story Reports

### ISSUE THREAD

**Issue by lucianojs** [demoiselle/behave#433]
Seria interessante adicionar os comentários e anotações no Story Reports.

Imagino ser possível pois verifiquei isto em relatórios de outros projetos que utilizam Jbehave (sem dbehave).

Este exemplo mostra a exibição das anotações:
https://www.continuumsecurity.net/bdd-example-report/view/automated_scanning.html

**Comment by juliancesar** [comment]
@lucianojs, pelo que entendi você quer que no relatório do JBehave aonde mostram as histórias também apareçam os comentários, correto? E você também disse que existem outros projetos que fazem isso somente com JBehave, você poderia mandar outro exemplo? O atual não existe mais.

Eu acredito que provavelmente existe uma implementação de REPORT nestes projetos que você citou, hoje o DBehave possui 2, uma padrão chamada **DefaultStoryReport** e outra que envia os dados para a ALM chamada **ALMStoryReport**. Outra coisa que fazemos é adicionar o screenshot do erro no relatório na classe **ScreenShootingHtmlOutput**.

Com base nestas informações acredito que você consiga evoluir na ideia.

**Comment by lucianojs** [comment]
Aquele link realmente quebrou, não achei outro exemplo da Web.

Tem um projeto legado aqui, que utilizava puramente Jbehave que apresenta os os comentários (conforme anexo).

Não tenho nenhum exemplo com as anotações, mas acho que é na mesma linha.

![captura de tela de 2016-11-21 15-34-08](https://cloud.githubusercontent.com/assets/5367385/20493569/813f4390-b000-11e6-8039-5936f9e1bc40.png)

Vou investigar estes reports, caso eu tenha um avanço atualizo aqui.

**Comment by juliancesar** [comment]
@lucianojs, acredito que sei qual é a questão! Na funcionalidade de REUSO de histórias nós recriamos elas para fazer as "injeções" das partes, e neste momento é bem possível que ignoremos os comentários!

De uma olhada neste arquivo do core, ele foi trazido de outro framework para a reutilização de histórias.
https://github.com/demoiselle/behave/blob/master/impl/core/src/main/java/br/gov/frameworkdemoiselle/behave/internal/parser/StoryConverter.java

**Comment by juliancesar** [comment]
Então! Retiramos propositalmente!
https://github.com/demoiselle/behave/blob/master/impl/core/src/main/java/br/gov/frameworkdemoiselle/behave/internal/parser/StoryConverter.java#L229

Você acredita que deveria ser parametrizável?

**Comment by lucianojs** [comment]
Bom, eu acredito que o comentário no report agrega a leitura do resultado.
Além do mais me parece ser um comportamento padrão do JBehave.

Sabe me dizer o motivo da remoção do comentário?

E quanto ao número do caso de teste no RQM (conforme abaixo)? Seria útil a sua exibição também no report.

Meta:
@casodeteste 12346

**Comment by juliancesar** [comment]
Luciano, acredito por já termos o comportamento padrão de não mostrar podemos causar problemas em alterar, sendo que a primeira coisa que penso é que o tamanho dos logs de execução irão aumentar consideravelmente, o que pode gerar grandes problemas! Mas podemos adicionar uma propriedade que possa alterar este comportamento já na versão 1.5.3, ou quem sabe na 1.5.2.

Com relação ao comportamento padrão ser assim eu não tenho a resposta, pois como comentei essa funcionalidade foi importada de outro framework, que eu acho que foi do @antonioclaudioneiva, se ele puder nos ajudar neste assunto serei grato!

Com relação a Meta eu preciso verificar se se encaixa na mesma situação, por isso peço a gentileza de abrir outra issue sobre o assunto.

Obrigado.
