### ISSUE TITLE
Cenários quebraram após migração da 1.5.1 para a 1.5.2-BETA1

### ISSUE THREAD

**Issue by lucianojs** [demoiselle/behave#438]
Realizei um teste de migração para a versão 1.5.2-BETA1 e alguns cenários quebraram.

Gerei um HTML simples e os exemplos abaixo na tentativa de isolar e facilitar a análise.

HTML

```
<html>
<body>
<div class="col-sm-6">
        Para mais informações, consulte a
            <a href="/portal-td/cotacoes" id="linkTabelaCotacoes" routerlink="/cotacoes">Tabela de Rentabilidades</a>.
</div>

<div>
                O e-mail de confirmação de troca de senha será enviado para o endereço
                ********n*e*@automacao.com.<br><br>
                Deseja prosseguir?<br><br>
</div>
</body>
<html>
```

```
Cenário: teste 1

Dado que vou para a tela "teste"
Então será exibido "Para mais informações, consulte a Tabela de Rentabilidades"

Cenário: teste 2

Dado que vou para a tela "teste"
Então será exibido "O e-mail de confirmação de troca de senha será enviado para o endereço ********n*e*@automacao.com"
```

**Comment by juliancesar** [comment]
Só para confirmar, este mesmo cenário funcionava com a 1.5.2-SNAPSHOT?
Aguardo;

**Comment by juliancesar** [comment]
Eu já havia percebido esse problema ao rodar o sample do site do DBehave (https://github.com/demoiselle/behave/tree/master/sample/dbehave-site/src/test) e já estou tratando ele.

Obrigado.

**Comment by juliancesar** [comment]
Favor testar com a BETA2.

**Comment by lucianojs** [comment]
Falha permanece no BETA2

**Comment by juliancesar** [comment]
Perceba que no seu texto tem uma quebra de linha, retire a quebra de linha e provavelmente irá funcionar.

O dbehave não interpreta as quebras.

Julian Cesar

Enviado de um dispositivo móvel.

**Comment by lucianojs** [comment]
Não entendi @juliancesar 

Realizei a alteração no HTML

```
<html>
<body>
<div class="col-sm-6">
        Para mais informações, consulte a <a href="/portal-td/cotacoes" id="linkTabelaCotacoes" routerlink="/cotacoes">Tabela de Rentabilidades</a>.
</div>

<div>
                O e-mail de confirmação de troca de senha será enviado para o endereço ********n*e*@automacao.com.<br><br>
                Deseja prosseguir?<br><br>
</div>
</body>
<html>
```

O teste 1 continuou quebrado.
O teste 2 passou a funcionar, contudo se o Dbehave não interpreta as quebras, porque funcionada na 1.5.1?
Além disto não tenho controle sobre o HTML gerado pela aplicação. 
Para o usuário que vê o HTML renderizado não existe distinção entre os 2 códigos.




Pro usuário da aplicação esta quebra de

**Comment by juliancesar** [comment]
Acho que não fui claro! O DBehave interpreta o texto como esta no HTML, inclusive as tags.

Algumas considerações:

1. O html que vc me passou não vai funcionar de qualquer maneira pois não esta setado o encoding (formatação do texto), para que funcionasse precisei setar no HTML - http://demoiselle.sourceforge.net/docs/components/behave/samples/textVisible.html
2. Criei um caso de teste para a situação no projeto mix:
  * Page: https://github.com/demoiselle/behave/blob/master/sample/mix/src/test/java/demoisellebehave/mix/pages/TextVisible.java
  *  Test: https://github.com/demoiselle/behave/blob/master/sample/mix/src/test/java/demoisellebehave/mix/tests/TextVisibleTest.java
   * Story: https://github.com/demoiselle/behave/blob/master/sample/mix/src/test/resources/stories/text/textVisible.story
3. O que eu notei é que por fazermos a busca por meio de um XPath ele não trabalha bem com tags e caracteres que sejam da sintaxe do XPath, talvez possamos melhorar neste ponto, sinta-se a vontade para fazer uma sugestão de código
* https://github.com/demoiselle/behave/blob/master/impl/runner/webdriver/src/main/java/br/gov/frameworkdemoiselle/behave/runner/webdriver/ui/WebBase.java#L622
4. Toda esta funcionalidade de encontrar texto na tela foi remodelada na versão 1.5.2 para ficar mais rápida, pois existiam várias reclamações de demora
5. Não entendi quem é o usuário na sua frase! Pois o utilizador do framework deve ter um minimo de conhecimento de HTML e tem ferramentas para verificar este tipo de situação, e o usuário final que utiliza a aplicação normalmente não tem acesso a estes testes para saber que esta "quebrado"! A sua colocação não ficou clara.

**Comment by juliancesar** [comment]
Estou fazendo vários testes e criando novos para tentar chegar em uma solução melhor, mas realmente temos um problema aqui!

**Comment by juliancesar** [comment]
@lucianojs, favor testar com a SNAPSHOT atual (gerada em 25/11/2016 17:03).

**Comment by lucianojs** [comment]
problema resolvido.

**Comment by juliancesar** [comment]
@lucianojs, obrigado pela colaboração.
