### ISSUE TITLE
Eclipse Neon... O que é preciso para rodar o dBehave?

### ISSUE THREAD

**Issue by malaguti** [demoiselle/behave#444]
Caros colegas.

Alguém já usa o dBehave com o Eclipse Neon? Caíram em alguma "pegadinha"? Se depararam com algum ponto fora da curva? Alguma documentação ou indicação de literatura?

Desde já grato por qualquer ajuda.

**Comment by juliancesar** [comment]
@malaguti, a principio estou rodando todos os testes normalmente no Neon, você teve algum problema?

**Comment by botelhojp** [comment]
Também usei com o Neon.1 para Ubuntu 16, 64bits e não tive problema.

**Comment by malaguti** [comment]
Oi Julian. Desculpe a demora.
Atualmente eu rodo o dBehave no kepler, que é, até onde eu sei, a distribuição do Framework Demoiselle. Quando eu fui atualizar a versão do RTC para 5.0.2, aconteceram problemas que eu só resolvi, depois de pastar muito, e ter muita ajuda.
Nesse meio tempo eu fiz uma tentativa de fazer o Neon funcionar com o RTC e o dBehave, mas, como isso demandou uma trabalheira doida (haja plugins, ainda mais usando a "ruinternet" que temos...), e o problema no Kepler foi solucionado, eu meio que abortei a missão, mas gostaria demais de começar a trabalhar com o Neon. Sabe como é... De uma hora pra outra podem ocorrer incompatibilidades irreconciliáveis, e a gente sabe que, nessas horas, as coisas saem tudo à fórceps, num stress danado. Por causa disso eu prefiro estar sempre atualizado, no que diz respeito à ferramentas de trabalho.

Se alguém puder disponibilizar um zip com o neon já com o o Demoiselle framework, e o maven já configurado pro dBahave, eu agradeço penhoradamente.

**Comment by juliancesar** [comment]
@malaguti, completando o que o @botelhojp comentou, acredito que para este caso a melhor saída seja utilizar o Neon padrão para o DBehave que já possui quase todos os plugins (exceto o de histórias que pode seguir os mesmos passos da documentação: http://demoiselle.sourceforge.net/docs/components/behave/reference/lastversion/html/behave-story.html#d0e1809) e para fazer o versionamento (plugin RTC) utilizar o eclipse fornecido pelo Serpro.

Entendo que esta não é a melhora saída, contudo é o que podemos oferecer hoje.

Obrigado pela sua atenção.

**Comment by malaguti** [comment]
Obrigado @botelhojp, e obrigado @juliancesar, Eu, pela sua resposta Julian, estou assumindo que o RTC não vai funcionar com o Neon, ou , pelo menos, não vale o esforço. Será que funciona com o Mars? Essa coisa de ter dois Eclipses usando a mesma área de trabalho, como eu suponho que seja necessário para trabalhar em um, e versionar em outro, não me parece ser muito "saudável"... Outra coisa Julian... Aonde eu obtenho o Neon padrão para dBehave? Nas minhas fuçadas preliminares, eu não encontrei nenhuma pista da criança.

**Comment by juliancesar** [comment]
@malaguti, realmente como comentei usar 2 eclipses não é o ideal, mas é o que tempos por enquanto.

Com relação a usar o Eclipse padrão, estou me referindo ao eclipse baixado diretamente no site em sua versão **Eclipse IDE for Java EE Developers** (baixe a versão do seu SO - 32 ou 64 bits), no link abaixo:
https://www.eclipse.org/downloads/eclipse-packages/

A versão **Eclipse IDE for Java EE Developers** já contém todas as ferramentas, exceto o plugin para auto complete de histórias que para instalar baixar seguir os passos do seguinte link:
http://demoiselle.sourceforge.net/docs/components/behave/reference/lastversion/html/behave-story.html#d0e1809

**Comment by malaguti** [comment]
Valeu @juliancesar! Muito obrigado pela ajuda.

**Comment by malaguti** [comment]
Senhores.
Consegui instalar o Neon, já configurado, e rodando o dBehave, e, com ele o RTC 5.0.2 funcionando.
Se alguém quiser, eu faço um ZIP e disponibilizo.
