### ISSUE TITLE
Execução dos testes na versão 1.5.2 muito mais lenta

### ISSUE THREAD

**Issue by otmarjr** [demoiselle/behave#447]
Pessoal

Nossa equipe aqui notou que após migrar para a versão 1.5.2 a execução ficou sensivelmente mais lenta. É possível melhorar isso e retomar o desempenho das versões anteriores ?

**Comment by juliancesar** [comment]
Olá @otmarjr, precisamos de mais informações sobre em que frases está mais lento, pois principalmente nas frases relacionadas a verificação de textos dentro das páginas (_[Então] será exibido "< texto >"_) existiam inconsistências que foram corrigidas. Ver issue #382.

> Lembrando que a frase é **PRIMEIRO** executada e **DEPOIS** mostrada no console, portanto a lentidão que ocorre deve ser da frases **EM EXECUÇÃO**.

A lentidão que percebemos é quando o código fonte da página é muito grande e o Java precisa verificar a existência do texto dentro do texto, e para este caso recomendamos que seja utilizada a expressão _[Então] será exibido na "< nome do elemento >" o valor "< valor >"_ que é busca apenas em determinado elemento.

**Comment by juliancesar** [comment]
Criei uma página na Wiki para irmos acompanhando o assunto, já que ele é uma questão importante que deve ser analisada com calma.

https://github.com/demoiselle/behave/wiki/Verifica%C3%A7%C3%A3o-de-Texto-em-P%C3%A1ginas

**Comment by juliancesar** [comment]
Foram feitas várias melhorias no código para que os testes ficassem mais rápidos. Em breve será lançada a versão 1.5.3.

**Comment by juliancesar** [comment]
A versão **1.5.3** foi lançada agora pouco contendo as melhorias desta issue.

O release notes esta disponível em:
http://demoiselle.sourceforge.net/docs/components/behave/reference/lastversion/html/release.html

Favor testar e caso o problema persista, favor reabrir.

**Comment by mmsps** [comment]
_**[Então] "< nome do elemento >" não está visível**_ está muito lento na versão 1.5.2 e 1.5.3, você poderia dar uma olhada @juliancesar?

**Comment by juliancesar** [comment]
@mmsps, sugiro que você habilite as estatísticas da ferramenta (adicionando a propriedade behave.runner.showExecutionStatistics=true no seu behave.properties) e verifique no log a ação mais lenta, a partir desta informação podemos tentar melhorar este ponto.

> a propriedade behave.runner.showExecutionStatistics só esta disponível a partir da versão **1.5.3**.

**Comment by mmsps** [comment]
Oi @juliancesar,
Eu executei com a propriedade = true mas não identifiquei onde ficam armazenados os Logs.  Notei que o console não mostra nada nas versões 1.5.2 e 1.5.3, como faço pra mostrar o andamento da execução no console como era antes?

**Comment by juliancesar** [comment]
Modo debug é ativado pelo arquivo log4j.xml, segue um exemplo:
https://github.com/demoiselle/behave/blob/master/sample/treino/src/test/resources/log4j.xml#L24

**Comment by mmsps** [comment]
Oi @juliancesar,
Ví que o método waitInvisible() era baseado usa a propriedade behave.runner.screen.maxWait e behave.runner.screen.minWait e a minha propriedade behave.runner.screen.maxWait estava 50000, então reduzi para 5000 e agora tá rodando numa velocidade legal.
