### ISSUE TITLE
Execução paralela configuração

### ISSUE THREAD

**Issue by Viveiros** [demoiselle/behave#450]
Boa tarde, fiz a configuração conforme a instrução na documentação, http://demoiselle.sourceforge.net/docs/components/behave/reference/lastversion/html/behave-execucao.html#d0e2400
Porem não abriu duas instancias de browser, seria só em modo background?

**Comment by juliancesar** [comment]
Olá @Viveiros, alguma evolução na questão levantada?
Obrigado pela colaboração.

**Comment by cesarfex** [comment]
@Viveiros Também tenho a necessidade de paralelizar a execução, vamos conversar a respeito. Entra no https://chat.serpro.gov.br/channel/testes-funcionais

**Comment by juliancesar** [comment]
@Viveiros, conseguiu avançar no assunto? Caso tenha conseguido nos deixe aqui sua solução.

Obrigado pela colaboração.

**Comment by juliancesar** [comment]
Issue concluída, caso ainda tenha problemas favor reabrir.
