### ISSUE TITLE
Testes automatizados em produção

### ISSUE THREAD

**Issue by malaguti** [demoiselle/behave#453]
Conteúdo removido --

**Comment by malaguti** [comment]
@juliancesar, @rogernobre

**Comment by botelhojp** [comment]
@malaguti esse assunto deve ser discutido internamente pelos times do SERPRO. Num passado não tão distante usávamos uma lista interna para discutir assuntos entre os times de testes.
Peço a compreensão de não utilizar o canal do Demoiselle Behave para esse tipo de questão.

**Comment by malaguti** [comment]
Certo. Vou colocar no Você Serpro. Não tenho como retirar a issue. Se você puder, faça. Ok?

**Comment by botelhojp** [comment]
Ótimo, discutiremos lá, a issue não pode ser deleta, mas vou remover seu conteúdo.
