### ISSUE TITLE
Sikuli: Problemas com Sikuli em ambiente Ubuntu com 2 monitores

### ISSUE THREAD

**Issue by ThiagoNicolielo** [demoiselle/behave#455]
Pessoal, alguém consegue utilizar o sikuli no OS Ubuntu com 2 monitores?

Por algum motivo parece que ele identifica errado a direção que ele precisa mover o mouse para o outro monitor.

Tentei resolver, encontrar na internet soluções, achei pessoas com problemas parecidos mas não pude resolver.

Para funcionar então, eu tenho que ir em debug e antes de executar a procura do botão via sikuli, eu preciso arrastar a janela para o monitor que o sikuli está conseguindo manipular, então, eu preciso desabilitar o uso do sikuli enquanto na minha máquina, mas caso a máquina de integração contínua utilize 2 monitores e Ubuntu, talvez ocorra o mesmo problema.

Caso alguém tenha tido este problema e encontrado uma solução, por favor divulgue aqui o que lembrar de como conseguiu resolver.

Grato!

**Comment by juliancesar** [comment]
Olá @ThiagoNicolielo, alguma evolução no problema?
Obrigado pela colaboração.

**Comment by ThiagoNicolielo** [comment]
Não, mas esta semana o meu SO será atualizado de Ubuntu 12.04 para 16.04.

Estou há tempos esperançoso que nesta versão existam atualizações dos gerenciadores de janelas que possam corrigir este problema.

**Comment by cesarfex** [comment]
@ThiagoNicolielo Vamos conversar a respeito. Entra no https://chat.serpro.gov.br/channel/testes-funcionais

**Comment by juliancesar** [comment]
@ThiagoNicolielo, avançou neste assunto?

**Comment by ThiagoNicolielo** [comment]
O problema foi resolvido após o upgrade do Ubuntu para a versão 16.04.
Obrigado.
