### ISSUE TITLE
Erro ao tentar verificar checkbox selecionado mas desabilitado

### ISSUE THREAD

**Issue by otmarjr** [demoiselle/behave#458]
No sistema em que atuo há uma funcionalidade de visualizar um cadastro. No teste automatizado, ao verificar que um checkbox está desabilitado (devido ao visualizar) e selecionado, ocorre um erro. Ao verificar o fonte do GitHub, notei na classe WebCheckbox o método isSelected:

`waitVisibleClickableEnabled();`

Entendo que não se deve considerar que o checkbox está habilitado e clicável para verificar se ele está selecionado, devido aos casos como o meu, de apresentação de uma tela no modo somente leitura.

**Comment by juliancesar** [comment]
Olá @otmarjr, alguma evolução no problema?
Obrigado pela colaboração.

**Comment by otmarjr** [comment]
Resolvi com um passo customizado.
