### ISSUE TITLE
Recuperar informação dinâmica na tela e guardar para testes posteriores

### ISSUE THREAD

**Issue by amandasaraiva** [demoiselle/behave#460]
Pessoas,

estou com a necessidade de pegar uma informação na página que está sendo testada e guardar esta informação para testes e verificações posteriores. É possível realizar este tipo de teste usando o Dbehave?

Para entender a necessidade, quando crio uma instância de um objeto no sistema, após a finalização com sucesso desta criação, o sistema retorna um número que identifica o objeto que acabou de ser criado. A partir deste número podem ser feitas outras operações (basicamente de busca). 

Não achei algo semelhante na implementação do framework. Dei uma olhada nas discussões aqui e também não encontrei. Aparentemente é possível fazer isto com Selenium, mas fiquei me perguntando se seria viável fazer isso usando story's, já que aparentemente nenhuma story 'retorna' nenhuma informação.

Obrigada desde já.

**Comment by juliancesar** [comment]
Não sei se entendi direito, mas existem algumas maneiras de armazenar dados, seguem:
* Conjunto de Dados - http://demoiselle.sourceforge.net/docs/components/behave/reference/lastversion/html/behave-dados.html
* Usando as frases:
`[Dado que | Quando | Então] obtenho "<VARIAVEL>" do campo "<nome do campo>"`
`[Dado que | Quando | Então] informo "<chave>" com valor "<VARIAVEL>"`
* Tabelas tabelas de exemplo do JBehave: `[Quando] informo: $table`

Acredito que o mais simples seja usar as frases obtenho e informo.

**Comment by cesarfex** [comment]
@amandasaraiva @juliancesar 
Vamos conversar a respeito. Entra no https://chat.serpro.gov.br/channel/testes-funcionais

**Comment by juliancesar** [comment]
@amandasaraiva, algum retorno sobre o assunto?

**Comment by juliancesar** [comment]
@amandasaraiva, vou fechar esta issue, e caso necessite pode reabrir.
