### ISSUE TITLE
Mapeamento de xPath que usa Id não está funcionando.

### ISSUE THREAD

**Issue by malaguti** [demoiselle/behave#461]
Tive que deixar o dBehave parado um período, para ajudar em testes exploratórios. Agora, recomeçando o trabalho com o dBehave, comecei a tomar uns erros, em storyes já prontas e testadas. O erro me pareceu mapeamento, e eu tratei de refazê-los, mas o erro continuava. Perdido, sem saber o que fazer, comecei a experimentar várias coisas, até que eu refiz o mapeamento sem ID no xpath. Pronto! funcionou!!! Parece que a nova versão do dBehave está de mau com os ID para mapeamento, quando usado dentro dos xPaths. E, mesmo quando referenciado como ID, eles dão erro. Eu tenho todo um sistema, mais de meia centena de pages, com dezenas e mais dezenas de maps em cada uma delas... Vou ter que trocar tudo por xPath sem ID? Sendo que o ID era meu porto seguro, pra não ter que refazer o mapeamento de tudo na página, caso uma vírgula  fosse alterada...
Alguém pode me ajudar?

**Comment by juliancesar** [comment]
Olá,

precisamos de mais informações:
* Qual versão do Dbehave você esta usando?
* Isso esta ocorrendo em todas as situações?

Nos mante pelo menos 3 exemplos do caso relatado para que possamos analisar.

Aguardo.

**Comment by malaguti** [comment]
Oi @juliancesar !
Acredito estar usando a versão 1.5.3 me diga, por favor, aonde eu verifico isso.
Em que situações? Está acontecendo nas situações exemplo logo abaixo:

@ElementMap(name = "Voltar", locatorType = ElementLocatorType.Id, locator = "dsisRedistribuidas:botaoVoltar")
@ElementMap(name = "MenuDU_E-->DistribuicaoRedistribuicao", locatorType = ElementLocatorType.XPath, locator = "id('hdr_nav')/x:ul/x:li[4]/x:ul/x:li[1]/x:a")

Pelos meus testes, bastou usar ID, pras storyes falharem.

**Comment by juliancesar** [comment]
O trecho que descreve a versão do DBehave utilizada é a seguinte:
```xml
<parent>
	<groupId>br.gov.frameworkdemoiselle.component.behave</groupId>
	<artifactId>demoiselle-behave-parent</artifactId>
	<version>1.5.2</version>
</parent>
```
> No caso acima a versão é a **1.5.2**

Agora preciso de outras informações:
* Os seus testes funcionavam com qual versão do DBehave?
* Qual a possibilidade do software ter mudado a tela, pois veja que em um dos exemplo que usou uma estrutura hierárquica que pode ter sido alterada, ou até mesmo o próprio ID na aplicação

Estas perguntas tem o objetivo de saber se é um erro de uma nova versão do DBehave, se sim em qual ponto, ou se o software que esta sendo testado que foi alterado durante o período.

**Comment by malaguti** [comment]
Oi @juliancesar .

O trecho que descreve a versão do dBehave se encontra em qual artefato?

Eu posso lhe afirmar que, à dois meses atrás, as storyes em questão funcionavam.
Com relação à possibilidade do software ter mudado a tela, eu conferi, e refiz os mapeamentos que apresentaram erro, usando o View XPath, e o FirePath, e não houveram mudanças nos mapeamentos que apresentaram defeitos. Só mesmo o problema relatado.

Existe um outro componente a ser considerado. O meu sistema foi incorporado ao Pucomex. Acontece que o meu sistema se tornou um sistema JSF, chamado de dentro de um portal único desenvolvido em Angular JS. Eu não sei quais as consequências, para o dBehave, com relação à essa configuração.

**Comment by juliancesar** [comment]
Todas as verões ficam no arquivo `pom.xml`.

Outras perguntas:
1. à dois meses atrás qual era a versão do DBehave e qual é a versão hoje?
2. a informação de que o sistema foi ou não alterado me parecem imprecisas, já que em um momento vc relata que os XPaths não mudaram e em outro o sistema foi migrado para JSF o que implica em dezenas de modificações já que a estrutura JSF é diferente de qualquer outra framework
3. Alguma busca por ID esta funcionando?

Por enquanto só vejo 2 opções:
1. o sistema mudou a estrutura geral das telas, o que pode impactar nos locators
2. as novas versões do DBehave tem algum problema com a descoberta de elementos

Com relação a opção 1 acredito que essa incorporação a outro sistema pode ter ocasionado muitas modificações que podem estar impactando nos testes, e neste caso realmente todos os mapeamentos terão de ser revistos.

Na opção 2 peço que descubra a versão atual e a versão que estava sendo rodada a 2 meses atrás para chegarmos a alguma conclusão.

Aguardo.

**Comment by malaguti** [comment]
@juliancesar .

De qualquer maneira, eu refiz os mapeamentos que deram erro, e, mesmo assim, eles continuaram dando erro. Só quando eu retirei o ID do mapeamento, eles pararam de apresentar erro.

As páginas do meu sistema não mudaram. Elas continuam a mesma coisa, ou, pelo menos, deveriam, porque eu utilizo extensamente os IDs como ponto de partida para os meus mapeamentos, e, refazendo os mesmos, eles não apresentaram modificação alguma. Ou seja: os mapeamentos refeitos são idênticos ao mapeamento salvo nos maps, à +/- dois meses atrás, antes do workflow ser incorporado ao portal.

Eu imaginava que proceder dessa maneira ia fazer com que eu tivesse alguma paz, com relação à mudanças pontuais nas telas do meu sistema, e é esse o motivo do acionamento. O ID, no caso do meu sistema, é a fonte do problema com os mapeamentos utilizado nas minhas storyes.

Ao que tudo indica, o dBehave está recusando a utilização do mesmo, no caso do meu sistema.

Se eu for obrigado a alterar todos os mapeamentos, para HTML puro, sem ID, isso vai "quebrar a firma", porque eles são muitos, e eu vou tomar erro à cada virgula que for incorporada a qualquer das telas do sistema.

É esse o motivo do meu pedido de ajuda. Eu já poderia ter resolvido o problema remapeando tudo para não usar o ID, mas gostaria de continuar utilizando o ID, pelos motivos supracitados.

**Comment by juliancesar** [comment]
Vc ainda não me respondeu qual era a versão de 2 meses atrás e a atual do DBehave. Pois se o sistema não mudou o dbehave deve ter mudado e basta voltar a versão para funcionar.

**Comment by malaguti** [comment]
@juliancesar .

Mil perdões. Eu cometi um equivoco terrível.

Eu parti do princípio de que o Maven iria me trazer a versão mais atual do dBehave, quando eu instalei o Neon, e parece que não foi o que aconteceu...

Meu pom.xml está assim:
	<parent>
		<groupId>br.gov.frameworkdemoiselle.component.behave</groupId>
		<artifactId>demoiselle-behave-parent</artifactId>
		<version>1.5.1</version>
	</parent>

Mas isso me leva a constatação. A versão 1.5.1 era a que eu tinha à dois meses atrás, então não é um problema de versão.
Isso me leva a outro questionamento: Se eu atualizar a versão para 1.5.3, eu vou conseguir resolver o problema?

**Comment by juliancesar** [comment]
Nas versões mais novas do maven é possível sempre pegar a versão mais nova, contudo podem ocorrer problemas, por isso não é muito recomendado.

No cenário atual, sabendo que a versão do DBehave que esta sendo usada agora é exatamente a mesma de 2 meses atrás a conclusão que chego é que o sistema foi alterado de alguma maneira que pode ter quebrado os testes feitos, uma das pistas já mencionadas é a questão da migração para JSF.

Sugiro que abra uma Solicitação de Serviço na ALM (Área Gestão SUPSD / Assunto Demoiselle Behave) e assim que eu puder atender eu acessarei a sua máquina e verificar o que pode estar ocorrendo.

**Comment by malaguti** [comment]
@juliancesar .
Como eu faço o Maven me instalar a versão 1.5.3? Será que isso pode ajudar?
Aonde eu Abro essa solicitação de Serviço?

**Comment by juliancesar** [comment]
Para subir a versão basta alterar a tag VERSION do seu `pom.xml`:
```xml
<parent>
   <groupId>br.gov.frameworkdemoiselle.component.behave</groupId>
   <artifactId>demoiselle-behave-parent</artifactId>
   <version>1.5.3</version>
</parent>
```

Não tenho como afirmar se o seu problema será resolvido! Até pq acredito que o problema não esteja na ferramenta e sim no sistema.

Sobre a abertura da Solicitação de Serviço.

> Sugiro que abra uma Solicitação de Serviço na ALM (Área Gestão SUPSD / Assunto Demoiselle Behave) e assim que eu puder atender eu acessarei a sua máquina e verificar o que pode estar ocorrendo.

**Comment by malaguti** [comment]
Oi @juliancesar .
Eu já tinha lido o texto replicado.
Eu preciso saber qual o canal que eu utilizo para fazer a SS.

**Comment by juliancesar** [comment]
Vc irá utilizar a ALM na intranet. http://alm.serpro

Julian Cesar

Enviado de um dispositivo móvel.

**Comment by juliancesar** [comment]
@malaguti, você conseguiu avançar no assunto?

Neste período sem mensagens foi lançada a versão **1.5.3** (http://dbehave.com/) que sugiro que utilize.

**Comment by juliancesar** [comment]
Issue concluída, caso ainda tenha problemas favor reabrir.
