### ISSUE TITLE
Possível bug na classe BehaveContext

### ISSUE THREAD

**Issue by ThiagoNicolielo** [demoiselle/behave#464]
Note que na classe BehaveContext, DBehave 1.5.2, o método getStepsMethod está retornando stepsGlobal, quando acredito que deveria retornar stepsMethod, variável utilizada no método addStepsMethod acima:

	public void addStepsMethod(Step step) {
		if (!BehaveConfig.getRunner_legacyRunner())
			stepsMethod.add(step);
		else
			throw new BehaveException(bm.getString("exception-legacyRunner-false"));
	}

	public List<Step> getStepsMethod() {
		if (!BehaveConfig.getRunner_legacyRunner())
			return stepsGlobal;
		else
			throw new BehaveException(bm.getString("exception-legacyRunner-false"));
	}

**Comment by juliancesar** [comment]
Verifique para mim se este é o mesmo caso do Pull Request que esta pendente:
https://github.com/demoiselle/behave/pull/452

**Comment by juliancesar** [comment]
@ttperes, vc poderia nos ajuda nisso?

**Comment by juliancesar** [comment]
@ThiagoNicolielo, tente fazer alguns testes com a versão **1.5.3** e veja se o problema ainda acontece.

Aguardo.

**Comment by ThiagoNicolielo** [comment]
@juliancesar 
Primeiramente, o pior é que não lembro mais para que eu estava precisando deste método getStepsMethod() naquele momento, acho que resolvi meu problema daquele dia com outra abordagem.

Mas, de qq forma, aproveito para te informar então que, ao entrando no método BehaveContext.getStepsMethod(), ainda está retornando stepsGlobal ao invés de stepsMethod.

Não sei, mas me parece estranho que o método addStepsMethod(Step step) adicione este "step" na lista stepsMethod e que o método getStepsMethod() retorne a lista stepsGlobal.

Posso estar enganado, mas acredito que a solução seria apenas refatorar o método alterando de "return stepsGlobal;" para "return stepsMethod;"
Isso pode gerar algum impacto, claro, o que poderia ser analisado durante este refactoring.

Gostaria de ajudar fazendo isso eu mesmo e enviando como pull request, mas sinceramente tenho pouco conhecimento deste processo, uso muito pouco, e compreendo pouco as entranhas do DBehave, então não sei nem rastrear quem usa este método dentro das classes do DBehave (eu tento rastrear vendo sua Call Hierarchy mas não aparece nada, talvez por eu não ter os projetos baixados, e sim apenas via maven dependencies.
Enfim, nessas coisas eu apanho um pouco.

Mas se quiser tentar me ajudar nisto, blz, mas é um refactoring simples e acho que o custo/benefício pode não ser vantajoso. Mas realmente, nada contra se optarmos por isso, também.

Muito obrigado Julian, pela sua sempre atenciosa ajuda!
