### ISSUE TITLE
Behave - Cenarios da suite não sendo executados se um cenarios anterior falha na versao 1.5.3

### ISSUE THREAD

**Issue by bamattos** [demoiselle/behave#467]
Prezados,

Ao migrar o Behave da versão 151 para a 153 passei a ter o seguinte comportamento; quando coloco uma suite para rodar e um cenário de teste falha, todos os cenários seguintes falham.

Quando executava a suite na versão 151 e um cenário falhava, os cenários seguintes eram executados, dessa forma todos os cenários sempre eram executados sendo marcados com falha apenas os que efetivamente quebraram.

Segue tela com o resultado da execução da suite no 151:

![versao151](https://cloud.githubusercontent.com/assets/28906643/26404647/08b6aa0e-4069-11e7-945a-97b8d57717aa.png)

As suites, no meu caso, foram construídas a partir de uma classe Java com métodos, individuais, que chamam os cenários para execução e reuso.

Quando preciso executar um cenário individualmente clico em cima do nome do metodo correspondente e seleciono "Run as jUnit", quando preciso rodar a suite toda clico no nome da classe e seleciono "Run as JUnit".

Meu problema agora no 153 é que se um cenário no meio da suite falha, os seguintes nem são executados, segue tela:

![versao153](https://cloud.githubusercontent.com/assets/28906643/26404667/16fc3d68-4069-11e7-8ec5-b30c8466b247.png)

Seguem exemplos de como as classes e metodos estão escritos:

Grato.

```java
public class ClasseDeTeste_ExecutaCenariosGerais_CADASTRO{ 

	private BehaveContext eng = null;
	
	Server server = new Server();

	@Test
	public void Cenario_CADASTRO_DE_USUARIO_ComSucesso() throws Throwable {
						
		// historias minimas
		eng.addStoriesReuse("/stories/caminho para cenario de reuso 001;
		eng.addStoriesReuse("/stories/caminho para cenario de reuso 002;
		eng.addStoriesReuse("/stories/caminho para cenario de reuso 003;
										
		// historia principal 
		eng.addStories("/stories/caminho para o cenario principal;
		eng.run();
		eng.clearAllOriginalStories();
	}

	@Test
	public void Cenario_CADASTRO_DE_USUARIO_ComFalha() throws Throwable {
							
		// historias minimas
		eng.addStoriesReuse("/stories/caminho para cenario de reuso 001;
		eng.addStoriesReuse("/stories/caminho para cenario de reuso 002;
		eng.addStoriesReuse("/stories/caminho para cenario de reuso 003;
											
		// historia principal 
		eng.addStories("/stories/caminho para o cenario principal;
		eng.run();
		eng.clearAllOriginalStories();
	}

}
```

**Comment by juliancesar** [comment]
@bamattos, se puder nos envie qual frase exatamente o comportamento acontece para que possamos ver a diferença entre as versões 1.5.1, 1.5.2 e 1.5.3.

**Comment by juliancesar** [comment]
@bamattos, outro ponto importante, na versão 1.5.2 qual é o comportamento?

**Comment by bamattos** [comment]
@juliancesar 

Testei a 152  e 153 com duas frases, "Quando clico...", original e "Quando informo Documento no campo...", a segunda frase foi personaliza para o nosso sistema, em ambos forcei a primeira frase a falhar colocando um nome de elemento inexistente na história, não modifiquei o mapeamento, quando houve a falha nesse campo todos os demais cenários quebraram, para a segunda frase houve falha pois ela depende de um serviço que gera o documento a ser informado em um campo e o serviço estava fora do ar, neste caso também todos os cenários seguintes falharam.

**Comment by juliancesar** [comment]
@rogernobre, @ThiagoNicolielo, @Viveiros, @estivalet e @delmarfilho acredito que este assunto seja **importante** para discutirmos em grupo para chegarmos a uma conclusão juntos, gostaria que cada um de vocês explicitasse uma opinião para que sabe modificarmos o comportamento da ferramenta, caso não possam ajuda peço a gentileza de indicar alguém que possa colaborar com o grupo.

**Comment by ThiagoNicolielo** [comment]
Vi com o @bamattos e na minha máquina funcionou normalmente, na versão 1.5.3, após um cenário falhar.
Não sei dizer pq na dele não funciona, já que com aquele outro problema, que na máquina dele os testes demoravam muito, verificamos que praticamente tudo, senão tudo, estava igual entre nossas máquinas.

**Comment by juliancesar** [comment]
@ThiagoNicolielo, será que tem relação com rodar diretamente pelo JUnit ou pelo Maven?

**Comment by juliancesar** [comment]
@ThiagoNicolielo, algum retorno sobre o assunto?

**Comment by ThiagoNicolielo** [comment]
Pelo que me lembro, o problema foi resolvido.
