### ISSUE TITLE
Integração Testlink

### ISSUE THREAD

**Issue by estivalet** [demoiselle/behave#471]
Existe a possibilidade de executar os testes automatizados especificados na ferramenta Testlink usando a API (https://github.com/kinow/testlink-java-api)? Algum exemplo? Obrigado

Explicando um pouco melhor... quero ter os meus cenários de teste armazenados no Testlink e de alguma forma via a API baixar esses testes para execução com o dbehave e retornar os resultados para o Testlink marcando o teste como falho ou com sucesso.

**Comment by juliancesar** [comment]
Eu nunca vi uma integração dessa por aqui.
Será necessário desenvolver um novo **Parser** com base no do JBehave (que baixe os testes, save os arquivos localmente e se necessário converta para o formato do JBhehave) e outro **Integration** (pode ser usado o da ALM como exemplo) para enviar as informações novamente para o Testlink.

**Comment by juliancesar** [comment]
@estivalet, avançou neste assunto? Posso fechar a issue?

**Comment by juliancesar** [comment]
Issue concluída, caso ainda tenha problemas favor reabrir.
