### ISSUE TITLE
Padronizar o nome do componente "Tree" do PrimeFaces

### ISSUE THREAD

**Issue by ahvsoares** [demoiselle/behave#473]
No código do _runner_ Webdriver, todos os componentes do PrimeFaces começam com "PrimeFaces", exceto o componente "Tree".

Sugiro que o nome seja alterado para de "Tree" para "PrimeFacesTree", seguindo o padrão de nomenclatura do _framework_.

Esse componente também não deveria implementar "br.gov.frameworkdemoiselle.behave.runner.ui.Tree"?

**Comment by juliancesar** [comment]
@ahvsoares, você esta correto, na verificação no Pull Request este detalhe passou batido, pois apesar de funcionar não esta utilizando a interface e dificulta a identificação do componente quando esta no Page Object.

Vou fazer a alteração e terei que alertar os usuários no Release Notes com relação a quebra.

**Comment by juliancesar** [comment]
A alteração já esta na versão **1.5.4-SNAPSHOT** e estará disponível na versão final **1.5.4**.
