### ISSUE TITLE
É possível automatizar o preenchimento do componente ng2-select do Angular usando o CommonSteps?

### ISSUE THREAD

**Issue by lucianojs** [demoiselle/behave#475]
Estamos automatizando algumas telas em angular 4 e um dos campos utiliza o componente ng2-select, gostaria de um auxílio em como automatizar o preenchimento deste elemento.
Veja abaixo um demo de como é o componente:

http://valor-software.com/ng2-select/

Acredito que posso trabalhar o preenchimento com duas alternativas, como um Autocomplete ou como um Select/ListBox. 

Minha dúvida é se é possível utilizar os elementos nativos ou terei que implementar um passo personalizado para interagir com o componente.

**Comment by lucianojs** [comment]
Consegui automatizar usando a seguinte abordagem:

Criar um passo reutilizável com 3 passos:
Cenário: Selecionar "{dado}" no campo "{componente}"
Quando clico em "Abrir Seleção"
Quando informo "{dado}" no campo "{componente}"
Quando clico em "Confirmar Seleção"

E no page object crio 3 elements relacionados ao componentes:
 @ElementMap(name = "Abrir Seleção", locatorType = ElementLocatorType.XPath, locator = "/html/body/demo-app/div/select-section/section/div[1]/tabset/div/tab[1]/sample-section/single-demo/div/ng-select/div/div[2]/span")
 private Link abrirSeleção;
 
 @ElementMap(name = "cor", locatorType = ElementLocatorType.XPath, locator = "/html/body/demo-app/div/select-section/section/div[1]/tabset/div/tab[1]/sample-section/single-demo/div/ng-select/div/input")
 private TextField cor;
 
 @ElementMap(name = "Confirmar Seleção", locatorType = ElementLocatorType.XPath, locator = "/html/body/demo-app/div/select-section/section/div[1]/tabset/div/tab[1]/sample-section/single-demo/div/ng-select/div/ul/li/div/a")
 private Link confirmarSeleção;

Com isto basta utilizar o passo abaixo no cenário de teste:
Selecionar "azul" no campo "cor"

Acho que foi a forma mais simples que percebi de como automatizar sem ficar criando steps personalizadas.
Vou deixar a questão aberta por um tempo para avalia se existe alguma outra solução.
Para fins de gestão pode fechá-la quando achar adequado.

**Comment by juliancesar** [comment]
@lucianojs, você tentou usar a estratégia do Select do Primefaces?

Você pode ver ele no sample mix:
* História: https://github.com/demoiselle/behave/blob/master/sample/mix/src/test/resources/stories/primefaces/input.story#L7
* Page Object: https://github.com/demoiselle/behave/blob/master/sample/mix/src/test/java/demoisellebehave/mix/pages/PrimefacesSelectOneMenu.java

**Comment by lucianojs** [comment]
Não, não tentei.

Estou de férias, quando retornar vou tentar.

Grato,

**Comment by juliancesar** [comment]
Vou fechar esta issue, e caso a questão ainda persista basta reabrir.
