### ISSUE TITLE
Componente para manipular Grid's

### ISSUE THREAD

**Issue by arildojg** [demoiselle/behave#61]
Pessoal:
   Alguém já está desenvolvendo implementação de componente para trabalhar com grid no DBehave?

   Em dois projetos que pretendemos usar o DBehave aqui em Florianópolis, dependemos de um componente para trabalhar com grid's que trate os casos de:
 - células com campos editáveis;
 - checkbox de seleção de linhas;
 - pesquisa de elementos em uma linha qualquer de uma página qualquer da grid;

   Antes de iniciarmos uma implementação (ou talvez mais uma implementação), gostaria de saber o que já existe feito nas demais regionais. Talvez exista código que possa ser reutilizado e/ou soluções que possam ser combinadas para produzir uma versão inicial de algo mais genérico.

**Comment by juliancesar** [comment]
Foi publicada uma nova versão **1.4.3-SNAPSHOT** contendo o novo componente de Grid para Primefaces.

@arildojg, o colega @ttperes sugeriu uma implementação via PR e gostaria que você desse uma olhada para ver se atende as suas necessidades.

**Comment by arildojg** [comment]
Fiz alguns testes aqui mapeando uma grid com o elemento PrimefacesGrid. 
Não temos como trocar o que fizemos e usar esta implementação, pois não atende a todas as situações que tratamos hoje. 
Mas achei que a implementação é útil e ficou boa pois está simples.
Pelo que vi no código e pelo que implementamos aqui, notei que não tem como fugir da concatenação de xpaths. 
Temos um xpath que serve como base, e nele adicionamos xpaths, em geral parametrizados, para chegar ao local pretendido na tabela (linha, célula, coluna etc). Isso também observei na solução proposta pelo PR.
O que talvez se torne um problema é a variabilidade dos xpaths.
Deixá-los no código tem o lado bom e o lado ruim. O lado bom é que deixa a a implementação mais clara e fácil de compreender. O lado ruim é que pode mudar diversas vezes conforme peculiaridades de cada sistema. 
Como exemplo, posso citar o caso de ter vários botões em uma única célula, o que exigiria um outro xpath para a instrução.
A forma como implementamos aqui, os xpaths, tanto o de base para a tabela quanto o os demais usados para concatenar, foram deixados fora da implementação e são mapeados em uma classe que descreve como é a estrutura da(s) grid(s) do sistema.
Deixa mais flexível a mudanças de estrutura na grid, porém torna o código bem mais difícil de compreender e o mapeamento fica mais complicado.

Enfim, achei que a implementação é util. Só talvez valha a pena estudar uma forma para permitir alterar a estrutura dos xpaths utilizados na concatenação. Se for possível essa melhoria vai evitar vários PR's a longo prazo para atender peculiaridades que surgirão nos sistemas.

OBS: Uma dificuldade aparece frequentemente e nem sempre conseguimos contornar apenas setando parâmetros de pesquisa, é verificar se em alguma página de resultado, tem uma linha na qual a coluna X tem valor Y.  Algo do tipo: 
Quando na grid "Pesquisa de Pessoas", busco a linha cuja coluna "Nome" tem valor "Maria Demoiselle Behave" e na coluna "Ações" e clico em "Detalhar Pessoas".
Se a implementação puder ser evoluída para suportar buscas na grid em várias páginas seria ótimo. 
Porém isso envolve mais um complicador, que é mapear e manipular também a barra de navegação.

**Comment by ttperes** [comment]
Bom dia  @arildojg !

O problema de se trabalhar com tables, é que dentro de uma table você pode se quiser ter uma página HTML inteira em uma célula, o que torna inviável tentar mapear todas as situações "a priori". O focado na implementação foram as tables "de dados", comum nas listagens dos sitemas que temos aqui (atualmente a implementação proposta atende a 2 grandes sistemas do DERJO, Remessa e DBK Isenção).

Esta situação "Como exemplo, posso citar o caso de ter vários botões em uma única célula, o que exigiria um outro xpath para a instrução." citada eu já havia pensado nela e quando tiver um tempo no projeto que estou trabalhando pretendo ampliar o suporte para isso. Seria algo do tipo "Quando clico no elemento "x"..." e aproveitaria todos os outros comportamentos já criados.

Já existe uma frase que trata o caso da sua observação (aliás pode ser feito de 2 maneiras): Tem a frase de comparar texto e ainda uma frase que armazena o conteúdo de uma célula e você pode compará-la. Quanto a página de resultado, a implementação varia muito, e a falta de suporte a instruções de loop nas histórias causa esse problema. Acredito que o ideal seria ter instruções nas histórias que suportassem loop, assim poderíamos ir navegando em qualquer tipo de conjunto de dados, não somente tabelas.

**Comment by juliancesar** [comment]
Senhores, essa issue será fechada pois já foram implemetadas algumas frases pré-definidas para a manipualação de grid, e acredito que a partir delas podemos adicionar novas de acordo com a necessidade. 

Segue o link para a documentação:
http://demoiselle.sourceforge.net/docs/components/behave/reference/lastversion/html/behave-story.html

Item **4.3. Frases pré-definidas pelo framework para manipulação de Grids**

**Comment by arildojg** [comment]
Perfeito

Lembrando que há uma segunda implementação de grid feita por um colega da regional de BH, que também possui frases úteis, pois permitem verificar valores e manipular elementos sem saber previamente os índices de linha e coluna. Estamos usando em um sistema e funcionou bem.
Exemplo: 
![exemplogriddinamicosemordenacao](https://cloud.githubusercontent.com/assets/4246255/8310014/deb68370-19a3-11e5-8b9e-b0f130bed4aa.png)

Mapeamento:
```
	@GridMap(name = "Grid Listagem Pessoas", locatorType = ElementLocatorType.Id, locator = { "form:idListagemPessoasDataTable" })
    private WebGrid listagemPessoasGrid;
    @ChildGridMap(name = "Coluna Matrícula", parentName = "Grid Listagem Pessoas", locatorType = ElementLocatorType.Id, locator = { "form:idListagemPessoasDataTable:#:idMatriculaListagemPessoasOutputText" })
    private Label matricula;
    @ChildGridMap(name = "Coluna Nome", parentName = "Grid Listagem Pessoas", locatorType = ElementLocatorType.Id, locator = { "form:idListagem PessoasDataTable:#:idNomeListagemPessoasOutputText" })
    private Label nome;
    @ChildGridMap(name = "Coluna Idade", parentName = "Grid Listagem Pessoas", locatorType = ElementLocatorType.Id, locator = { "form:idListagemPessoasDataTable:#:idIdadeListagemPessoasOutputText" })
    private Label idade;
    @ChildGridMap(name = "Coluna Profissão", parentName = "Grid Listagem Pessoas", locatorType = ElementLocatorType.Id, locator = { "form:idListagemPessoasDataTable:#:idProfissaoListagemPessoasOutputText" })
    private Label profissao;
    @ChildGridMap(name = "Editar", parentName = "Grid Listagem Pessoas", locatorType = ElementLocatorType.Id, locator = { "form:idListagemPessoasDataTable:#:editarListagemPessoasCommandButton" })
    private Button editar;
```

Feito o mapeamento da Grid e das Colunas teríamos as frases:

```
Então é exibido "Coluna Idade" da tabela "Grid Listagem Pessoas" com valor igual a "28" onde "Coluna Matrícula=4984985"

Quando clico no campo "Editar" da tabela "Grid Listagem Pessoas" onde "Nome=Pedro de Araújo"
```
Sugiro abrir um issue para avaliar como incorporar essa outra abordagem ao fw DBehave!

Em conversa, comentou-se que já há até iniciativas locais de evoluções dessa grid para permitir fazer essas buscas em mais de uma página.

O que acham?

**Comment by arildojg** [comment]
Pelo que vi ha algum tempo, com essa nova implementação teríamos 3 no Fw, não sei se é possível/viável fazer um "merge" delas:

![implementacoesdegridnofw](https://cloud.githubusercontent.com/assets/4246255/8310939/7f8f4b9c-19a9-11e5-9ec5-a9067aed172a.jpg)

**Comment by juliancesar** [comment]
@arildojg, com relação as diversas classes de table, na verdade existem 2, e eu vou fazer o merge, agora a **GridSteps** acredito ser uma classe de Steps do seu projeto!
Obrigado pela colaboração.

**Comment by rogernobre** [comment]
@ttperes, tem como colocar aqui um exemplo de mapeamento do grid que usem os passos que estão no framework ou ainda se possivel tem como fazer um pull request com algum exemplo de uso do GridSteps?

**Comment by ttperes** [comment]
@rogernobre bom dia cara! Na sexta fiquei em uma planning a tarde toda só vi sua msg hoje. Então você mapeia a tabela somente até o 1o TR.  ex: id('tabela')/tr ou se for com tbody vai id('tabela')/tbody/tr
